/* 
 *  TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 */

package com.autentia.intra.businessobject;

import com.autentia.intra.dao.ITransferObject;
import com.autentia.intra.dao.hibernate.UserDAO;

import java.io.Serializable;
import java.util.Date;

/**
 * Transfer object to store Interactions
 *
 * @author stajanov code generator
 */
public class Interaction implements Serializable, ITransferObject {
    public static boolean historial = true;

    private Organization client;

    public Organization getClient() {
        if (this.project != null)
            return this.project.getClient();
        else
            return client;
    }

    public void setClient(Organization client) {
        this.client = client;
    }

    public String getClientName() {
        if (this.client != null)
            return this.client.getName();

        if (this.project != null)
            return this.project.getClient().getName();

        return null;
    }

    public void setClientName() {
    }

    /**
     * Serial version field
     */
    private static final long serialVersionUID = -1L;

/* interaction - generated by stajanov (do not edit/delete) */

    // Fields


    private Integer id;


    private Date creationDate;


    private InteractionInterest interest;


    private InteractionMedio medio;


    private String why;


    private String description;


    private String file;


    private String fileMime;


    private String observations;


    private Integer departmentId;


    private Date insertDate;


    private Date updateDate;


    private Project project;


    private InteractionType type;


    private User user;


    private Offer offer;

    // Setters and getters


    public Integer getId() {
        return id;
    }

    private void setId(Integer id) {
        this.id = id;
    }


    public Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }


    public InteractionInterest getInterest() {
        return interest;
    }

    public void setInterest(InteractionInterest interest) {
        this.interest = interest;
    }


    public InteractionMedio getMedio() {
        return medio;
    }

    public void setMedio(InteractionMedio medio) {
        this.medio = medio;
    }


    public String getWhy() {
        return why;
    }

    public void setWhy(String why) {
        this.why = why;
    }


    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }


    public String getFile() {
        return file;
    }

    public void setFile(String file) {
        this.file = file;
    }


    public String getFileMime() {
        return fileMime;
    }

    public void setFileMime(String fileMime) {
        this.fileMime = fileMime;
    }


    public String getObservations() {
        return observations;
    }

    public void setObservations(String observations) {
        this.observations = observations;
    }


    public Integer getDepartmentId() {
        return departmentId;
    }

    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }


    public Date getInsertDate() {
        return insertDate;
    }

    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }


    public Date getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }


    public Project getProject() {
        return project;
    }

    public void setProject(Project project) {
        this.project = project;
        if (project != null)
            this.client = project.getClient();
    }


    public InteractionType getType() {
        return type;
    }

    public void setType(InteractionType type) {
        this.type = type;
    }


    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }


    public Offer getOffer() {
        return offer;
    }

    public void setOffer(Offer offer) {
        this.offer = offer;
    }

    public Integer getOwnerId() {
        return user.getId();
    }


    public void setOwnerId(Integer ownerId) {
        user = UserDAO.getDefault().getById(ownerId);
    }


    public boolean equals(Object that) {
        try {
            if (that == null)
                return false;
            else
                return this.getId().equals(((Interaction) that).getId());
        } catch (Exception e) {
            return false;
        }
    }

    public int hashCode() {
        if (this.getId() == null)
            return super.hashCode();
        else
            return this.getId().intValue();
    }
/* interaction - generated by stajanov (do not edit/delete) */

    private Integer updatedById;

    public Integer getUpdatedById() {
        return updatedById;
    }

    public void setUpdatedById(Integer updatedById) {
        this.updatedById = updatedById;
    }
}
