/*
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.
 *
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com
 */

package com.autentia.intra.businessobject;

import com.autentia.intra.dao.ITransferObject;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import java.util.Set;

public class Offer implements Serializable, ITransferObject {
    public static boolean historial = true;

    private Bill bill;
    private Set<Project> projects;
    private Department lineaTrabajo;

    public Department getLineaTrabajo() {
        return lineaTrabajo;
    }

    public void setLineaTrabajo(Department lineaTrabajo) {
        this.lineaTrabajo = lineaTrabajo;
    }

    public Set<Project> getProjects() {
        return projects;
    }

    public void setProjects(Set<Project> projects) {
        this.projects = projects;
    }

    public Bill getBill() {
        return bill;
    }

    public void setBill(Bill bill) {
        this.bill = bill;
    }


    private BigDecimal iva;
    private boolean informesCreados;

    public boolean isInformesCreados() {
        return informesCreados;
    }

    public void setInformesCreados(boolean informesCreados) {
        this.informesCreados = informesCreados;
    }

    public BigDecimal getIva() {
        return iva;
    }

    public void setIva(BigDecimal iva) {
        this.iva = iva;
    }

/* Offer - generated by stajanov (do not edit/delete) */


    private String orderNumber;

    public String getOrderNumber() {
        return orderNumber;
    }

    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    // Fields


    private Integer id;


    private String number;


    private String title;


    private String description;


    private String observations;


    private Date creationDate;


    private Date validityDate;


    private Date maturityDate;


    private OfferState offerState;


    private OfferPotential offerPotential;


    private BigDecimal totalRoles;


    private BigDecimal totalEnsayos;


    private BigDecimal totalPautas;


    private BigDecimal totalCosts;


    private BigDecimal total;


    private Integer ownerId;


    private Integer departmentId;


    private Date insertDate;


    private Date updateDate;


    private User user;


    private Organization organization;


    private Contact contact;


    private OfferRejectReason offerRejectReason;


    private Set<Interaction> interactions;


    private Set<OfferRole> roles;


    private List<OfferEnsayo> ensayos;


    private List<OfferPauta> pautas;


    private Set<OfferCost> costs;

    // Setters and getters


    public Integer getId() {
        return id;
    }

    private void setId(Integer id) {
        this.id = id;
    }


    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }


    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }


    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }


    public String getObservations() {
        return observations;
    }

    public void setObservations(String observations) {
        this.observations = observations;
    }


    public Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }


    public Date getValidityDate() {
        return validityDate;
    }

    public void setValidityDate(Date validityDate) {
        this.validityDate = validityDate;
    }


    public Date getMaturityDate() {
        return maturityDate;
    }

    public void setMaturityDate(Date maturityDate) {
        this.maturityDate = maturityDate;
    }


    public OfferState getOfferState() {
        return offerState;
    }

    public void setOfferState(OfferState offerState) {
        this.offerState = offerState;
    }


    public OfferPotential getOfferPotential() {
        return offerPotential;
    }

    public void setOfferPotential(OfferPotential offerPotential) {
        this.offerPotential = offerPotential;
    }


    public BigDecimal getTotalRoles() {
        return totalRoles;
    }

    public void setTotalRoles(BigDecimal totalRoles) {
        this.totalRoles = totalRoles;
    }


    public BigDecimal getTotalEnsayos() {
        return totalEnsayos;
    }

    public void setTotalEnsayos(BigDecimal totalEnsayos) {
        this.totalEnsayos = totalEnsayos;
    }


    public BigDecimal getTotalPautas() {
        return totalPautas;
    }

    public void setTotalPautas(BigDecimal totalPautas) {
        this.totalPautas = totalPautas;
    }


    public BigDecimal getTotalCosts() {
        return totalCosts;
    }

    public void setTotalCosts(BigDecimal totalCosts) {
        this.totalCosts = totalCosts;
    }


    public BigDecimal getTotal() {
        return total;
    }

    public void setTotal(BigDecimal total) {
        this.total = total;
    }


    public Integer getOwnerId() {
        return ownerId;
    }

    public void setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
    }


    public Integer getDepartmentId() {
        return departmentId;
    }

    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }


    public Date getInsertDate() {
        return insertDate;
    }

    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }


    public Date getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }


    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }


    public Organization getOrganization() {
        return organization;
    }

    public void setOrganization(Organization organization) {
        this.organization = organization;
    }


    public Contact getContact() {
        return contact;
    }

    public void setContact(Contact contact) {
        this.contact = contact;
    }


    public OfferRejectReason getOfferRejectReason() {
        return offerRejectReason;
    }

    public void setOfferRejectReason(OfferRejectReason offerRejectReason) {
        this.offerRejectReason = offerRejectReason;
    }


    public Set<Interaction> getInteractions() {
        return interactions;
    }

    public void setInteractions(Set<Interaction> interactions) {
        this.interactions = interactions;
    }


    public Set<OfferRole> getRoles() {
        return roles;
    }

    public void setRoles(Set<OfferRole> roles) {
        this.roles = roles;
    }


    public List<OfferEnsayo> getEnsayos() {
        return ensayos;
    }

    public void setEnsayos(List<OfferEnsayo> ensayos) {
        this.ensayos = ensayos;
    }


    public List<OfferPauta> getPautas() {
        return pautas;
    }

    public void setPautas(List<OfferPauta> pautas) {
        this.pautas = pautas;
    }


    public Set<OfferCost> getCosts() {
        return costs;
    }

    public void setCosts(Set<OfferCost> costs) {
        this.costs = costs;
    }


    @Override
    public boolean equals(Object that) {
        try {
            if (that == null)
                return false;
            else
                return this.getId().equals(((Offer) that).getId());
        } catch (Exception e) {
            return false;
        }
    }

    @Override
    public int hashCode() {
        if (this.getId() == null)
            return super.hashCode();
        else
            return this.getId().intValue();
    }

/* Offer - generated by stajanov (do not edit/delete) */


    private Integer updatedById;

    public Integer getUpdatedById() {
        return updatedById;
    }

    public void setUpdatedById(Integer updatedById) {
        this.updatedById = updatedById;
    }
}
