/* 
 *  TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 */

package com.autentia.intra.businessobject;

import com.autentia.intra.dao.ITransferObject;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Collection;
import java.util.Date;
import java.util.List;


/**
 * Transfer object to store Pauta
 *
 * @author auto code generator
 */
public class Pauta implements Serializable, ITransferObject {
    public static boolean historial = true;

    /**
     * Serial version field
     */
    private static final long serialVersionUID = -1L;

/* pauta - generated by auto (do not edit/delete) */

    // Fields

    private Date insertDate;
    private BigDecimal cost;
    private Integer departmentId;

    private List<PautaEnsayo> ensayos;
    private Date updateDate;
    private String name;
    private String description;
    private Integer id;
    private Integer ownerId;
    private Integer updatedById;
    private String ensayosSolicitados;
    private Collection<PautaPrecio> pautaprecios;
    private String titulo;
    private String familia;
    private List<PautaIdentificacion> referenciasCliente;
    private Integer tiempoRespuesta;
    private String referenciaCliente;

    public String getReferenciaCliente() {
        return referenciaCliente;
    }

    public void setReferenciaCliente(String referenciaCliente) {
        this.referenciaCliente = referenciaCliente;
    }

    public Integer getTiempoRespuesta() {
        return tiempoRespuesta;
    }

    public void setTiempoRespuesta(Integer tiempoRespuesta) {
        this.tiempoRespuesta = tiempoRespuesta;
    }

    public List<PautaIdentificacion> getReferenciasCliente() {
        return referenciasCliente;
    }

    public void setReferenciasCliente(List<PautaIdentificacion> referenciasCliente) {
        this.referenciasCliente = referenciasCliente;
    }

    public String getFamilia() {
        return familia;
    }

    public void setFamilia(String familia) {
        this.familia = familia;
    }

    public String getTitulo() {
        return titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public Collection<PautaPrecio> getPautaprecios() {
        return pautaprecios;
    }

    public void setPautaprecios(Collection<PautaPrecio> pautaprecios) {
        this.pautaprecios = pautaprecios;
    }

    public Organization getCliente() {
        return cliente;
    }

    public void setCliente(Organization cliente) {
        this.cliente = cliente;
    }

    public String getMaterial() {
        return material;
    }

    public void setMaterial(String material) {
        this.material = material;
    }

    public String getAgrupacion() {
        return agrupacion;
    }

    public void setAgrupacion(String agrupacion) {
        this.agrupacion = agrupacion;
    }

    private Organization cliente;
    private String material;
    private String agrupacion;

    public String getEnsayosSolicitados() {
        return ensayosSolicitados;
    }

    public void setEnsayosSolicitados(String ensayosSolicitados) {
        this.ensayosSolicitados = ensayosSolicitados;
    }

    public Integer getUpdatedById() {
        return updatedById;
    }

    public void setUpdatedById(Integer updatedById) {
        this.updatedById = updatedById;
    }

    // Setters and getters

    public BigDecimal getCost() {
        return cost;
    }

    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    public Integer getDepartmentId() {
        return departmentId;
    }

    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    public List<PautaEnsayo> getEnsayos() {
        return ensayos;
    }

    public void setEnsayos(List<PautaEnsayo> ensayos) {
        this.ensayos = ensayos;
    }

    public Integer getId() {
        return id;
    }

    private void setId(Integer id) {
        this.id = id;
    }

    public Date getInsertDate() {
        return insertDate;
    }

    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getOwnerId() {
        return ownerId;
    }

    public void setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
    }

    public Date getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }


    @Override
    public boolean equals(Object that) {
        try {
            if (that == null)
                return false;
            else
                return this.getId().equals(((Pauta) that).getId());
        } catch (Exception e) {
            return false;
        }
    }

    @Override
    public int hashCode() {
        if (this.getId() == null)
            return super.hashCode();
        else
            return this.getId().intValue();
    }

/* pauta - generated by auto (do not edit/delete) */

}


