<%-- 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 *
 --%>

<%@page language="java" contentType="text/html; charset=UTF-8" %>

<%@include file="/inc/tlibs.jsp" %>

<html>
<head>
    <%@include file="/inc/uiCore.jsp" %>
</head>
<body>

<f:loadBundle basename="com.autentia.intra.resources.messages" var="msg"/>
<i:location place="editOccupation" msg="${msg}"/>

<f:view>
<%@include file="/inc/header.jsp" %>
<h:form id="editOccupation" enctype="multipart/form-data">

    <%-- Header --%>
<i:titleBar name="${occupationBean.startDate}" msg="${msg}">
    <h:commandLink action="#{occupationBean.save}"
                   onclick="if(!askSave('#{occupationBean.id}','#{msg['question.confirmSave']}')) return false;">
        <h:graphicImage title="#{msg.entityActions_save}" value="/img/save.gif" styleClass="titleImg"/>
    </h:commandLink>
    <h:commandLink action="#{occupationBean.delete}"
                   onclick="if( !confirm('#{msg['question.confirmDelete']}') ) return false;">
        <h:graphicImage title="#{msg.entityActions_delete}" value="/img/delete.gif" styleClass="titleImg"/>
    </h:commandLink>
    <h:commandLink action="#{occupationBean.list}" immediate="true">
        <h:graphicImage title="#{msg.entityActions_back}" value="/img/back.gif" styleClass="titleImg"/>
    </h:commandLink>
</i:titleBar>
    <%-- Edition form --%>
<table class="editTable" cellpadding="0" cellspacing="0">
        <%-- occupation - generated by stajanov (do not edit/delete) --%>


        <%-- Ignored field: id --%>

        <%-- Field: user --%>
    <tr>
        <td class="editLabelRW">*${msg['occupation.user']}:</td>

        <td class="editFieldCell">

            <h:panelGroup>
                <h:message styleClass="error" showSummary="true" showDetail="false" for="user"/>
                <h:selectOneMenu id="user" value="#{occupationBean.user}" required="true"
                                 styleClass="requiredFieldClass">
                    <f:selectItems value="#{occupationBean.users}"/>
                    <f:converter converterId="autentia.EntityConverter"/>
                </h:selectOneMenu>
            </h:panelGroup>

        </td>
    </tr>

        <%-- Field: organization --%>
    <tr>
        <td class="editLabelRW">${msg['occupation.organization']}:</td>
        <td class="editFieldCell">
            <h:panelGroup>
                <h:message styleClass="error" showSummary="true" showDetail="false" for="organization"/>
                <h:selectOneMenu id="organization" value="#{occupationBean.selectedOrganization}" immediate="true"
                                 onchange="submit()"
                                 valueChangeListener="#{occupationBean.onSelectedOrganizationChanged}">
                    <f:selectItems value="#{occupationBean.organizations}"/>
                    <f:converter converterId="autentia.EntityConverter"/>
                </h:selectOneMenu>
            </h:panelGroup>
        </td>
    </tr>


        <%-- Field: project --%>
    <tr>
        <td class="editLabelRW">*${msg['occupation.project']}:</td>

        <td class="editFieldCell">

            <h:panelGroup>
                <h:message styleClass="error" showSummary="true" showDetail="false" for="project"/>
                <h:selectOneMenu id="project" value="#{occupationBean.project}" required="true"
                                 styleClass="requiredFieldClass">
                    <f:selectItems value="#{occupationBean.projectsBySelectedOrganization}"/>
                    <f:converter converterId="autentia.EntityConverter"/>
                </h:selectOneMenu>
            </h:panelGroup>

        </td>
    </tr>


        <%-- Field: startDate --%>
    <tr>
        <td class="editLabelRW">*${msg['occupation.startDate']}:</td>

        <td class="editFieldCell">

            <h:panelGroup>
                <h:message styleClass="error" showSummary="true" showDetail="false" for="startDate"/>
                <t:inputCalendar id="startDate" value="#{occupationBean.startDate}" required="true"
                                 styleClass="requiredFieldClass"
                                 renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true"
                                 popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                        />
            </h:panelGroup>

        </td>
    </tr>


        <%-- Field: endDate --%>
    <tr>
        <td class="editLabelRW">*${msg['occupation.endDate']}:</td>

        <td class="editFieldCell">

            <h:panelGroup>
                <h:message styleClass="error" showSummary="true" showDetail="false" for="endDate"/>
                <t:inputCalendar id="endDate" value="#{occupationBean.endDate}" required="true"
                                 styleClass="requiredFieldClass"
                                 renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true"
                                 popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                        />
            </h:panelGroup>

        </td>
    </tr>

        <%-- Field: duration --%>
    <tr>
        <td class="editLabelRW">*${msg['occupation.duration']}:</td>

        <td class="editFieldCell">

            <h:panelGroup>
                <h:message styleClass="error" showSummary="true" showDetail="false" for="duration"/>
                <h:inputText id="duration" value="#{occupationBean.duration}" size="10" required="true"
                             styleClass="requiredFieldClass">
                    <f:converter converterId="autentia.MinuteToHourConverter"/>
                </h:inputText>
            </h:panelGroup>

        </td>
    </tr>


        <%-- Field: description --%>
    <tr>
        <td class="editLabelRW">${msg['occupation.description']}:</td>

        <td class="editFieldCell">

            <h:panelGroup>
                <h:message styleClass="error" showSummary="true" showDetail="false" for="description"/>
                <h:inputTextarea id="description" value="#{occupationBean.description}" rows="5" cols="68"/>
            </h:panelGroup>

        </td>
    </tr>


        <%-- Ignored field: ownerId --%>


        <%-- Ignored field: departmentId --%>


        <%-- Ignored field: insertDate --%>


        <%-- Ignored field: updateDate --%>


        <%-- occupation - generated by stajanov (do not edit/delete) --%>
    </h:form>
    </f:view>
</body>
</html>  	