<%-- 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 *
 --%>
<%@page language="java" contentType="text/html; charset=UTF-8" %>

<%@include file="/inc/tlibs.jsp" %>

<html>
<head>
    <%@include file="/inc/uiCore.jsp" %>
</head>
<body>

<!-- propagateObjective.jsp: generated by stajanov code generator -->
<f:loadBundle basename="com.autentia.intra.resources.messages" var="msg"/>
<i:location place="propagateObjective" msg="${msg}"/>

<f:view>
    <%@include file="/inc/header.jsp" %>
    <h:form id="objective" enctype="multipart/form-data">

        <%-- Header --%>
        <i:titleBar name="${objectiveBean.name}" msg="${msg}">
            <h:commandLink action="#{objectiveBean.confirmPropagate}">
                <h:graphicImage value="/img/save.gif" styleClass="titleImg"/>
            </h:commandLink>
            <h:commandLink action="#{objectiveBean.list}" immediate="true">
                <h:graphicImage value="/img/back.gif" styleClass="titleImg"/>
            </h:commandLink>
        </i:titleBar>

        <%-- Edition form --%>
        <table class="editTable" cellpadding="0" cellspacing="0">

                <%-- Field: log --%>
            <tr>
                <td class="editLabelRW">${msg['objective.log']}:</td>
                <td class="editFieldCell">
                    <h:panelGroup>
                        <h:message styleClass="error" showSummary="true" showDetail="false" for="log"/>
                        <h:inputText id="log" value="#{objectiveBean.log}" size="70" required="true"/>
                    </h:panelGroup>
                </td>
            </tr>

                <%-- Field: childObjectivesCount --%>
            <tr>
                <td class="editLabelRW">${msg['propagateObjective.childObjectivesCount']}:</td>
                <td class="editFieldCell">
                    <h:panelGroup>
                        <h:message styleClass="error" showSummary="true" showDetail="false" for="childObjectivesCount"/>
                        <h:selectOneMenu id="childObjectivesCount" value="#{objectiveBean.childObjectivesCount}">
                            <f:selectItems value="#{objectiveBean.childObjectivesCounts}"/>
                        </h:selectOneMenu>
                    </h:panelGroup>
                </td>
            </tr>

        </table>

    </h:form>
</f:view>

</body>
</html>  		

