<%-- holiday - generated by stajanov (do not edit/delete) --%>


<%--
* TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
*	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.
*
* 	This program is free software; you can redistribute it and/or
* 	modify it under the terms of the GNU General Public License
* 	as published by the Free Software Foundation; either version 2
* 	of the License, or (at your option) any later version.
*
* 	This program is distributed in the hope that it will be useful,
* 	but WITHOUT ANY WARRANTY; without even the implied warranty of
* 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* 	GNU General Public License for more details.
*
* 	You should have received a copy of the GNU General Public License
* 	along with this program; if not, write to the Free Software
* 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*
* 	Autentia Real Bussiness Solution S.L.
* 	Tlf: +34 91 675 33 06, +34 655 99 11 72
* 	Fax: +34 91 656 65 04
* 	info@autentia.com
*
--%>

<%@page language="java" contentType="text/html; charset=UTF-8" %>

<%@include file="/inc/tlibs.jsp" %>

<html>
<head>
    <%@include file="/inc/uiCore.jsp" %>
</head>
<body>


<f:loadBundle basename="com.autentia.intra.resources.messages" var="msg"/>
<i:location place="myHolidays" msg="${msg}"/>

<f:view>
    <%@include file="/inc/header.jsp" %>
    <h:form id="myHolidays">

        <%-- Header --%>
        <i:titleBar msg="${msg}">

        </i:titleBar>

        <h:panelGrid columns="3" cellpadding="0" cellspacing="0" styleClass="editTable"
                     columnClasses="editLabelRW,editFieldCellGlobal,editFieldCellGlobal">
            <h:outputText value="#{msg['userHolidayState.chargeYear']}:"/>
            <t:inputCalendar id="startDate" value="#{userHolidaysStateBean.chargeYear}" required="true"
                             styleClass="requiredFieldClass"
                             renderAsPopup="true" popupDateFormat="yyyy" renderPopupButtonAsImage="true"
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                             onchange="submit()" valueChangeListener="#{userHolidaysStateBean.changeDate}"/>

            <h:commandButton action="#{userHolidaysStateBean.myHolidays}" title="#{msg['userHolidayState.show']}"
                             value="#{msg['userHolidayState.show']}"/>
        </h:panelGrid>

        <%-- Detail form --%>
        <table class="detailMyHolidays" cellpadding="0" cellspacing="0">


            <tr>
                <td class="detailLabelRW">${msg['userHolidaysState.totalAvailable']}:</td>
                <td class="detailFieldCell">
                    <h:outputText value="#{userHolidaysStateBean.userState.user.agreement.holidays}"/>
                </td>
            </tr>

            <tr>
                <td class="detailLabelRW">${msg['userHolidaysState.totalYear']}:</td>
                <td class="detailFieldCell">
                    <h:outputText value="#{userHolidaysStateBean.userState.totalYear}"/>
                </td>
            </tr>


            <tr>
                <td class="detailLabelRW">${msg['userHolidaysState.totalAccepted']}:</td>
                <td class="detailFieldCell">
                    <h:outputText value="#{userHolidaysStateBean.userState.totalAccepted}"/>
                </td>
            </tr>


            <tr>
                <td class="detailLabelRW">${msg['userHolidaysState.total']}:</td>
                <td class="detailFieldCell">
                    <h:outputText value="#{userHolidaysStateBean.userState.total}"/>
                </td>
            </tr>

                <%-- Ignored field: ownerId --%>


                <%-- Ignored field: departmentId --%>


                <%-- Ignored field: insertDate --%>


                <%-- Ignored field: updateDate --%>


        </table>

    </h:form>
</f:view>

</body>
</html>
<%-- holiday - generated by stajanov (do not edit/delete) --%>
