/*
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.
 *
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com
 */


package com.autentia.intra.manager.holiday;

import com.autentia.intra.businessobject.RequestHoliday;
import com.autentia.intra.dao.SortCriteria;
import com.autentia.intra.dao.hibernate.RequestHolidayDAO;
import com.autentia.intra.dao.search.RequestHolidaySearch;
import com.autentia.intra.util.SpringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.util.List;

public class RequestHolidayManager {

/* RequestHoliday - generated by stajanov (do not edit/delete) */


    /**
     * Logger
     */
    private static final Log log = LogFactory.getLog(RequestHolidayManager.class);

    /**
     * RequestHoliday DAO *
     */
    private RequestHolidayDAO requestHolidayDAO;

    /**
     * Get default RequestHolidayManager as defined in Spring's configuration file.
     *
     * @return the default singleton RequestHolidayManager
     */
    public static RequestHolidayManager getDefault() {
        return (RequestHolidayManager) SpringUtils.getSpringBean("managerRequestHoliday");
    }

    /**
     * Empty constructor needed by CGLIB (Spring AOP)
     */
    protected RequestHolidayManager() {
    }

    /**
     * Default constructor
     *
     * @deprecated do not construct managers alone: use Spring's declared beans
     */
    public RequestHolidayManager(RequestHolidayDAO requestHolidayDAO) {
        this.requestHolidayDAO = requestHolidayDAO;
    }

    /**
     * List requestHolidays.
     *
     * @param search search filter to apply
     * @param sort   sorting criteria
     * @return the list of all requestHolidays sorted by requested criterion
     */
    public List<RequestHoliday> getAllEntities(RequestHolidaySearch search, SortCriteria sort) {
        return requestHolidayDAO.search(search, sort);
    }

    /**
     * Get requestHoliday by primary key.
     *
     * @return requestHoliday selected by id.
     */
    public RequestHoliday getEntityById(int id) {
        return requestHolidayDAO.getById(id);
    }

    /**
     * Insert requestHoliday.
     */
    public void insertEntity(RequestHoliday requestHoliday) {
        requestHolidayDAO.insert(requestHoliday);
    }

    /**
     * Update requestHoliday.
     */
    public void updateEntity(RequestHoliday requestHoliday) {
        requestHolidayDAO.update(requestHoliday);
    }

    /**
     * Delete requestHoliday.
     */
    public void deleteEntity(RequestHoliday requestHoliday) {
        requestHolidayDAO.delete(requestHoliday);
    }

/* RequestHoliday - generated by stajanov (do not edit/delete) */
}
