<%-- Albaran - generated by stajanov (do not edit/delete) --%>


<%--
* TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
*	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.
*
* 	This program is free software; you can redistribute it and/or
* 	modify it under the terms of the GNU General Public License
* 	as published by the Free Software Foundation; either version 2
* 	of the License, or (at your option) any later version.
*
* 	This program is distributed in the hope that it will be useful,
* 	but WITHOUT ANY WARRANTY; without even the implied warranty of
* 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* 	GNU General Public License for more details.
*
* 	You should have received a copy of the GNU General Public License
* 	along with this program; if not, write to the Free Software
* 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*
* 	Autentia Real Bussiness Solution S.L.
* 	Tlf: +34 91 675 33 06, +34 655 99 11 72
* 	Fax: +34 91 656 65 04
* 	info@autentia.com
*
--%>

<%@page language="java" contentType="text/html; charset=UTF-8" %>

<%@include file="/inc/tlibs.jsp" %>

<html>
<head>
    <%@include file="/inc/uiCore.jsp" %>
</head>
<body>

<!-- editAlbaran.jsp: generated by stajanov code generator -->
<f:loadBundle basename="com.autentia.intra.resources.messages" var="msg"/>
<i:location place="detailAlbaran" msg="${msg}"/>

<f:view>
    <%@include file="/inc/header.jsp" %>
    <h:form id="albaran" enctype="multipart/form-data">

        <%-- Header --%>
        <i:titleBar name="${albaranBean.title}" msg="${msg}">
            <t:commandLink action="#{albaranBean.edit}" immediate="true" rendered="#{albaranBean.editAvailable}">
                <f:param name="id" value="#{albaranBean.id}"/>
                <h:graphicImage title="#{msg.entityActions_edit}" value="/img/edit.gif" styleClass="cmdImg"/>
            </t:commandLink>
            <h:commandLink action="#{albaranBean.delete}" rendered="#{albaranBean.deleteAvailable}"
                           onclick="if( !confirm('#{msg['question.confirmDelete']}') ) return false;">
                <h:graphicImage title="#{msg.entityActions_delete}" value="/img/delete.gif" styleClass="titleImg"/>
            </h:commandLink>
            <h:commandLink action="#{albaranBean.list}" immediate="true">
                <h:graphicImage title="#{msg.entityActions_back}" value="/img/back.gif" styleClass="titleImg"/>
            </h:commandLink>
        </i:titleBar>


        <%-- Detail form --%>
        <table class="detailTable" cellpadding="0" cellspacing="0">


                <%-- Ignored field: id --%>


                <%-- Field: name --%>
            <tr>
                <td class="detailLabelRW">Nombre:</td>
                <td class="detailFieldCell">
                    <h:outputText value="#{albaranBean.name}"/>
                </td>
            </tr>


                <%-- Field: fecha --%>
            <tr>
                <td class="detailLabelRW">Fecha:</td>
                <td class="detailFieldCell">
                    <h:outputText value="#{albaranBean.fecha}" converter="autentia.dateConverter"/>
                </td>
            </tr>


                <%-- Field: numero --%>
            <tr>
                <td class="detailLabelRW">Numero:</td>
                <td class="detailFieldCell">
                    <h:outputText value="#{albaranBean.numero}"/>
                </td>
            </tr>


                <%-- Field: devuelto --%>
            <tr>
                <td class="detailLabelRW">Devuelto:</td>
                <td class="detailFieldCell">
                    <h:outputText value="#{albaranBean.devuelto}"/>
                    (indica si el envío incluye material no ensayado devuelto)
                </td>
            </tr>


                <%-- Ignored field: ownerId --%>


                <%-- Ignored field: departmentId --%>


                <%-- Ignored field: insertDate --%>


                <%-- Ignored field: updateDate --%>


                <%-- Field: lineaAlbarans --%>
            <tr>
                <td class="detailLabelRW">Líneas albarán:</td>
                <td class="detailFieldCell">
                    <%@include file="inlineDetailLineaAlbaran.jsp" %>
                </td>
            </tr>


        </table>

    </h:form>
</f:view>

</body>
</html>

<%-- Albaran - generated by stajanov (do not edit/delete) --%>
