<%-- 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 *
 --%>


<%@page language="java" contentType="text/html; charset=UTF-8" %>

<%@include file="/inc/tlibs.jsp" %>

<html>
<head>
    <%@include file="/inc/uiCore.jsp" %>
    <script type="text/javascript">
        function openPDF(id, idOrg) {
            //openReportParameters("document/factura.pdf","?id="+id+"&idOrg="+idOrg+"&idAccount="+account+"&SUBREPORT_BILLHEADER=factura_subreport&SUBREPORT_BILLFOOTERINFO=footerInfo_subreport&SUBREPORT_BILLFOOTERACCOUNT=account_subreport");
            openReportParameters("document/oferta.pdf", "?offerId=" + id + "&idOrg=" + idOrg + "&SUBREPORT_BILLFOOTERINFO=footerInfo_subreport&SUBREPORT_OFFERHEADER=factura_subreport&SUBREPORT_PRESUPUESTO=subreport_presupuesto", "");
        }
    </script>
</head>
<body>

<!-- editOfferRejectReason.jsp: generated by stajanov code generator -->
<f:loadBundle basename="com.autentia.intra.resources.messages" var="msg"/>
<i:location place="editOffer" msg="${msg}"/>

<f:view>
<%@include file="/inc/header.jsp" %>
<h:form id="offer" enctype="multipart/form-data">

<%-- Header --%>
<i:titleBar name="${offerBean.title}" msg="${msg}">
    <h:commandLink action="#{offerBean.save}"
                   onclick="if(!askSave('#{offerBean.id}','#{msg['question.confirmSave']}')) return false;">
        <h:graphicImage title="#{msg.entityActions_save}" value="/img/save.gif" styleClass="titleImg"/>
    </h:commandLink>
    <h:commandLink action="#{offerBean.delete}"
                   onclick="if( !confirm('#{msg['question.confirmDelete']}') ) return false;">
        <h:graphicImage title="#{msg.entityActions_delete}" value="/img/delete.gif" styleClass="titleImg"/>
    </h:commandLink>
    <h:commandLink action="#{offerBean.list}" immediate="true">
        <h:graphicImage title="#{msg.entityActions_back}" value="/img/back.gif" styleClass="titleImg"/>
    </h:commandLink>
    <t:commandLink rendered="#{offerBean.puedoCrearProyecto && offerBean.offer.informesCreados}"
                   action="#{offerBean.copiarTodos}"
                   immediate="true"
                   onclick="if( !confirm('Ya se han creado informes desde este presupuesto, ¿Seguro que desea repetirlos?') ) return false;">
        <f:param name="id" value="#{offerBean.id}"/>
        <h:outputText value="#{msg['offer.copy']}"/>
    </t:commandLink>
    <t:commandLink rendered="#{offerBean.puedoCrearProyecto && !offerBean.offer.informesCreados}"
                   action="#{offerBean.copiarTodos}"
                   immediate="true">
        <f:param name="id" value="#{offerBean.id}"/>
        <h:outputText value="#{msg['offer.copy']}"/>
    </t:commandLink>
    <h:commandLink rendered="#{offerBean.puedoImprimirOferta}" action="#"
                   onclick="openPDF('#{offerBean.id}','#{offerBean.idSelectedOrganization}')" immediate="true">
        <h:graphicImage title="#{msg['offer.print']}" value="/img/document.png" styleClass="titleImg"/>
    </h:commandLink>


</i:titleBar>

<h:messages layout="table" globalOnly="true"/>
<%-- Edition form --%>
<table class="editTable" cellpadding="0" cellspacing="0">


    <%-- Offer - generated by stajanov (do not edit/delete) --%>


    <%-- Ignored field: id --%>


<tr>
    <td class="editLabelRW">${msg['offer.informesCreados']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:outputText value="Aún no existen informes de este presupuesto."
                          rendered="#{empty offerBean.offer.projects}"/>
            <h:outputText value="Existen los siguientes informes: " rendered="#{!empty offerBean.offer.projects}"/>
            <t:dataList var="project" value="#{offerBean.offer.projects}">
                <t:commandLink action="#{projectBean.detail_desde_fuera}" immediate="true" styleClass="enlaceAzul">
                    <f:param name="id" value="#{project.id}"/>
                    <h:outputText value="#{project.referenciaLaboratorio}"/>
                </t:commandLink>
                <h:outputText value=", "/>
            </t:dataList>
        </h:panelGroup>
    </td>
</tr>

    <%-- Field: number --%>
<tr>
    <td class="editLabelRW">*${msg['offer.number']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="number"/>
            <h:inputText id="number" value="#{offerBean.numberDefault}" required="true" styleClass="requiredFieldClass"
                         maxlength="64" validator="#{offerBean.numberValidate}"/>
        </h:panelGroup>
    </td>
</tr>


    <%-- Field: organization --%>
<tr>
    <td class="editLabelRW">*${msg['offer.organization']}:</td>

    <td class="editFieldCell">

        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="organization"/>
            <h:selectOneMenu id="organization" value="#{offerBean.organization}" immediate="true" onchange="submit()"
                             valueChangeListener="#{offerBean.onSelectedOrganizationChanged}">
                <f:selectItems value="#{offerBean.organizations}"/>
                <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
        </h:panelGroup>

    </td>
</tr>


    <%-- Field: contact --%>
<tr>
    <td class="editLabelRW">*${msg['offer.contact']}:</td>

    <td class="editFieldCell">

        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="contact"/>
            <h:selectOneMenu id="contact" value="#{offerBean.contact}" required="true" styleClass="requiredFieldClass">
                <f:selectItems value="#{offerBean.contactsBySelectedOrganization}"/>
                <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
        </h:panelGroup>

    </td>
</tr>


    <%-- Field: orderNumber --%>
<tr>
    <td class="editLabelRW">${msg['bill.orderNumber']}:</td>

    <td class="editFieldCell">

        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="orderNumber"/>
            <h:inputText id="orderNumber" value="#{offerBean.orderNumber}" maxlength="64"/>
        </h:panelGroup>

    </td>
</tr>

    <%-- Field: lineaTrabajo --%>
<tr>
    <td class="editLabelRW">*${msg['offer.lineaTrabajo']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="lineaTrabajo"/>
            <h:selectOneMenu id="lineaTrabajo" value="#{offerBean.offer.lineaTrabajo}" required="true"
                             styleClass="requiredFieldClass">
                <f:selectItems value="#{offerBean.lineaTrabajos}"/>
                <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
        </h:panelGroup>
    </td>
</tr>


    <%-- Field: title --%>
<tr>
    <td class="editLabelRW">*${msg['offer.title']}:</td>

    <td class="editFieldCell">

        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="title"/>
            <h:inputText id="title" value="#{offerBean.title}" maxlength="128" required="true"
                         styleClass="requiredFieldClass"/>
        </h:panelGroup>

    </td>
</tr>


    <%-- Field: description --%>
<tr>
    <td class="editLabelRW">${msg['offer.description']}:</td>

    <td class="editFieldCell">

        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="description"/>
            <h:inputTextarea id="description" value="#{offerBean.description}" rows="5" cols="68"/>
        </h:panelGroup>

    </td>
</tr>


    <%-- Field: creationDate --%>
<tr>
    <td class="editLabelRW">${msg['offer.creationDate']}:</td>

    <td class="editFieldCell">

        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="creationDate"/>
            <t:inputCalendar id="creationDate" value="#{offerBean.creationDate}" disabled="true"
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true"
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                    />
        </h:panelGroup>

    </td>
</tr>


    <%-- Field: validityDate --%>
<tr>
    <td class="editLabelRW">*${msg['offer.validityDate']}:</td>

    <td class="editFieldCell">

        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="validityDate"/>
            <t:inputCalendar id="validityDate" value="#{offerBean.validityDateDefault}" styleClass="requiredFieldClass"
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true"
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                    />
        </h:panelGroup>

    </td>
</tr>

    <%-- Field: maturityDate --%>
<tr>
    <td class="editLabelRW">${msg['offer.maturityDate']}:</td>

    <td class="editFieldCell">

        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="maturityDate"/>
            <t:inputCalendar id="maturityDate" value="#{offerBean.maturityDate}"
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true"
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                    />
        </h:panelGroup>

    </td>
</tr>


    <%-- Field: offerState --%>
<tr>
    <td class="editLabelRW">*${msg['offer.offerState']}:</td>

    <td class="editFieldCell">

        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="offerState"/>
            <h:selectOneMenu id="offerState" value="#{offerBean.offerState}" required="true"
                             styleClass="requiredFieldClass">
                <f:converter converterId="autentia.EnumConverter"/>
                <f:selectItems value="#{offerBean.offerStates}"/>
            </h:selectOneMenu>
        </h:panelGroup>

    </td>
</tr>

    <%-- Field: offerPotential --%>
<tr>
    <td class="editLabelRW">*${msg['offer.offerPotential']}:</td>

    <td class="editFieldCell">

        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="offerPotential"/>
            <h:selectOneMenu id="offerPotential" value="#{offerBean.offerPotential}" required="true"
                             styleClass="requiredFieldClass">
                <f:converter converterId="autentia.EnumConverter"/>
                <f:selectItems value="#{offerBean.offerPotentials}"/>
            </h:selectOneMenu>
        </h:panelGroup>

    </td>
</tr>
    <%-- Ignored field: ownerId --%>


    <%-- Ignored field: departmentId --%>


    <%-- Ignored field: insertDate --%>


    <%-- Ignored field: updateDate --%>


    <%-- Field: user --%>
<tr>
    <td class="editLabelRW">${msg['offer.user']}:</td>

    <td class="editFieldCell">

        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="user"/>
            <h:selectOneMenu id="user" value="#{offerBean.user}" disabled="true">
                <f:selectItems value="#{offerBean.users}"/>
                <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
        </h:panelGroup>

    </td>
</tr>


    <%-- Field: offerRejectReason --%>
<tr>
    <td class="editLabelRW">${msg['offer.offerRejectReason']}:</td>

    <td class="editFieldCell">

        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="offerRejectReason"/>
            <h:selectOneMenu id="offerRejectReason" value="#{offerBean.offerRejectReason}">
                <f:selectItems value="#{offerBean.offerRejectReasons}"/>
                <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
        </h:panelGroup>

    </td>
</tr>
    <%-- Field: interactions --%>

<c:if test="${offerBean.interactionsAvailable}">
    <tr>
        <td class="editLabelRW">${msg['offer.interactions']}:</td>

        <td class="editFieldCell">

            <%@include file="inlineDetailInteraction.jsp" %>

        </td>
    </tr>
</c:if>

    <%-- Field: roles --%>
<tr>
    <td class="editLabelRW">${msg['offer.roles']}:</td>

    <td class="editFieldCell">

        <%@include file="inlineEditOfferRole.jsp" %>

    </td>
</tr>

    <%-- Field: totalRoles --%>
<tr>
    <td class="editLabelRW">${msg['offer.totalRoles']}:</td>

    <td class="editFieldCell">

        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="totalRoles"/>
            <h:inputText id="totalRoles" value="#{offerBean.totalRoles}" size="10" disabled="true"/>
        </h:panelGroup>

    </td>
</tr>
    <%-- Field: ensayos --%>
<tr>
    <td class="editLabelRW">${msg['offer.ensayos']}:</td>

    <td class="editFieldCell">

        <%@include file="inlineEditOfferEnsayo.jsp" %>

    </td>
</tr>

    <%-- Field: totalEnsayos --%>
<tr>
    <td class="editLabelRW">${msg['offer.totalEnsayos']}:</td>

    <td class="editFieldCell">

        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="totalEnsayos"/>
            <h:inputText id="totalEnsayos" value="#{offerBean.totalEnsayos}" size="10" disabled="true"/>
        </h:panelGroup>

    </td>
</tr>
    <%-- Field: pautas --%>
<tr>
    <td class="editLabelRW">${msg['offer.pautas']}:</td>

    <td class="editFieldCell">

        <%@include file="inlineEditOfferPauta.jsp" %>

    </td>
</tr>

    <%-- Field: totalPautas --%>
<tr>
    <td class="editLabelRW">${msg['offer.totalPautas']}:</td>

    <td class="editFieldCell">

        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="totalPautas"/>
            <h:inputText id="totalPautas" value="#{offerBean.totalPautas}" size="10" disabled="true"/>
        </h:panelGroup>

    </td>
</tr>
    <%-- Field: costs --%>
<tr>
    <td class="editLabelRW">${msg['offer.costs']}:</td>

    <td class="editFieldCell">

        <%@include file="inlineEditOfferCost.jsp" %>

    </td>
</tr>


    <%-- Field: totalCosts --%>
<tr>
    <td class="editLabelRW">${msg['offer.totalCosts']}:</td>

    <td class="editFieldCell">

        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="totalCosts"/>
            <h:inputText id="totalCosts" value="#{offerBean.totalCosts}" size="10" disabled="true"/>
        </h:panelGroup>

    </td>
</tr>


    <%-- Field: total --%>
<tr>
    <td class="editLabelRW">${msg['offer.total']}:</td>

    <td class="editFieldCell">

        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="total"/>
            <h:inputText id="total" value="#{offerBean.total}" size="10" disabled="true"/>
        </h:panelGroup>

    </td>
</tr>


    <%-- Field: iva --%>
<tr>
    <td class="editLabelRW">*${msg['offer.iva']}:</td>

    <td class="editFieldCell">

        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="iva"/>
            <h:inputText id="iva" value="#{offerBean.iva}" size="10"/>
        </h:panelGroup>

    </td>
</tr>


    <%-- Field: observations --%>
<tr>
    <td class="editLabelRW">${msg['offer.observations']}:</td>

    <td class="editFieldCell">

        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="observations"/>
            <h:inputTextarea id="observations" value="#{offerBean.observations}" rows="5" cols="68"/>
        </h:panelGroup>

    </td>
</tr>


    <%-- Offer - generated by stajanov (do not edit/delete) --%>
</table>

<h:commandLink action="#{historicoBean.ver_historico}" immediate="true" target="_blank"
               rendered="#{offerBean.id != null}">
    <f:param name="idObjeto" value="#{offerBean.id}"/>
    <f:param name="klazz" value="#{offerBean.offer.class.name}"/>
    <h:graphicImage value="/img/historico.png" styleClass="titleImg"/>
</h:commandLink>

</h:form>
</f:view>

</body>
</html>  	
