<%-- 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 *
 --%>
<%@page language="java" contentType="text/html; charset=UTF-8" %>

<%@include file="/inc/tlibs.jsp" %>

<html>
<head>
    <%@include file="/inc/uiCore.jsp" %>
</head>
<body>

<!-- editOrganization.jsp: generated by stajanov code generator -->
<f:loadBundle basename="com.autentia.intra.resources.messages" var="msg"/>
<i:location place="editarPrecios" msg="${msg}"/>

<f:view>
    <%@include file="/inc/header.jsp" %>
    <h:form id="precios" enctype="multipart/form-data">

        <%-- Header --%>
        <i:titleBar name="${organizationBean.name}" msg="${msg}">
            <h:commandLink action="#{organizationBean.savePrecios}"
                           onclick="if(!askSave('#{organizationBean.id}','#{msg['question.confirmSave']}')) return false;">
                <h:graphicImage value="/img/save.gif" styleClass="titleImg"/>
            </h:commandLink>
            <h:commandLink action="#{organizationBean.list}" immediate="true">
                <h:graphicImage value="/img/back.gif" styleClass="titleImg"/>
            </h:commandLink>
        </i:titleBar>

        <%-- Edition form --%>
        <table class="editTable" cellpadding="0" cellspacing="0">

            <c:if test="${organizationBean.esCliente}">
                <%-- Field: ensayos --%>
                <tr>
                    <td class="editLabelRW">Ensayos:</td>
                    <td class="editFieldCell">
                        <t:dataTable id="ensayoPrecios" var="item" value="#{organizationBean.ensayoPrecios}"
                                     preserveDataModel="false"
                                     cellpadding="0" cellspacing="0" styleClass="editListTable"
                                     headerClass="editListHeaderCell" footerClass="editListFooter"
                                     rows="#{settingBean.mySettings.listSize}" rowClasses="editListRowO,editListRowE"
                                     columnClasses="editListEditarPreciosEnsayo,editListEditarPreciosCost">


                            <%-- Commands --%>
                            <h:column>
                                <f:facet name="header">
                                    <t:commandLink action="#{organizationBean.createEnsayoPrecios}">
                                        <h:graphicImage title="#{msg.entityActions_new}" value="/img/new.gif"
                                                        styleClass="cmdImg"/>
                                    </t:commandLink>
                                </f:facet>
                                <t:commandLink action="#{organizationBean.deleteEnsayoPrecios}"
                                               onclick="if( !confirm('#{msg['question.confirmDelete']}') ) return false;">
                                    <h:graphicImage title="#{msg.entityActions_delete}" value="/img/delete.gif"
                                                    styleClass="cmdImg"/>
                                </t:commandLink>
                            </h:column>


                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="*#{msg['ensayo.name']}" styleClass="editListHeader"/>
                                </f:facet>
                                <h:panelGroup>
                                    <h:message styleClass="error" showSummary="true" showDetail="false" for="ensayo"/>
                                    <h:selectOneMenu id="ensayo" value="#{item.ensayo}" required="true"
                                                     styleClass="requiredFieldClass" onchange="submit()">
                                        <f:selectItems value="#{organizationBean.misEnsayos}"/>
                                        <f:converter converterId="autentia.EntityConverter"/>
                                    </h:selectOneMenu>
                                </h:panelGroup>
                            </h:column>


                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="*#{msg['ensayo.cost']}" styleClass="editListHeader"/>
                                </f:facet>
                                <h:panelGroup>
                                    <h:message styleClass="error" showSummary="true" showDetail="false" for="cost"/>
                                    <h:inputText id="cost" value="#{item.cost}" size="10"/>
                                    <h:outputText value="(#{item.ensayo.cost})"/>
                                </h:panelGroup>
                            </h:column>


                        </t:dataTable>
                    </td>
                </tr>

                <tr>
                    <td class="editLabelRW">Pautas:</td>
                    <td class="editFieldCell">

                        <t:dataTable id="pautaPrecios" var="item" value="#{organizationBean.pautaPrecios}"
                                     preserveDataModel="false"
                                     cellpadding="0" cellspacing="0" styleClass="editListTable"
                                     headerClass="editListHeaderCell" footerClass="editListFooter"
                                     rows="#{settingBean.mySettings.listSize}" rowClasses="editListRowO,editListRowE"
                                     columnClasses="editListEditarPreciosPautas,editListEditarPreciosCost">


                            <%-- Commands --%>
                            <h:column>
                                <f:facet name="header">
                                    <t:commandLink action="#{organizationBean.createPautaPrecios}">
                                        <h:graphicImage title="#{msg.entityActions_new}" value="/img/new.gif"
                                                        styleClass="cmdImg"/>
                                    </t:commandLink>
                                </f:facet>
                                <t:commandLink action="#{organizationBean.deletePautaPrecios}"
                                               onclick="if( !confirm('#{msg['question.confirmDelete']}') ) return false;">
                                    <h:graphicImage title="#{msg.entityActions_delete}" value="/img/delete.gif"
                                                    styleClass="cmdImg"/>
                                </t:commandLink>
                            </h:column>


                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="*#{msg['pauta.name']}" styleClass="editListHeader"/>
                                </f:facet>
                                <h:panelGroup>
                                    <h:message styleClass="error" showSummary="true" showDetail="false" for="pauta"/>
                                    <h:selectOneMenu id="pauta" value="#{item.pauta}" required="true"
                                                     styleClass="requiredFieldClass" onchange="submit()">
                                        <f:selectItems value="#{organizationBean.misPautas}"/>
                                        <f:converter converterId="autentia.EntityConverter"/>
                                    </h:selectOneMenu>
                                </h:panelGroup>
                            </h:column>

                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="*#{msg['pauta.cost']}" styleClass="editListHeader"/>
                                </f:facet>
                                <h:panelGroup>
                                    <h:message styleClass="error" showSummary="true" showDetail="false" for="cost"/>
                                    <h:inputText id="cost" value="#{item.cost}" size="10"/>
                                    <h:outputText value="(#{item.pauta.cost})"/>
                                </h:panelGroup>
                            </h:column>


                        </t:dataTable>
                    </td>
                </tr>
            </c:if>


            <c:if test="${organizationBean.esProveedor}">
                <t:dataTable id="productoPrecios" var="item" value="#{organizationBean.productoPrecios}"
                             preserveDataModel="false"
                             cellpadding="0" cellspacing="0" styleClass="editListTable"
                             headerClass="editListHeaderCell" footerClass="editListFooter"
                             rows="#{settingBean.mySettings.listSize}" rowClasses="editListRowO,editListRowE"
                             columnClasses="editListEditarPreciosProductos,editListEditarPreciosCost">


                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="*#{msg['productoPrecio.producto']}" styleClass="editListHeader"/>
                        </f:facet>
                        <h:panelGroup>
                            <h:message styleClass="error" showSummary="true" showDetail="false" for="producto"/>
                            <h:inputText id="producto" value="#{item.producto}" size="70" maxlength="255"/>
                        </h:panelGroup>
                    </h:column>


                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="*#{msg['productoPrecio.cost']}" styleClass="editListHeader"/>
                        </f:facet>
                        <h:panelGroup>
                            <h:message styleClass="error" showSummary="true" showDetail="false" for="cost"/>
                            <h:inputText id="cost" value="#{item.cost}" size="10"/>
                        </h:panelGroup>
                    </h:column>


                </t:dataTable>
                <%-- Paginator control --%>
                <t:dataScroller for="productoPrecios" fastStep="10" paginator="true"
                                paginatorMaxPages="10" renderFacetsIfSinglePage="false"
                                styleClass="scroller" paginatorTableClass="paginator"
                                paginatorColumnClass="paginatorCell"
                                paginatorActiveColumnClass="paginatorActiveCell">
                    <f:facet name="first">
                        <t:graphicImage value="/img/arrow-first.gif" border="0"/>
                    </f:facet>
                    <f:facet name="last">
                        <t:graphicImage value="/img/arrow-last.gif" border="0"/>
                    </f:facet>
                    <f:facet name="previous">
                        <t:graphicImage value="/img/arrow-previous.gif" border="0"/>
                    </f:facet>
                    <f:facet name="next">
                        <t:graphicImage value="/img/arrow-next.gif" border="0"/>
                    </f:facet>
                    <f:facet name="fastrewind">
                        <t:graphicImage value="/img/arrow-fr.gif" border="0"/>
                    </f:facet>
                    <f:facet name="fastforward">
                        <t:graphicImage value="/img/arrow-ff.gif" border="0"/>
                    </f:facet>
                </t:dataScroller>
            </c:if>

        </table>

    </h:form>
</f:view>

</body>
</html>

<%-- organization - generated by stajanov (do not edit/delete) --%>






