<%-- 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 *
 --%>
<%@page language="java" contentType="text/html; charset=UTF-8" %>

<%@include file="/inc/tlibs.jsp" %>

<html>
<head>
    <%@include file="/inc/uiCore.jsp" %>
</head>
<body>

<!-- editContact.jsp: generated by stajanov code generator -->
<f:loadBundle basename="com.autentia.intra.resources.messages" var="msg"/>
<i:location place="editContact" msg="${msg}"/>

<f:view>
    <%@include file="/inc/header.jsp" %>
    <h:form id="contact" enctype="multipart/form-data">

        <%-- Header --%>
        <i:titleBar name="${contactBean.name}" msg="${msg}">
            <h:commandLink action="#{contactBean.save}">
                <h:graphicImage value="/img/save.gif" styleClass="titleImg"/>
            </h:commandLink>
            <h:commandLink action="#{contactBean.delete}"
                           onclick="if( !confirm('#{msg['question.confirmDelete']}') ) return false;">
                <h:graphicImage value="/img/delete.gif" styleClass="titleImg"/>
            </h:commandLink>
            <h:commandLink action="#{contactBean.list}" immediate="true">
                <h:graphicImage value="/img/back.gif" styleClass="titleImg"/>
            </h:commandLink>
        </i:titleBar>

        <%-- Edition form --%>
        <table class="editTable" cellpadding="0" cellspacing="0">

                <%-- contact - generated by stajanov (do not edit/delete) --%>


                <%-- Ignored field: id --%>


                <%-- Field: name --%>
            <tr>
                <td class="editLabelRW">*${msg['contact.name']}:</td>

                <td class="editFieldCell">

                    <h:panelGroup>
                        <h:message styleClass="error" showSummary="true" showDetail="false" for="name"/>
                        <h:inputText id="name" value="#{contactBean.name}" size="70" maxlength="150" required="true"
                                     styleClass="requiredFieldClass"/>
                    </h:panelGroup>

                </td>
            </tr>


                <%-- Field: email --%>
            <tr>
                <td class="editLabelRW">${msg['contact.email']}:</td>

                <td class="editFieldCell">

                    <h:panelGroup>
                        <h:message styleClass="error" showSummary="true" showDetail="false" for="email"/>
                        <h:inputText id="email" value="#{contactBean.email}" size="70" maxlength="128"/>
                    </h:panelGroup>

                </td>
            </tr>


                <%-- Field: phone --%>
            <tr>
                <td class="editLabelRW">${msg['contact.phone']}:</td>

                <td class="editFieldCell">

                    <h:panelGroup>
                        <h:message styleClass="error" showSummary="true" showDetail="false" for="phone"/>
                        <h:inputText id="phone" value="#{contactBean.phone}" maxlength="15"/>
                    </h:panelGroup>

                </td>
            </tr>


                <%-- Field: mobile --%>
            <tr>
                <td class="editLabelRW">${msg['contact.mobile']}:</td>

                <td class="editFieldCell">

                    <h:panelGroup>
                        <h:message styleClass="error" showSummary="true" showDetail="false" for="mobile"/>
                        <h:inputText id="mobile" value="#{contactBean.mobile}" maxlength="15"/>
                    </h:panelGroup>

                </td>
            </tr>


                <%-- Ignored field: notified --%>


                <%-- Field: position --%>
            <tr>
                <td class="editLabelRW">${msg['contact.position']}:</td>

                <td class="editFieldCell">

                    <h:panelGroup>
                        <h:message styleClass="error" showSummary="true" showDetail="false" for="position"/>
                        <h:inputText id="position" value="#{contactBean.position}" size="70" maxlength="128"/>
                    </h:panelGroup>

                </td>
            </tr>


                <%-- Ignored field: ownerId --%>


                <%-- Ignored field: departmentId --%>


                <%-- Ignored field: insertDate --%>


                <%-- Ignored field: updateDate --%>


                <%-- Field: organization --%>
            <tr>
                <td class="editLabelRW">*${msg['contact.organization']}:</td>

                <td class="editFieldCell">

                    <h:panelGroup>
                        <h:message styleClass="error" showSummary="true" showDetail="false" for="organization"/>
                        <h:selectOneMenu id="organization" value="#{contactBean.organization}" required="true"
                                         styleClass="requiredFieldClass">
                            <f:selectItems value="#{contactBean.organizations}"/>
                            <f:converter converterId="autentia.EntityConverter"/>
                        </h:selectOneMenu>
                    </h:panelGroup>

                </td>
            </tr>


                <%-- contact - generated by stajanov (do not edit/delete) --%>

                <%-- Field: notified --%>
            <tr>
                <td class="editLabelRW">*${msg['contact.notified']}:</td>
                <td class="editFieldCell">

                    <h:panelGroup>
                        <h:message styleClass="error" showSummary="true" showDetail="false" for="notified"/>
                        <h:panelGroup rendered="#{! contactBean.notified}">
                            <h:commandLink action="#{contactBean.sendMail}" styleClass="warning"
                                           title="#{msg['editContact.notifiedTooltip']}">
                                <h:graphicImage value="/img/envelope.png" styleClass="titleImg"/>
                                <f:verbatim>&nbsp;</f:verbatim><
                                <h:outputText value="#{msg['editContact.notifiedWarning']}"/>
                            </h:commandLink>
                        </h:panelGroup>
                        <h:selectBooleanCheckbox id="notified" value="#{contactBean.notified}" required="true"
                                                 styleClass="requiredFieldClass"/>
                    </h:panelGroup>

                </td>
            </tr>

        </table>

        <h:commandLink action="#{historicoBean.ver_historico}" immediate="true" target="_blank"
                       rendered="#{contactBean.id != null}">
            <f:param name="idObjeto" value="#{contactBean.id}"/>
            <f:param name="klazz" value="#{contactBean.contact.class.name}"/>
            <h:graphicImage value="/img/historico.png" styleClass="titleImg"/>
        </h:commandLink>

    </h:form>
</f:view>

</body>
</html>  		
