<%-- 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 *
 --%>


<%@page language="java" contentType="text/html; charset=UTF-8" %>

<%@include file="/inc/tlibs.jsp" %>

<html>
<head>
    <%@include file="/inc/uiCore.jsp" %>
</head>
<body>

<!-- editInteraction.jsp: generated by stajanov code generator -->
<f:loadBundle basename="com.autentia.intra.resources.messages" var="msg"/>
<i:location place="editInteraction" msg="${msg}"/>

<f:view>
    <%@include file="/inc/header.jsp" %>
    <h:form id="interaction" enctype="multipart/form-data">

        <%-- Header --%>
        <i:titleBar name="${interactionBean.why}" msg="${msg}">
            <h:commandLink action="#{interactionBean.saveFromOffer}"
                           onclick="if(!askSave('#{interactionBean.id}','#{msg['question.confirmSave']}')) return false;">
                <h:graphicImage title="#{msg.entityActions_save}" value="/img/save.gif" styleClass="titleImg"/>
            </h:commandLink>
            <h:commandLink action="#{interactionBean.listFromOffer}" immediate="true">
                <h:graphicImage title="#{msg.entityActions_back}" value="/img/back.gif" styleClass="titleImg"/>
            </h:commandLink>
        </i:titleBar>

        <%-- Edition form --%>
        <table class="editTable" cellpadding="0" cellspacing="0">

                <%-- Ignored field: id --%>

                <%-- Field: organization --%>

            <tr>
                <td class="editLabelRW">${msg['interaction.organization']}:</td>
                <td class="editFieldCell">
                    <h:panelGroup>
                        <h:message styleClass="error" showSummary="true" showDetail="false" for="organization"/>
                        <h:selectOneMenu id="organization" value="#{interactionBean.selectedOrganization}"
                                         immediate="true"
                                         onchange="submit()"
                                         valueChangeListener="#{interactionBean.onSelectedOrganizationChanged}">
                            <f:selectItems value="#{interactionBean.organizations}"/>
                            <f:converter converterId="autentia.EntityConverter"/>
                        </h:selectOneMenu>
                    </h:panelGroup>
                </td>
            </tr>

                <%-- Field: project --%>
            <tr>
                <td class="editLabelRW">${msg['interaction.project']}:</td>
                <td class="editFieldCell">
                    <h:panelGroup>
                        <h:message styleClass="error" showSummary="true" showDetail="false" for="project"/>
                        <h:selectOneMenu id="project" value="#{interactionBean.project}">
                            <f:selectItems value="#{interactionBean.projectsBySelectedOrganization}"/>
                            <f:converter converterId="autentia.EntityConverter"/>
                        </h:selectOneMenu>
                    </h:panelGroup>
                </td>
            </tr>

                <%-- Field: offer --%>
            <tr>
                <td class="editLabelRW">${msg['interaction.offer']}:</td>
                <td class="editFieldCell">
                    <h:panelGroup>
                        <h:message styleClass="error" showSummary="true" showDetail="false" for="offer"/>
                        <h:selectOneMenu id="organization" value="#{interactionBean.offer}" disabled="true">
                            <f:selectItems value="#{interactionBean.offers}"/>
                            <f:converter converterId="autentia.EntityConverter"/>
                        </h:selectOneMenu>
                    </h:panelGroup>
                </td>
            </tr>

                <%-- Field: type --%>
            <tr>
                <td class="editLabelRW">*${msg['interaction.type']}:</td>
                <td class="editFieldCell">
                    <h:panelGroup>
                        <h:message styleClass="error" showSummary="true" showDetail="false" for="type"/>
                        <h:selectOneMenu id="type" value="#{interactionBean.type}" required="true"
                                         styleClass="requiredFieldClass">
                            <f:selectItems value="#{interactionBean.types}"/>
                            <f:converter converterId="autentia.EntityConverter"/>
                        </h:selectOneMenu>
                    </h:panelGroup>
                </td>
            </tr>

                <%-- Field: creationDate --%>
            <tr>
                <td class="editLabelRW">*${msg['interaction.creationDate']}:</td>
                <td class="editFieldCell">
                    <h:panelGroup>
                        <h:message styleClass="error" showSummary="true" showDetail="false" for="creationDate"/>
                        <t:inputCalendar id="creationDate" value="#{interactionBean.creationDate}"
                                         required="true" styleClass="requiredFieldClass"
                                         renderAsPopup="true" popupDateFormat="d/MM/yyyy"
                                         renderPopupButtonAsImage="true"
                                         popupTodayString="#{msg['calendar.today']}"
                                         popupWeekString="#{msg['calendar.week']}"/>
                    </h:panelGroup>
                </td>
            </tr>

                <%-- Field: interest --%>
            <tr>
                <td class="editLabelRW">*${msg['interaction.interest']}:</td>
                <td class="editFieldCell">
                    <h:panelGroup>
                        <h:message styleClass="error" showSummary="true" showDetail="false" for="interest"/>
                        <h:selectOneMenu id="interest" value="#{interactionBean.interest}" required="true"
                                         styleClass="requiredFieldClass">
                            <f:converter converterId="autentia.EnumConverter"/>
                            <f:selectItems value="#{interactionBean.interests}"/>
                        </h:selectOneMenu>
                    </h:panelGroup>
                </td>
            </tr>

                <%-- Field: medio --%>
            <tr>
                <td class="editLabelRW">*${msg['interaction.medio']}:</td>
                <td class="editFieldCell">
                    <h:panelGroup>
                        <h:message styleClass="error" showSummary="true" showDetail="false" for="medio"/>
                        <h:selectOneMenu id="medio" value="#{interactionBean.medio}" required="true"
                                         styleClass="requiredFieldClass">
                            <f:converter converterId="autentia.EnumConverter"/>
                            <f:selectItems value="#{interactionBean.medios}"/>
                        </h:selectOneMenu>
                    </h:panelGroup>
                </td>
            </tr>

                <%-- Field: why --%>
            <tr>
                <td class="editLabelRW">*${msg['interaction.why']}:</td>
                <td class="editFieldCell">
                    <h:panelGroup>
                        <h:message styleClass="error" showSummary="true" showDetail="false" for="why"/>
                        <h:inputTextarea id="why" value="#{interactionBean.why}" rows="5" cols="68" required="true"
                                         styleClass="requiredFieldClass"/>
                    </h:panelGroup>
                </td>
            </tr>

                <%-- Field: description --%>
            <tr>
                <td class="editLabelRW">*${msg['interaction.description']}:</td>
                <td class="editFieldCell">
                    <h:panelGroup>
                        <h:message styleClass="error" showSummary="true" showDetail="false" for="description"/>
                        <h:inputTextarea id="description" value="#{interactionBean.description}" rows="5" cols="68"
                                         required="true"
                                         styleClass="requiredFieldClass"/>
                    </h:panelGroup>
                </td>
            </tr>

                <%-- Field: file --%>
            <tr>
                <td class="editLabelRW">${msg['interaction.file']}:</td>
                <td class="editFieldCell">
                    <h:commandLink action="#{interactionBean.deleteFile}" immediate="true"
                                   rendered="#{interactionBean.file != null}">
                        <h:graphicImage title="#{msg.entityActions_delete}" value="/img/delete.gif"
                                        styleClass="titleImg"/>
                    </h:commandLink>
                    <i:fileLink type="interaction" objectId="${interactionBean.id}" file="${interactionBean.file}"
                                mime="${interactionBean.fileMime}"/>
                    <h:panelGroup>
                        <h:message styleClass="error" showSummary="true" showDetail="false" for="file"/>
                        <t:inputFileUpload id="file" size="58" maxlength="400" value="#{interactionBean.uploadFile}"
                                           storage="file"/>
                    </h:panelGroup>
                </td>
            </tr>

                <%-- Ignored field: fileMime --%>

                <%-- Field: observations --%>
            <tr>
                <td class="editLabelRW">${msg['interaction.observations']}:</td>
                <td class="editFieldCell">
                    <h:panelGroup>
                        <h:message styleClass="error" showSummary="true" showDetail="false" for="observations"/>
                        <h:inputTextarea id="observations" value="#{interactionBean.observations}" rows="5" cols="68"/>
                    </h:panelGroup>
                </td>
            </tr>


                <%-- Ignored field: user --%>

        </table>

    </h:form>
</f:view>

</body>
</html>  		

