<%-- 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 *
 --%>


<%@page language="java" contentType="text/html; charset=UTF-8" %>

<%@include file="/inc/tlibs.jsp" %>

<html>
<head>
    <%@include file="/inc/uiCore.jsp" %>
</head>
<body>

<!-- editPauta.jsp: generated by stajanov code generator -->
<f:loadBundle basename="com.autentia.intra.resources.messages" var="msg"/>
<i:location place="editPauta" msg="${msg}"/>

<f:view>
<%@include file="/inc/header.jsp" %>
<h:form id="pauta" enctype="multipart/form-data">

<%-- Header --%>
<i:titleBar name="${pautaBean.name}" msg="${msg}">
    <h:commandLink action="#{pautaBean.save}"
                   onclick="if(!askSave('#{pautaBean.id}','#{msg['question.confirmSave']}')) return false;">
        <h:graphicImage title="#{msg.entityActions_save}" value="/img/save.gif" styleClass="titleImg"/>
    </h:commandLink>
    <h:commandLink rendered="#{pautaBean.id!=null}" action="#{pautaBean.delete}"
                   onclick="if( !confirm('#{msg['question.confirmDelete']}') ) return false;">
        <h:graphicImage title="#{msg.entityActions_delete}" value="/img/delete.gif" styleClass="titleImg"/>
    </h:commandLink>
    <h:commandLink action="#{pautaBean.list}" immediate="true">
        <h:graphicImage title="#{msg.entityActions_back}" value="/img/back.gif" styleClass="titleImg"/>
    </h:commandLink>
</i:titleBar>

<%-- Edition form --%>
<table class="editTable" cellpadding="0" cellspacing="0">

        <%-- Pauta - generated by stajanov (do not edit/delete) --%>


        <%-- Ignored field: id --%>


        <%-- Field: name --%>
    <tr>
        <td class="editLabelRW">*${msg['pauta.name']}:</td>

        <td class="editFieldCell">

            <h:panelGroup>
                <h:message styleClass="error" showSummary="true" showDetail="false" for="name"/>
                <h:inputText id="name" value="#{pautaBean.name}" size="70" maxlength="255" required="true"
                             styleClass="requiredFieldClass"/>
            </h:panelGroup>

        </td>
    </tr>

    <tr>
        <td class="editLabelRW">${msg['pauta.titulo']}:</td>
        <td class="editFieldCell">
            <h:panelGroup>
                <h:message styleClass="error" showSummary="true" showDetail="false" for="titulo"/>
                <h:inputText id="titulo" value="#{pautaBean.pauta.titulo}" size="70" maxlength="255"/>
            </h:panelGroup>
        </td>
    </tr>


    <tr>
        <td class="editLabelRW">${msg['pauta.referenciaCliente']}:</td>
        <td class="editFieldCell">
            <h:panelGroup>
                <h:message styleClass="error" showSummary="true" showDetail="false" for="referenciaCliente"/>
                <h:inputText id="referenciaCliente" value="#{pautaBean.pauta.referenciaCliente}" maxlength="64"
                             size="64"/>
            </h:panelGroup>
        </td>
    </tr>


    <tr>
        <td class="editLabelRW">${msg['pauta.referenciasCliente']}:</td>
        <td class="editFieldCell">
            <%@include file="inlineEditPautaIdentificacion.jsp" %>
        </td>
    </tr>

        <%-- Field: description --%>
    <tr>
        <td class="editLabelRW">${msg['pauta.description']}:</td>
        <td class="editFieldCell">
            <h:panelGroup>
                <h:message styleClass="error" showSummary="true" showDetail="false" for="description"/>
                <h:inputTextarea id="description" value="#{pautaBean.description}" rows="5" cols="68"/>
            </h:panelGroup>
        </td>
    </tr>


        <%-- Field: cost --%>
    <tr>
        <td class="editLabelRW">${msg['pauta.cost']}:</td>

        <td class="editFieldCell">

            <h:panelGroup>
                <h:message styleClass="error" showSummary="true" showDetail="false" for="cost"/>
                <h:inputText id="cost" value="#{pautaBean.cost}" size="10"/>
            </h:panelGroup>

        </td>
    </tr>


        <%-- Field: ensayosSolicitados --%>
    <tr>
        <td class="editLabelRW">${msg['pauta.ensayosSolicitados']}:</td>
        <td class="editFieldCell">
            <h:panelGroup>
                <h:message styleClass="error" showSummary="true" showDetail="false" for="ensayosSolicitados"/>
                <h:inputTextarea id="ensayosSolicitados" value="#{pautaBean.pauta.ensayosSolicitados}" rows="5"
                                 cols="68"/>
            </h:panelGroup>
        </td>
    </tr>


        <%-- Ignored field: ownerId --%>


        <%-- Ignored field: departmentId --%>


        <%-- Ignored field: insertDate --%>


        <%-- Ignored field: updateDate --%>

        <%-- Field: ensayos --%>

    <tr>
        <td class="editLabelRW">Ensayos:</td>

        <td class="editFieldCell">

            <%@include file="inlineEditPauta_PautaEnsayo.jsp" %>

        </td>
    </tr>

        <%-- Field: cliente --%>
    <tr>
        <td class="editLabelRW">${msg['pauta.cliente']}:</td>
        <td class="editFieldCell">
            <h:panelGroup>
                <h:message styleClass="error" showSummary="true" showDetail="false" for="cliente"/>
                <h:selectOneMenu id="cliente" value="#{pautaBean.pauta.cliente}">
                    <f:selectItems value="#{pautaBean.clientes}"/>
                    <f:converter converterId="autentia.EntityConverter"/>
                </h:selectOneMenu>
            </h:panelGroup>
        </td>
    </tr>

        <%-- Field: material --%>
    <tr>
        <td class="editLabelRW">${msg['pauta.material']}:</td>
        <td class="editFieldCell">
            <h:panelGroup>
                <h:message styleClass="error" showSummary="true" showDetail="false" for="material"/>
                <h:inputText id="material" value="#{pautaBean.pauta.material}" size="70" maxlength="255"/>
            </h:panelGroup>
        </td>
    </tr>

        <%-- Field: agrupacion --%>
    <tr>
        <td class="editLabelRW">${msg['pauta.agrupacion']}:</td>
        <td class="editFieldCell">
            <h:panelGroup>
                <h:message styleClass="error" showSummary="true" showDetail="false" for="agrupacion"/>
                <h:inputText id="agrupacion" value="#{pautaBean.pauta.agrupacion}" size="70" maxlength="255"/>
            </h:panelGroup>
        </td>
    </tr>


    <tr>
        <td class="editLabelRW">${msg['pauta.familia']}:</td>
        <td class="editFieldCell">
            <h:panelGroup>
                <h:message styleClass="error" showSummary="true" showDetail="false" for="familia"/>
                <h:inputText id="familia" value="#{pautaBean.pauta.familia}" size="70" maxlength="255"/>
            </h:panelGroup>
        </td>
    </tr>


    <tr>
        <td class="editLabelRW">*${msg['pauta.tiempoRespuesta']}:</td>
        <td class="editFieldCell">
            <h:panelGroup>
                <h:message styleClass="error" showSummary="true" showDetail="false" for="tiempoRespuesta"/>
                <h:inputText id="tiempoRespuesta" value="#{pautaBean.pauta.tiempoRespuesta}" maxlength="64"
                             required="true" styleClass="requiredFieldClass"/>
            </h:panelGroup>
            días
        </td>
    </tr>

        <%-- Pauta - generated by stajanov (do not edit/delete) --%>
</table>

<h:commandLink action="#{historicoBean.ver_historico}" immediate="true" target="_blank"
               rendered="#{pautaBean.id != null}">
    <f:param name="idObjeto" value="#{pautaBean.id}"/>
    <f:param name="klazz" value="#{pautaBean.pauta.class.name}"/>
    <h:graphicImage value="/img/historico.png" styleClass="titleImg"/>
</h:commandLink>

</h:form>
</f:view>

</body>
</html>  		

