<%--
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.
 *
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com
 *
 --%>

<%@page language="java" contentType="text/html; charset=UTF-8" %>

<%@include file="/inc/tlibs.jsp" %>

<html>
<head>
    <%@include file="/inc/uiCore.jsp" %>
</head>
<body>

<!-- editProject.jsp: generated by stajanov code generator -->
<f:loadBundle basename="com.autentia.intra.resources.messages" var="msg"/>
<i:location place="editPautaEnsayo" msg="${msg}"/>

<f:view>
    <%@include file="/inc/header.jsp" %>
    <h:form id="pautaEnsayo" enctype="multipart/form-data">

        <%-- Header --%>
        <i:titleBar name="${pautaEnsayoBean.ensayo.name}" msg="${msg}">
            <h:commandLink action="#{pautaEnsayoBean.save}"
                           onclick="if(!askSave('#{pautaEnsayoBean.id}','#{msg['question.confirmSave']}')) return false;">
                <h:graphicImage value="/img/save.gif" styleClass="titleImg"/>
            </h:commandLink>
            <h:commandLink action="#{pautaBean.detail}" immediate="true">
                <f:param name="id" value="#{pautaEnsayoBean.pautaEnsayo.pauta.id}"/>
                <h:graphicImage title="#{msg.entityActions_back}" value="/img/back.gif" styleClass="titleImg"/>
            </h:commandLink>
        </i:titleBar>

        <%-- Edition form --%>
        <table class="editTable" cellpadding="0" cellspacing="0">

                <%-- Ignored field: id --%>


            <tr>
                <td class="editLabelRW">${msg['pautaEnsayo.procedimiento']}:</td>
                <td class="editFieldCell">
                    <h:panelGroup>
                        <h:message styleClass="error" showSummary="true" showDetail="false" for="procedimiento"/>
                        <h:selectOneMenu id="procedimiento" value="#{pautaEnsayoBean.procedimiento}">
                            <f:selectItems value="#{pautaEnsayoBean.pautaEnsayo.procedimientosBySelectedEnsayo}"/>
                        </h:selectOneMenu>
                    </h:panelGroup>
                </td>
            </tr>

                <%-- Field: requerimientos --%>

            <tr>
                <td class="editLabelRW">${msg['pautaEnsayo.dimensiones']}:</td>

                <td class="editFieldCell">

                    <%@include file="inlinePautaEnsayo_PautaEnsayoDimension.jsp" %>

                </td>
            </tr>

                <%-- Field: requerimientos --%>

            <tr>
                <td class="editLabelRW">${msg['pautaEnsayo.requerimientos']}:</td>

                <td class="editFieldCell">

                    <%@include file="inlinePautaEnsayo_ParametroString.jsp" %>

                </td>
            </tr>


        </table>

    </h:form>
</f:view>

</body>
</html>

