<%--
* TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
*	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.
*
* 	This program is free software; you can redistribute it and/or
* 	modify it under the terms of the GNU General Public License
* 	as published by the Free Software Foundation; either version 2
* 	of the License, or (at your option) any later version.
*
* 	This program is distributed in the hope that it will be useful,
* 	but WITHOUT ANY WARRANTY; without even the implied warranty of
* 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* 	GNU General Public License for more details.
*
* 	You should have received a copy of the GNU General Public License
* 	along with this program; if not, write to the Free Software
* 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*
* 	Autentia Real Bussiness Solution S.L.
* 	Tlf: +34 91 675 33 06, +34 655 99 11 72
* 	Fax: +34 91 656 65 04
* 	info@autentia.com
*
--%>
<%@page language="java" contentType="text/html; charset=UTF-8" %>

<%@include file="/inc/tlibs.jsp" %>

<html>
<head>
    <%@include file="/inc/uiCore.jsp" %>
</head>
<body>

<!-- searchAlbaran.jsp: generated by stajanov code generator -->
<f:loadBundle basename="com.autentia.intra.resources.messages" var="msg"/>
<i:location place="searchAlbaran" msg="${msg}"/>

<f:view>
    <%@include file="/inc/header.jsp" %>
    <h:form id="search" enctype="multipart/form-data">

        <%-- Header --%>
        <i:titleBar msg="${msg}">
            <h:commandLink action="#{albaranBean.list}">
                <h:graphicImage title="#{msg.entityActions_run}" value="/img/run.png" styleClass="titleImg"/>
            </h:commandLink>
        </i:titleBar>

        <%-- Search form --%>
        <table class="searchTable" cellpadding="0" cellspacing="0">


                <%-- Ignored field: id --%>


                <%-- Field: name --%>
            <tr>
                <td class="searchLabel">Nombre:</td>
                <td class="searchFieldCell">


                    <h:panelGroup>
                        <h:message styleClass="error" showSummary="true" showDetail="false" for="name"/>
                        <h:selectBooleanCheckbox id="nameValid" value="#{albaranBean.searchNameValid}"
                                                 onclick="setEnabled('search:name',this.checked)"/>
                        <h:inputText id="name" value="#{albaranBean.searchName}" size="70"/>
                    </h:panelGroup>
                    <script>
                        setEnabled('search:name', ${albaranBean.searchNameValid})
                    </script>


                </td>
            </tr>

                <%-- Field: fecha --%>
            <tr>
                <td class="searchLabel">Fecha:</td>
                <td class="searchFieldCell">


                    <h:panelGroup>
                        <h:message styleClass="error" showSummary="true" showDetail="false" for="startFecha"/>
                        <h:selectBooleanCheckbox id="startFechaValid" value="#{albaranBean.searchStartFechaValid}"
                                                 onclick="setEnabled('search:startFecha',this.checked)"/>
                        <t:inputCalendar id="startFecha" value="#{albaranBean.searchStartFecha}"
                                         renderAsPopup="true" popupDateFormat="d/MM/yyyy"
                                         renderPopupButtonAsImage="true"
                                         popupTodayString="#{msg['calendar.today']}"
                                         popupWeekString="#{msg['calendar.week']}"
                                         onchange="setEnabled('search:startFecha',true);setChecked('search:startFechaValid',true);"
                                />
                    </h:panelGroup>
                    -
                    <h:panelGroup>
                        <h:message styleClass="error" showSummary="true" showDetail="false" for="endFecha"/>
                        <h:selectBooleanCheckbox id="endFechaValid" value="#{albaranBean.searchEndFechaValid}"
                                                 onclick="setEnabled('search:endFecha',this.checked)"/>
                        <t:inputCalendar id="endFecha" value="#{albaranBean.searchEndFecha}"
                                         renderAsPopup="true" popupDateFormat="d/MM/yyyy"
                                         renderPopupButtonAsImage="true"
                                         popupTodayString="#{msg['calendar.today']}"
                                         popupWeekString="#{msg['calendar.week']}"
                                         onchange="setEnabled('search:endFecha',true);setChecked('search:endFechaValid',true);"
                                />
                    </h:panelGroup>
                    <script>
                        setEnabled('search:startFecha', ${albaranBean.searchStartFechaValid})
                        setEnabled('search:endFecha', ${albaranBean.searchEndFechaValid})
                    </script>


                </td>
            </tr>


                <%-- Ignored field: description --%>


                <%-- Ignored field: observations --%>


                <%-- Ignored field: ownerId --%>


                <%-- Ignored field: departmentId --%>


                <%-- Ignored field: insertDate --%>


                <%-- Ignored field: updateDate --%>


                <%-- Field: client --%>
            <tr>
                <td class="searchLabel">${msg['albaran.client']}:</td>
                <td class="searchFieldCell">
                    <h:panelGroup>
                        <h:message styleClass="error" showSummary="true" showDetail="false" for="client"/>
                        <h:selectBooleanCheckbox id="clientValid" value="#{albaranBean.searchClientValid}"
                                                 onclick="setEnabled('search:client',this.checked)"/>
                        <h:selectOneMenu id="client" value="#{albaranBean.searchClient}"
                                         onclick="setEnabled('search:client',true)">
                            <f:selectItems value="#{albaranBean.clients}"/>
                            <f:converter converterId="autentia.EntityConverter"/>
                        </h:selectOneMenu>
                    </h:panelGroup>
                    <script>
                        setEnabled('search:client', ${albaranBean.searchClientValid})
                    </script>
                </td>
            </tr>

        </table>

    </h:form>
</f:view>

</body>
</html>  		
