<%--
* TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
*	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.
*
* 	This program is free software; you can redistribute it and/or
* 	modify it under the terms of the GNU General Public License
* 	as published by the Free Software Foundation; either version 2
* 	of the License, or (at your option) any later version.
*
* 	This program is distributed in the hope that it will be useful,
* 	but WITHOUT ANY WARRANTY; without even the implied warranty of
* 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* 	GNU General Public License for more details.
*
* 	You should have received a copy of the GNU General Public License
* 	along with this program; if not, write to the Free Software
* 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*
* 	Autentia Real Bussiness Solution S.L.
* 	Tlf: +34 91 675 33 06, +34 655 99 11 72
* 	Fax: +34 91 656 65 04
* 	info@autentia.com
*
--%>
<%@page language="java" contentType="text/html; charset=UTF-8" %>

<%@include file="/inc/tlibs.jsp" %>

<html>
<head>
    <%@include file="/inc/uiCore.jsp" %>
</head>
<body>

<!-- searchPauta.jsp: generated by stajanov code generator -->
<f:loadBundle basename="com.autentia.intra.resources.messages" var="msg"/>
<i:location place="searchPauta" msg="${msg}"/>

<f:view>
    <%@include file="/inc/header.jsp" %>
    <h:form id="search" enctype="multipart/form-data">

        <%-- Header --%>
        <i:titleBar msg="${msg}">
            <h:commandLink action="#{pautaBean.list}">
                <h:graphicImage title="#{msg.entityActions_run}" value="/img/run.png" styleClass="titleImg"/>
            </h:commandLink>
            <h:commandLink action="#{pautaBean.create}" rendered="#{pautaBean.createAvailable}">
                <h:graphicImage title="#{msg.entityActions_create}" value="/img/new.gif" styleClass="titleImg"/>
            </h:commandLink>
        </i:titleBar>

        <%-- Search form --%>
        <table class="searchTable" cellpadding="0" cellspacing="0">


                <%-- Ignored field: id --%>


                <%-- Field: name --%>
            <tr>
                <td class="searchLabel">${msg['pauta.name']}:</td>
                <td class="searchFieldCell">


                    <h:panelGroup>
                        <h:message styleClass="error" showSummary="true" showDetail="false" for="name"/>
                        <h:selectBooleanCheckbox id="nameValid" value="#{pautaBean.searchNameValid}"
                                                 onclick="setEnabled('search:name',this.checked)"/>
                        <h:inputText id="name" value="#{pautaBean.searchName}" size="70"/>
                    </h:panelGroup>
                    <script>
                        setEnabled('search:name', ${pautaBean.searchNameValid})
                    </script>


                </td>
            </tr>

                <%-- Field: cliente --%>
            <tr>
                <td class="searchLabel">${msg['pauta.cliente']}:</td>
                <td class="searchFieldCell">
                    <h:panelGroup>
                        <h:message styleClass="error" showSummary="true" showDetail="false" for="cliente"/>
                        <h:selectBooleanCheckbox id="clienteValid" value="#{pautaBean.searchClienteValid}"
                                                 onclick="setEnabled('search:cliente',this.checked)"/>
                        <h:selectOneMenu id="cliente" value="#{pautaBean.searchCliente}"
                                         onclick="setEnabled('search:cliente',true)">
                            <f:selectItems value="#{pautaBean.clientes}"/>
                            <f:converter converterId="autentia.EntityConverter"/>
                        </h:selectOneMenu>
                    </h:panelGroup>
                    <script>
                        setEnabled('search:cliente', ${pautaBean.searchClienteValid})
                    </script>
                </td>
            </tr>

                <%-- Field: material --%>
            <tr>
                <td class="searchLabel">${msg['pauta.material']}:</td>
                <td class="searchFieldCell">
                    <h:panelGroup>
                        <h:message styleClass="error" showSummary="true" showDetail="false" for="material"/>
                        <h:selectBooleanCheckbox id="materialValid" value="#{pautaBean.searchMaterialValid}"
                                                 onclick="setEnabled('search:material',this.checked)"/>
                        <h:inputText id="material" value="#{pautaBean.searchMaterial}" size="70"/>
                    </h:panelGroup>
                    <script>
                        setEnabled('search:material', ${pautaBean.searchMaterialValid})
                    </script>
                </td>
            </tr>

                <%-- Field: agrupacion --%>
            <tr>
                <td class="searchLabel">${msg['pauta.agrupacion']}:</td>
                <td class="searchFieldCell">
                    <h:panelGroup>
                        <h:message styleClass="error" showSummary="true" showDetail="false" for="agrupacion"/>
                        <h:selectBooleanCheckbox id="agrupacionValid" value="#{pautaBean.searchAgrupacionValid}"
                                                 onclick="setEnabled('search:agrupacion',this.checked)"/>
                        <h:inputText id="agrupacion" value="#{pautaBean.searchAgrupacion}" size="70"/>
                    </h:panelGroup>
                    <script>
                        setEnabled('search:agrupacion', ${pautaBean.searchAgrupacionValid})
                    </script>
                </td>
            </tr>

                <%-- Ignored field: ownerId --%>


                <%-- Ignored field: departmentId --%>


                <%-- Ignored field: insertDate --%>


                <%-- Ignored field: updateDate --%>


        </table>

    </h:form>
</f:view>

</body>
</html>  		
