/* 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 */


package com.autentia.intra.manager.book;

import com.autentia.intra.businessobject.Book;
import com.autentia.intra.dao.SortCriteria;
import com.autentia.intra.dao.hibernate.BookDAO;
import com.autentia.intra.dao.search.BookSearch;
import com.autentia.intra.util.SpringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.util.List;


public class BookManager {

/* Book - generated by stajanov (do not edit/delete) */


    /**
     * Logger
     */
    private static final Log log = LogFactory.getLog(BookManager.class);

    /**
     * Book DAO *
     */
    private BookDAO bookDAO;

    /**
     * Get default BookManager as defined in Spring's configuration file.
     *
     * @return the default singleton BookManager
     */
    public static BookManager getDefault() {
        return (BookManager) SpringUtils.getSpringBean("managerBook");
    }

    /**
     * Empty constructor needed by CGLIB (Spring AOP)
     */
    protected BookManager() {
    }

    /**
     * Default constructor
     *
     * @deprecated do not construct managers alone: use Spring's declared beans
     */
    public BookManager(BookDAO bookDAO) {
        this.bookDAO = bookDAO;
    }

    /**
     * List books.
     *
     * @param search search filter to apply
     * @param sort   sorting criteria
     * @return the list of all books sorted by requested criterion
     */
    public List<Book> getAllEntities(BookSearch search, SortCriteria sort) {
        return bookDAO.search(search, sort);
    }

    /**
     * Get book by primary key.
     *
     * @return book selected by id.
     */
    public Book getEntityById(int id) {
        return bookDAO.getById(id);
    }

    /**
     * Insert book.
     */
    public void insertEntity(Book book) {
        bookDAO.insert(book);
    }

    /**
     * Update book.
     */
    public void updateEntity(Book book) {
        bookDAO.update(book);
    }

    /**
     * Delete book.
     */
    public void deleteEntity(Book book) {
        bookDAO.delete(book);
    }

/* Book - generated by stajanov (do not edit/delete) */


}
