/* 
 *  TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 */


package com.autentia.intra.dao.search;

import com.autentia.intra.dao.SearchCriteria;

import java.util.ArrayList;
import java.util.Date;

public class ProjectEnsayoRequerimientoSearch extends SearchCriteria {

/* generated by stajanov (do not edit/delete) */


    @Override
    public String getHQL() {
        StringBuilder ret = new StringBuilder();
        int iArgNum = 0;

        if (isNombreSet()) {
            ret.append((ret.length() == 0) ? "WHERE " : " AND ");
            if (getNombre() == null) {
                ret.append("nombre is NULL");
            } else {
                ret.append("nombre like :arg" + (iArgNum++));
            }
        }


        if (isNombreInglesSet()) {
            ret.append((ret.length() == 0) ? "WHERE " : " AND ");
            if (getNombreIngles() == null) {
                ret.append("nombreIngles is NULL");
            } else {
                ret.append("nombreIngles like :arg" + (iArgNum++));
            }
        }


        if (isValorSet()) {
            ret.append((ret.length() == 0) ? "WHERE " : " AND ");
            if (getValor() == null) {
                ret.append("valor is NULL");
            } else {
                ret.append("valor like :arg" + (iArgNum++));
            }
        }


        if (isIncertidumbreSet()) {
            ret.append((ret.length() == 0) ? "WHERE " : " AND ");
            if (getIncertidumbre() == null) {
                ret.append("incertidumbre is NULL");
            } else {
                ret.append("incertidumbre like :arg" + (iArgNum++));
            }
        }


        if (isOwnerIdSet()) {
            ret.append((ret.length() == 0) ? "WHERE " : " AND ");
            if (getOwnerId() == null) {
                ret.append("ownerId is NULL");
            } else {
                ret.append("ownerId = :arg" + (iArgNum++));
            }
        }


        if (isDepartmentIdSet()) {
            ret.append((ret.length() == 0) ? "WHERE " : " AND ");
            if (getDepartmentId() == null) {
                ret.append("departmentId is NULL");
            } else {
                ret.append("departmentId = :arg" + (iArgNum++));
            }
        }


        if (isStartInsertDateSet()) {
            ret.append((ret.length() == 0) ? "WHERE " : " AND ");
            if (startInsertDate == null) {
                ret.append("insertDate=:arg" + (iArgNum++));
            } else {
                ret.append("insertDate>=:arg" + (iArgNum++));
            }
        }
        if (isEndInsertDateSet()) {
            ret.append((ret.length() == 0) ? "WHERE " : " AND ");
            if (endInsertDate == null) {
                ret.append("insertDate=:arg" + (iArgNum++));
            } else {
                ret.append("insertDate<=:arg" + (iArgNum++));
            }
        }


        if (isStartUpdateDateSet()) {
            ret.append((ret.length() == 0) ? "WHERE " : " AND ");
            if (startUpdateDate == null) {
                ret.append("updateDate=:arg" + (iArgNum++));
            } else {
                ret.append("updateDate>=:arg" + (iArgNum++));
            }
        }
        if (isEndUpdateDateSet()) {
            ret.append((ret.length() == 0) ? "WHERE " : " AND ");
            if (endUpdateDate == null) {
                ret.append("updateDate=:arg" + (iArgNum++));
            } else {
                ret.append("updateDate<=:arg" + (iArgNum++));
            }
        }


        customGetHQL(ret, iArgNum);
        return ret.toString();
    }

    @Override
    public Object[] getArguments() {
        ArrayList<Object> ret = new ArrayList<Object>();

        if (isNombreSet() && getNombre() != null) {
            ret.add(nombre);
        }


        if (isNombreInglesSet() && getNombreIngles() != null) {
            ret.add(nombreIngles);
        }


        if (isValorSet() && getValor() != null) {
            ret.add(valor);
        }


        if (isIncertidumbreSet() && getIncertidumbre() != null) {
            ret.add(incertidumbre);
        }


        if (isOwnerIdSet() && getOwnerId() != null) {
            ret.add(ownerId);
        }


        if (isDepartmentIdSet() && getDepartmentId() != null) {
            ret.add(departmentId);
        }


        if (isStartInsertDateSet()) {
            ret.add(startInsertDate);
        }
        if (isEndInsertDateSet()) {
            ret.add(endInsertDate);
        }


        if (isStartUpdateDateSet()) {
            ret.add(startUpdateDate);
        }
        if (isEndUpdateDateSet()) {
            ret.add(endUpdateDate);
        }


        customGetArguments(ret);
        return ret.toArray();
    }

    @Override
    public void reset() {

        unsetNombre();
        unsetNombreIngles();
        unsetValor();
        unsetIncertidumbre();

        unsetOwnerId();


        unsetDepartmentId();


        unsetStartInsertDate();
        unsetEndInsertDate();


        unsetStartUpdateDate();
        unsetEndUpdateDate();


        customReset();
    }

    private void unsetIncertidumbre() {
        this.incertidumbreSet = false;
    }

    private void unsetValor() {
        this.valorSet = false;
    }

    private void unsetNombreIngles() {
        this.nombreInglesSet = false;
    }

    private void unsetNombre() {
        this.nombreSet = false;
    }

    @Override
    public String toString() {
        StringBuilder ret = new StringBuilder();
        ret.append("ParametroStringSearch{");


        if (isNombreSet()) {
            ret.append("(nombre");
            ret.append("=" + nombre);
            ret.append(")");
        }


        if (isNombreInglesSet()) {
            ret.append("(nombreIngles");
            ret.append("=" + nombreIngles);
            ret.append(")");
        }


        if (isValorSet()) {
            ret.append("(valor");
            ret.append("=" + valor);
            ret.append(")");
        }


        if (isIncertidumbreSet()) {
            ret.append("(incertidumbre");
            ret.append("=" + incertidumbre);
            ret.append(")");
        }


        if (isOwnerIdSet()) {
            ret.append("(ownerId");
            ret.append("=" + ownerId);
            ret.append(")");
        }


        if (isDepartmentIdSet()) {
            ret.append("(departmentId");
            ret.append("=" + departmentId);
            ret.append(")");
        }


        if (isStartInsertDateSet()) {
            ret.append("(startInsertDate");
            ret.append("=" + startInsertDate);
            ret.append(")");
        }
        if (isEndInsertDateSet()) {
            ret.append("(endInsertDate");
            ret.append("=" + endInsertDate);
            ret.append(")");
        }


        if (isStartUpdateDateSet()) {
            ret.append("(startUpdateDate");
            ret.append("=" + startUpdateDate);
            ret.append(")");
        }
        if (isEndUpdateDateSet()) {
            ret.append("(endUpdateDate");
            ret.append("=" + endUpdateDate);
            ret.append(")");
        }


        customToString(ret);
        ret.append("}");
        return ret.toString();
    }

    // Getters and setters


    public boolean isOwnerIdSet() {
        return ownerIdSet;
    }

    public Integer getOwnerId() {
        return ownerId;
    }

    public void setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
        this.ownerIdSet = true;
    }

    public void unsetOwnerId() {
        this.ownerIdSet = false;
    }


    public boolean isDepartmentIdSet() {
        return departmentIdSet;
    }

    public Integer getDepartmentId() {
        return departmentId;
    }

    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
        this.departmentIdSet = true;
    }

    public void unsetDepartmentId() {
        this.departmentIdSet = false;
    }


    public boolean isStartInsertDateSet() {
        return startInsertDateSet;
    }

    public Date getStartInsertDate() {
        return startInsertDate;
    }

    public void setStartInsertDate(Date startInsertDate) {
        this.startInsertDate = startInsertDate;
        this.startInsertDateSet = true;
    }

    public void unsetStartInsertDate() {
        this.startInsertDateSet = false;
    }

    public boolean isEndInsertDateSet() {
        return endInsertDateSet;
    }

    public Date getEndInsertDate() {
        return endInsertDate;
    }

    public void setEndInsertDate(Date endInsertDate) {
        this.endInsertDate = endInsertDate;
        this.endInsertDateSet = true;
    }

    public void unsetEndInsertDate() {
        this.endInsertDateSet = false;
    }


    public boolean isStartUpdateDateSet() {
        return startUpdateDateSet;
    }

    public Date getStartUpdateDate() {
        return startUpdateDate;
    }

    public void setStartUpdateDate(Date startUpdateDate) {
        this.startUpdateDate = startUpdateDate;
        this.startUpdateDateSet = true;
    }

    public void unsetStartUpdateDate() {
        this.startUpdateDateSet = false;
    }

    public boolean isEndUpdateDateSet() {
        return endUpdateDateSet;
    }

    public Date getEndUpdateDate() {
        return endUpdateDate;
    }

    public void setEndUpdateDate(Date endUpdateDate) {
        this.endUpdateDate = endUpdateDate;
        this.endUpdateDateSet = true;
    }

    public void unsetEndUpdateDate() {
        this.endUpdateDateSet = false;
    }

    // Fields

    private boolean ownerIdSet;
    private Integer ownerId;


    private boolean departmentIdSet;
    private Integer departmentId;


    private boolean startInsertDateSet;
    private Date startInsertDate;
    private boolean endInsertDateSet;
    private Date endInsertDate;


    private boolean startUpdateDateSet;
    private Date startUpdateDate;
    private boolean endUpdateDateSet;
    private Date endUpdateDate;

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
        this.nombreSet = true;
    }

    public boolean isNombreSet() {
        return nombreSet;
    }

    public String getNombreIngles() {
        return nombreIngles;
    }

    public void setNombreIngles(String nombreIngles) {
        this.nombreIngles = nombreIngles;
        this.nombreInglesSet = true;
    }

    public boolean isNombreInglesSet() {
        return nombreInglesSet;
    }

    public String getValor() {
        return valor;
    }

    public void setValor(String valor) {
        this.valor = valor;
        this.valorSet = true;
    }

    public boolean isValorSet() {
        return valorSet;
    }

    public String getIncertidumbre() {
        return incertidumbre;
    }

    public void setIncertidumbre(String incertidumbre) {
        this.incertidumbre = incertidumbre;
        this.incertidumbreSet = true;
    }

    public boolean isIncertidumbreSet() {
        return incertidumbreSet;
    }

    private String nombre;
    private boolean nombreSet;
    private String nombreIngles;
    private boolean nombreInglesSet;
    private String valor;
    private boolean valorSet;
    private String incertidumbre;
    private boolean incertidumbreSet;

    // Returns if there are a search condition active
    public boolean isSearchActive() {
        return customIsSearchActive() || nombreSet || nombreInglesSet || valorSet || incertidumbreSet || ownerIdSet || departmentIdSet || startInsertDateSet || endInsertDateSet || startUpdateDateSet || endUpdateDateSet;
    }

    /* generated by stajanov (do not edit/delete) */
    private void customGetHQL(StringBuilder ret, int argNum) {
        // TODO Auto-generated method stub

    }

    private boolean customIsSearchActive() {
        // TODO Auto-generated method stub
        return false;
    }

    private void customGetArguments(ArrayList<Object> ret) {
        // TODO Auto-generated method stub

    }

    private void customToString(StringBuilder ret) {
        // TODO Auto-generated method stub

    }

    private void customReset() {
        // TODO Auto-generated method stub

    }

}