/* 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 */

package com.autentia.intra.manager.document;

import com.autentia.intra.businessobject.Document;
import com.autentia.intra.dao.SortCriteria;
import com.autentia.intra.dao.hibernate.DocumentDAO;
import com.autentia.intra.dao.search.DocumentSearch;
import com.autentia.intra.util.SpringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.util.List;


public class DocumentManager {

/* Document - generated by stajanov (do not edit/delete) */


    /**
     * Logger
     */
    private static final Log log = LogFactory.getLog(DocumentManager.class);

    /**
     * Document DAO *
     */
    private DocumentDAO documentDAO;

    /**
     * Get default DocumentManager as defined in Spring's configuration file.
     *
     * @return the default singleton DocumentManager
     */
    public static DocumentManager getDefault() {
        return (DocumentManager) SpringUtils.getSpringBean("managerDocument");
    }

    /**
     * Empty constructor needed by CGLIB (Spring AOP)
     */
    protected DocumentManager() {
    }

    /**
     * Default constructor
     *
     * @deprecated do not construct managers alone: use Spring's declared beans
     */
    public DocumentManager(DocumentDAO documentDAO) {
        this.documentDAO = documentDAO;
    }

    /**
     * List documents.
     *
     * @param search search filter to apply
     * @param sort   sorting criteria
     * @return the list of all documents sorted by requested criterion
     */
    public List<Document> getAllEntities(DocumentSearch search, SortCriteria sort) {
        return documentDAO.search(search, sort);
    }

    /**
     * Get document by primary key.
     *
     * @return document selected by id.
     */
    public Document getEntityById(int id) {
        return documentDAO.getById(id);
    }

    /**
     * Insert document.
     */
    public void insertEntity(Document document) {
        documentDAO.insert(document);
    }

    /**
     * Update document.
     */
    public void updateEntity(Document document) {
        documentDAO.update(document);
    }

    /**
     * Delete document.
     */
    public void deleteEntity(Document document) {
        documentDAO.delete(document);
    }
/* Document - generated by stajanov (do not edit/delete) */


}
