/* 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 */

package com.autentia.intra.manager.document;

import com.autentia.intra.businessobject.DocumentVersion;
import com.autentia.intra.dao.SortCriteria;
import com.autentia.intra.dao.hibernate.DocumentVersionDAO;
import com.autentia.intra.dao.search.DocumentVersionSearch;
import com.autentia.intra.util.SpringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.util.List;


public class DocumentVersionManager {

/* generated by stajanov (do not edit/delete) */


    /**
     * Logger
     */
    private static final Log log = LogFactory.getLog(DocumentVersionManager.class);

    /**
     * DocumentVersion DAO *
     */
    private DocumentVersionDAO documentVersionDAO;

    /**
     * Get default DocumentVersionManager as defined in Spring's configuration file.
     *
     * @return the default singleton DocumentVersionManager
     */
    public static DocumentVersionManager getDefault() {
        return (DocumentVersionManager) SpringUtils.getSpringBean("managerDocumentVersion");
    }

    /**
     * Empty constructor needed by CGLIB (Spring AOP)
     */
    protected DocumentVersionManager() {
    }

    /**
     * Default constructor
     *
     * @deprecated do not construct managers alone: use Spring's declared beans
     */
    public DocumentVersionManager(DocumentVersionDAO documentVersionDAO) {
        this.documentVersionDAO = documentVersionDAO;
    }

    /**
     * List documentVersions.
     *
     * @param search search filter to apply
     * @param sort   sorting criteria
     * @return the list of all documentVersions sorted by requested criterion
     */
    public List<DocumentVersion> getAllEntities(DocumentVersionSearch search, SortCriteria sort) {
        return documentVersionDAO.search(search, sort);
    }

    /**
     * Get documentVersion by primary key.
     *
     * @return documentVersion selected by id.
     */
    public DocumentVersion getEntityById(int id) {
        return documentVersionDAO.getById(id);
    }

    /**
     * Insert documentVersion.
     */
    public void insertEntity(DocumentVersion documentVersion) {
        documentVersionDAO.insert(documentVersion);
    }

    /**
     * Update documentVersion.
     */
    public void updateEntity(DocumentVersion documentVersion) {
        documentVersionDAO.update(documentVersion);
    }

    /**
     * Delete documentVersion.
     */
    public void deleteEntity(DocumentVersion documentVersion) {
        documentVersionDAO.delete(documentVersion);
    }
/* generated by stajanov (do not edit/delete) */
}
