/* 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 */

package com.autentia.intra.manager.document;

import com.autentia.intra.businessobject.DocumentCategory;
import com.autentia.intra.dao.SortCriteria;
import com.autentia.intra.dao.hibernate.DocumentCategoryDAO;
import com.autentia.intra.dao.search.DocumentCategorySearch;
import com.autentia.intra.util.ConfigurationUtil;
import com.autentia.intra.util.SpringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.util.List;


public class DocumentCategoryManager {

/* DocumentCategory - generated by stajanov (do not edit/delete) */


    /**
     * Logger
     */
    private static final Log log = LogFactory.getLog(DocumentCategoryManager.class);

    /**
     * DocumentCategory DAO *
     */
    private DocumentCategoryDAO documentCategoryDAO;

    /**
     * Get default DocumentCategoryManager as defined in Spring's configuration file.
     *
     * @return the default singleton DocumentCategoryManager
     */
    public static DocumentCategoryManager getDefault() {
        return (DocumentCategoryManager) SpringUtils.getSpringBean("managerDocumentCategory");
    }

    /**
     * Empty constructor needed by CGLIB (Spring AOP)
     */
    protected DocumentCategoryManager() {
    }

    /**
     * Default constructor
     *
     * @deprecated do not construct managers alone: use Spring's declared beans
     */
    public DocumentCategoryManager(DocumentCategoryDAO documentCategoryDAO) {
        this.documentCategoryDAO = documentCategoryDAO;
    }

    /**
     * List documentCategorys.
     *
     * @param search search filter to apply
     * @param sort   sorting criteria
     * @return the list of all documentCategorys sorted by requested criterion
     */
    public List<DocumentCategory> getAllEntities(DocumentCategorySearch search, SortCriteria sort) {
        return documentCategoryDAO.search(search, sort);
    }

    /**
     * Get documentCategory by primary key.
     *
     * @return documentCategory selected by id.
     */
    public DocumentCategory getEntityById(int id) {
        return documentCategoryDAO.getById(id);
    }

    /**
     * Insert documentCategory.
     */
    public void insertEntity(DocumentCategory documentCategory) {
        documentCategoryDAO.insert(documentCategory);
    }

    /**
     * Update documentCategory.
     */
    public void updateEntity(DocumentCategory documentCategory) {
        documentCategoryDAO.update(documentCategory);
    }

    /**
     * Delete documentCategory.
     */
    public void deleteEntity(DocumentCategory documentCategory) {
        documentCategoryDAO.delete(documentCategory);
    }
/* DocumentCategory - generated by stajanov (do not edit/delete) */


    public DocumentCategory getDocumentCategoryParent() {
        return (DocumentCategory) documentCategoryDAO.getById(ConfigurationUtil.getDefault().getUserDocumentCategoryId());
    }

}
