/* 
 *  TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 */

package com.autentia.intra.manager.account;

import com.autentia.intra.businessobject.AccountEntryType;
import com.autentia.intra.dao.SortCriteria;
import com.autentia.intra.dao.hibernate.AccountEntryTypeDAO;
import com.autentia.intra.dao.search.AccountEntryTypeSearch;
import com.autentia.intra.util.SpringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.util.List;


public class AccountEntryTypeManager {

/* AccountEntryType - generated by stajanov (do not edit/delete) */


    /**
     * Logger
     */
    private static final Log log = LogFactory.getLog(AccountEntryTypeManager.class);

    /**
     * AccountEntryType DAO *
     */
    private AccountEntryTypeDAO accountEntryTypeDAO;

    /**
     * Get default AccountEntryTypeManager as defined in Spring's configuration file.
     *
     * @return the default singleton AccountEntryTypeManager
     */
    public static AccountEntryTypeManager getDefault() {
        return (AccountEntryTypeManager) SpringUtils.getSpringBean("managerAccountEntryType");
    }

    /**
     * Empty constructor needed by CGLIB (Spring AOP)
     */
    protected AccountEntryTypeManager() {
    }

    /**
     * Default constructor
     *
     * @deprecated do not construct managers alone: use Spring's declared beans
     */
    public AccountEntryTypeManager(AccountEntryTypeDAO accountEntryTypeDAO) {
        this.accountEntryTypeDAO = accountEntryTypeDAO;
    }

    /**
     * List accountEntryTypes.
     *
     * @param search search filter to apply
     * @param sort   sorting criteria
     * @return the list of all accountEntryTypes sorted by requested criterion
     */
    public List<AccountEntryType> getAllEntities(AccountEntryTypeSearch search, SortCriteria sort) {
        return accountEntryTypeDAO.search(search, sort);
    }

    /**
     * Get accountEntryType by primary key.
     *
     * @return accountEntryType selected by id.
     */
    public AccountEntryType getEntityById(int id) {
        return accountEntryTypeDAO.getById(id);
    }

    /**
     * Insert accountEntryType.
     */
    public void insertEntity(AccountEntryType accountEntryType) {
        accountEntryTypeDAO.insert(accountEntryType);
    }

    /**
     * Update accountEntryType.
     */
    public void updateEntity(AccountEntryType accountEntryType) {
        accountEntryTypeDAO.update(accountEntryType);
    }

    /**
     * Delete accountEntryType.
     */
    public void deleteEntity(AccountEntryType accountEntryType) {
        accountEntryTypeDAO.delete(accountEntryType);
    }

/* AccountEntryType - generated by stajanov (do not edit/delete) */
}
