<%-- 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 *
 --%>
<%@page language="java" contentType="text/html; charset=UTF-8" %>

<%@include file="/inc/tlibs.jsp" %>

<html>
<head>
    <%@include file="/inc/uiCore.jsp" %>
    <script type="text/javascript">
        function openPDF(id, idOrg) {
            var elem = document.getElementById("bill:account");
            var account = elem.value;
            openReportParameters("document/factura.pdf", "?id=" + id + "&idOrg=" + idOrg + "&idAccount=" + account + "&SUBREPORT_BILLHEADER=factura_subreport&SUBREPORT_BILLFOOTERINFO=footerInfo_subreport&SUBREPORT_BILLFOOTERACCOUNT=account_subreport", "");
        }

    </script>
</head>
<body>

<!-- editBill.jsp: generated by stajanov code generator -->
<f:loadBundle basename="com.autentia.intra.resources.messages" var="msg"/>
<i:location place="editBill" msg="${msg}"/>

<f:view>
<%@include file="/inc/header.jsp" %>
<h:form id="bill" enctype="multipart/form-data">

<%-- Header --%>
<i:titleBar name="${billBean.number}" msg="${msg}">
    <h:commandLink action="#{billBean.save}"
                   onclick="if(!askSave('#{billBean.id}','#{msg['question.confirmSave']}')) return false;">
        <h:graphicImage title="#{msg.entityActions_save}" value="/img/save.gif" styleClass="titleImg"/>
    </h:commandLink>
    <h:commandLink action="#{billBean.delete}"
                   onclick="if( !confirm('#{msg['question.confirmDelete']}') ) return false;"
                   rendered="#{billBean.puedoBorrar}">
        <h:graphicImage title="#{msg.entityActions_delete}" value="/img/delete.gif" styleClass="titleImg"/>
    </h:commandLink>
    <h:commandLink action="#{billBean.list}" immediate="true">
        <h:graphicImage title="#{msg.entityActions_back}" value="/img/back.gif" styleClass="titleImg"/>
    </h:commandLink>

    <h:commandLink rendered="#{billBean.puedoImprimir}" action="#"
                   onclick="openPDF('#{billBean.id}','#{billBean.client.id}')" immediate="true">
        <h:graphicImage title="#{msg['bill.print']}" value="/img/document.png" styleClass="titleImg"/>
    </h:commandLink>
    <h:commandLink action="#" title="Imprimir etiquetas"
                   onclick="openReportParameters('document/etiqueta_direccion.pdf','?id='+#{billBean.client.id}+'&tipoDireccion=direccionEnvioFactura','');"
                   immediate="true" rendered="#{billBean.client != null}">
        <h:graphicImage value="/img/envelope.png" styleClass="titleImg"/>
    </h:commandLink>
</i:titleBar>


<%-- Edition form --%>
<table class="editTable" cellpadding="0" cellspacing="0">

    <%-- Ignored field: id --%>

    <%-- Field: billType --%>
<tr>
    <td class="warning2">${msg['bill.selectType']}</td>

    <td class="editFieldCell">

        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="billType"/>
            <h:selectOneMenu id="billType" value="#{billBean.billType}" disabled="true">
                <f:converter converterId="autentia.EnumConverter"/>
                <f:selectItems value="#{billBean.billTypes}"/>
            </h:selectOneMenu>
        </h:panelGroup>

    </td>
</tr>

    <%-- Field: number --%>
<tr>
    <td class="editLabelRW">*${msg['bill.number']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="number"/>
            <h:inputText id="number" value="#{billBean.numberDefault}" required="true" styleClass="requiredFieldClass"
                         maxlength="64" validator="#{billBean.numberValidate}"/>
        </h:panelGroup>
    </td>
</tr>

    <%-- Field: provider --%>
<tr>
    <td class="editLabelRW">${msg['bill.provider']}:</td>

    <td class="editFieldCell">

        <h:panelGroup rendered="#{billBean.puedoPintarProvider}">
            <h:message styleClass="error" showSummary="true" showDetail="false" for="provider"/>
            <h:selectOneMenu id="provider" value="#{billBean.provider}" required="true" styleClass="requiredFieldClass">
                <f:selectItems value="#{billBean.providers}"/>
                <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
        </h:panelGroup>


    </td>
</tr>

    <%-- Field: organization --%>
<tr>
    <td class="editLabelRW">${msg['bill.organization']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="organization"/>
            <h:selectOneMenu id="organization" value="#{billBean.client}" immediate="true"
                             onchange="submit()"
                             valueChangeListener="#{billBean.onSelectedOrganizationChanged}">
                <f:selectItems value="#{billBean.organizations}"/>
                <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
        </h:panelGroup>
    </td>
</tr>

    <%-- Field: billable --%>
<tr>
    <td class="editLabelRW">${msg['bill.pendienteDePedido']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="pendienteDePedido"/>
            <h:selectBooleanCheckbox id="pendienteDePedido" value="#{billBean.bill.pendienteDePedido}"/>
        </h:panelGroup>
    </td>
</tr>

    <%-- Field: project --%>
<tr>
    <td class="editLabelRW">${msg['bill.project']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="project"/>
            <h:selectOneMenu id="project" value="#{billBean.project}">
                <f:selectItems value="#{billBean.projectsOpenBySelectedOrganizationOrBlank}"/>
                <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
        </h:panelGroup>
    </td>
</tr>

    <%-- Field: name --%>
<tr>
    <td class="editLabelRW">*${msg['bill.name']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="name"/>
            <h:inputText id="name" value="#{billBean.name}" size="100" maxlength="128" required="true"
                         styleClass="requiredFieldClass"/>
        </h:panelGroup>
    </td>
</tr>

    <%-- Field: orderNumber --%>
<tr>
    <td class="editLabelRW">${msg['bill.orderNumber']}:</td>

    <td class="editFieldCell">

        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="orderNumber"/>
            <h:inputText id="orderNumber" value="#{billBean.orderNumber}" maxlength="64"
                         styleClass="requiredFieldClass"/>
        </h:panelGroup>

    </td>
</tr>

    <%-- Field: lineaTrabajo --%>
<tr>
    <td class="editLabelRW">*${msg['bill.lineaTrabajo']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="lineaTrabajo"/>
            <h:selectOneMenu id="lineaTrabajo" value="#{billBean.bill.lineaTrabajo}" required="true"
                             styleClass="requiredFieldClass">
                <f:selectItems value="#{billBean.lineaTrabajos}"/>
                <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
            <h:outputText value="Sugerencia: #{billBean.bill.lineaTrabajoDefault.ruta}"/>
        </h:panelGroup>
    </td>
</tr>


    <%-- Field: contact --%>
<tr>
    <td class="editLabelRW">*${msg['bill.contact']}:</td>

    <td class="editFieldCell">

        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="contact"/>
            <h:selectOneMenu id="contact" value="#{billBean.contact}" required="true"
                             styleClass="requiredFieldClass">
                <f:selectItems value="#{billBean.contactsBySelectedOrganization}"/>
                <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
        </h:panelGroup>

    </td>
</tr>

<tr>
    <td class="editLabelRW">${msg['bill.account']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="account"/>
            <h:selectOneMenu id="account" value="#{billBean.selectedAccount}" required="true"
                             styleClass="requiredFieldClass">
                <f:selectItems value="#{billBean.accounts}"/>
                <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
        </h:panelGroup>
    </td>
</tr>


    <%-- Field: breakDown --%>
<tr>
    <td class="editLabelRW">${msg['bill.breakDown']}:</td>

    <td class="editFieldCell">
        <%@include file="inlineEditBillBreakDown.jsp" %>

    </td>
</tr>

    <%-- Field: albarans --%>

<tr>
    <td class="editLabelRW">${msg['bill.albarans']}: (con sus informes con sus ensayos)</td>

    <td class="editFieldCell">
        <%@include file="inlineEditBillAlbaran.jsp" %>
    </td>
</tr>


    <%-- Field: offers --%>

<tr>
    <td class="editLabelRW">${msg['bill.offers']}: (con tareas y costes generales)</td>

    <td class="editFieldCell">
        <%@include file="inlineEditBillOffer.jsp" %>
    </td>
</tr>


<tr>
    <td class="editLabelRW">${msg['bill.total']}:</td>
    <td class="editFieldCell" align="right">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="total"/>
            <h:outputText id="total" value="#{billBean.total}" styleClass="requiredFieldClass"/>
        </h:panelGroup>
    </td>
</tr>


    <%-- Field: creationDate --%>
<tr>
    <td class="editLabelRW">*${msg['bill.creationDate']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="creationDate"/>
            <t:inputCalendar id="creationDate" value="#{billBean.creationDate}"
                             required="true" styleClass="requiredFieldClass"
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true"
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                    />
        </h:panelGroup>
    </td>
</tr>

    <%-- Field: startBillDate --%>
<tr>
    <td class="editLabelRW">*${msg['bill.startBillDate']}:</td>

    <td class="editFieldCell">

        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="startBillDate"/>
            <t:inputCalendar id="startBillDate" value="#{billBean.startBillDate}" required="true"
                             styleClass="requiredFieldClass"
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true"
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                    />
        </h:panelGroup>

    </td>
</tr>


    <%-- Field: endBillDate --%>
<tr>
    <td class="editLabelRW">*${msg['bill.endBillDate']}:</td>

    <td class="editFieldCell">

        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="endBillDate"/>
            <t:inputCalendar id="endBillDate" value="#{billBean.endBillDate}" required="true"
                             styleClass="requiredFieldClass"
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true"
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                    />
        </h:panelGroup>

    </td>
</tr>

    <%-- Field: expiration --%>
<tr>
    <td class="editLabelRW">${msg['bill.expiration']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="expiration"/>
            <h:inputText id="expiration" value="#{billBean.expiration}" size="10" maxlength="6"/>
        </h:panelGroup>
    </td>
</tr>

    <%-- Field: paymentMode --%>
<tr>
    <td class="editLabelRW">*${msg['bill.paymentMode']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="paymentMode"/>
            <h:selectOneMenu id="paymentMode" value="#{billBean.paymentMode}" required="true"
                             styleClass="requiredFieldClass">
                <f:converter converterId="autentia.EnumConverter"/>
                <f:selectItems value="#{billBean.paymentModes}"/>
            </h:selectOneMenu>
        </h:panelGroup>
    </td>
</tr>

    <%-- Field: state --%>
<tr>
    <td class="editLabelRW">*${msg['bill.state']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="state"/>
            <h:selectOneMenu id="state" value="#{billBean.state}" required="true" styleClass="requiredFieldClass">
                <f:converter converterId="autentia.EnumConverter"/>
                <f:selectItems value="#{billBean.states}"/>
            </h:selectOneMenu>
        </h:panelGroup>
    </td>
</tr>


    <%-- Field: file --%>
<tr>
    <td class="editLabelRW">${msg['bill.file']}:</td>
    <td class="editFieldCell">
        <h:commandLink action="#{billBean.deleteFile}" immediate="true" rendered="#{billBean.file != null}">
            <h:graphicImage title="#{msg.entityActions_delete}" value="/img/delete.gif"
                            styleClass="titleImg"/>
        </h:commandLink>
        <i:fileLink type="bill" objectId="${billBean.id}" file="${billBean.file}" mime="${billBean.fileMime}"/>
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="file"/>
            <t:inputFileUpload id="file" size="58" value="#{billBean.uploadFile}" storage="file"/>
        </h:panelGroup>
    </td>
</tr>

    <%-- Ignored field: fileMime --%>

    <%-- Field: observations --%>
<tr>
    <td class="editLabelRW">${msg['bill.observations']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="observations"/>
            <h:inputTextarea id="observations" value="#{billBean.observations}" rows="5" cols="68"/>
        </h:panelGroup>
    </td>
</tr>


</table>
<%-- Field: versiones --%>
<h:panelGrid rendered="#{billBean.id!=null}" columnClasses="editLabelRW">
    <h:panelGroup styleClass="editLabelRW">
        <h:outputText value="#{msg['bill.entries']}"/>
        <h:commandLink action="#{billBean.searchEntries}" immediate="true">
            <h:graphicImage title="#{msg['bill.searchEntries']}" value="/img/search.gif" styleClass="titleImg"/>
        </h:commandLink>
    </h:panelGroup>
    <h:panelGroup>

        <%@include file="inlineShowEntries.jsp" %>
    </h:panelGroup>
</h:panelGrid>


<h:commandLink action="#{historicoBean.ver_historico}" immediate="true" target="_blank"
               rendered="#{billBean.id != null}">
    <f:param name="idObjeto" value="#{billBean.id}"/>
    <f:param name="klazz" value="#{billBean.bill.class.name}"/>
    <h:graphicImage value="/img/historico.png" styleClass="titleImg"/>
</h:commandLink>

</h:form>
</f:view>

</body>
</html>  		

