/* 
 *  TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 */

package com.autentia.intra.dao.hibernate;

import com.autentia.intra.businessobject.AccountEntry;
import com.autentia.intra.dao.DataAccException;
import com.autentia.intra.dao.IDataAccessObject;
import com.autentia.intra.dao.SearchCriteria;
import com.autentia.intra.dao.SortCriteria;
import com.autentia.intra.util.SpringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.util.List;


public class AccountEntryDAO extends HibernateManagerBase implements IDataAccessObject<AccountEntry> {
/* accountEntry - generated by stajanov (do not edit/delete) */


    /**
     * Logger
     */
    private static final Log log = LogFactory.getLog(AccountEntryDAO.class);

    /**
     * Get default AccountEntryDAO as defined in Spring's configuration file.
     *
     * @return the default singleton AccountEntryDAO
     */
    public static AccountEntryDAO getDefault() {
        return (AccountEntryDAO) SpringUtils.getSpringBean("daoAccountEntry");
    }

    /**
     * Constructor
     *
     * @deprecated do not construct DAOs alone: use Spring's declared beans
     */
    public AccountEntryDAO() {
        super(false);
    }

    /**
     * Retrieve a AccountEntry object from database given its id
     *
     * @param id primary key of AccountEntry object
     * @return the AccountEntry object identified by the id
     * @throws DataAccException on error
     */
    public AccountEntry getById(int id) throws DataAccException {
        return super.getByPk(AccountEntry.class, id);
    }

    /**
     * Get all AccountEntry objects from database sorted by the given criteria
     *
     * @param crit the sorting criteria
     * @return a list with all existing AccountEntry objects
     * @throws DataAccException on error
     */
    public List<AccountEntry> search(SortCriteria crit) throws DataAccException {
        return super.list(AccountEntry.class, crit);
    }

    /**
     * Get specified AccountEntry objects from database sorted by the given criteria
     *
     * @param search search criteria
     * @param sort   the sorting criteria
     * @return a list with AccountEntry objects matching the search criteria
     * @throws DataAccException on error
     */
    public List<AccountEntry> search(SearchCriteria search, SortCriteria sort) throws DataAccException {
        return super.search(AccountEntry.class, search, sort);
    }

    /**
     * Insert a new AccountEntry object in database
     *
     * @param dao the AccountEntry object to insert
     * @throws DataAccException on error
     */
    public void insert(AccountEntry dao) throws DataAccException {
        super.insert(dao);
    }

    /**
     * Update an existing AccountEntry object in database
     *
     * @param dao the AccountEntry object to update
     * @throws DataAccException on error
     */
    public void update(AccountEntry dao) throws DataAccException {
        super.update(dao, dao.getId());
    }

    /**
     * Delete an existing AccountEntry object in database
     *
     * @param dao the AccountEntry object to update
     * @throws DataAccException on error
     */
    public void delete(AccountEntry dao) throws DataAccException {
        super.delete(dao, dao.getId());
    }

/* accountEntry - generated by stajanov (do not edit/delete) */
}
