/* 
 *  TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 */

package com.autentia.intra.dao.hibernate;

import com.autentia.intra.businessobject.Historial;
import com.autentia.intra.dao.DataAccException;
import com.autentia.intra.dao.IDataAccessObject;
import com.autentia.intra.dao.SearchCriteria;
import com.autentia.intra.dao.SortCriteria;
import com.autentia.intra.util.SpringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.util.List;

/**
 * DAO for Historial objects.
 *
 * @author stajanov code generator
 */
public class HistorialDAO extends HibernateManagerBase implements IDataAccessObject<Historial> {
    /* historial - generated by stajanov (do not edit/delete) */
    /**
     * Logger
     */
    private static final Log log = LogFactory.getLog(HistorialDAO.class);

    /**
     * Get default HistorialDAO as defined in Spring's configuration file.
     *
     * @return the default singleton HistorialDAO
     */
    public static HistorialDAO getDefault() {
        return (HistorialDAO) SpringUtils.getSpringBean("daoHistorial");
    }

    /**
     * Constructor
     *
     * @deprecated do not construct DAOs alone: use Spring's declared beans
     */
    public HistorialDAO() {
        super(false);
    }

    /**
     * Retrieve a Historial object from database given its id
     *
     * @param id primary key of Historial object
     * @return the Historial object identified by the id
     * @throws DataAccException on error
     */
    public Historial getById(int id) throws DataAccException {
        return super.getByPk(Historial.class, id);
    }

    /**
     * Get all Historial objects from database sorted by the given criteria
     *
     * @param crit the sorting criteria
     * @return a list with all existing Historial objects
     * @throws DataAccException on error
     */
    public List<Historial> search(SortCriteria crit) throws DataAccException {
        return super.list(Historial.class, crit);
    }

    /**
     * Get specified Historial objects from database sorted by the given criteria
     *
     * @param search search criteria
     * @param sort   the sorting criteria
     * @return a list with Historial objects matching the search criteria
     * @throws DataAccException on error
     */
    public List<Historial> search(SearchCriteria search, SortCriteria sort) throws DataAccException {
        return super.search(Historial.class, search, sort);
    }

    /**
     * Insert a new Historial object in database
     *
     * @param dao the Historial object to insert
     * @throws DataAccException on error
     */
    public void insert(Historial dao) throws DataAccException {
        super.insert(dao);
    }

    /**
     * Update an existing Historial object in database
     *
     * @param dao the Historial object to update
     * @throws DataAccException on error
     */
    public void update(Historial dao) throws DataAccException {
        super.update(dao, dao.getId());
    }

    /**
     * Delete an existing Historial object in database
     *
     * @param dao the Historial object to update
     * @throws DataAccException on error
     */
    public void delete(Historial dao) throws DataAccException {
        super.delete(dao, dao.getId());
    }
/* historial - generated by stajanov (do not edit/delete) */

    public List<Historial> search(Class klazz, Integer idObjeto) {
        return (List<Historial>) search("from Historial where klazz = :arg0 and idObjeto = :arg1 order by fechaHora desc, tipoCambio desc", klazz, idObjeto);
    }
}
