/* 
 *  TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 */


package com.autentia.intra.dao.hibernate;

import com.autentia.intra.businessobject.OfferEnsayo;
import com.autentia.intra.dao.DataAccException;
import com.autentia.intra.dao.IDataAccessObject;
import com.autentia.intra.dao.SearchCriteria;
import com.autentia.intra.dao.SortCriteria;
import com.autentia.intra.util.SpringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.util.List;


public class OfferEnsayoDAO extends HibernateManagerBase implements IDataAccessObject<OfferEnsayo> {

    /* OfferEnsayo - generated by stajanov (do not edit/delete) */
    /**
     * Logger
     */
    private static final Log log = LogFactory.getLog(OfferEnsayoDAO.class);

    /**
     * Get default OfferEnsayoDAO as defined in Spring's configuration file.
     *
     * @return the default singleton OfferEnsayoDAO
     */
    public static OfferEnsayoDAO getDefault() {
        return (OfferEnsayoDAO) SpringUtils.getSpringBean("daoOfferEnsayo");
    }

    /**
     * Constructor
     *
     * @deprecated do not construct DAOs alone: use Spring's declared beans
     */
    public OfferEnsayoDAO() {
        super(false);
    }

    /**
     * Retrieve a OfferEnsayo object from database given its id
     *
     * @param id primary key of OfferEnsayo object
     * @return the OfferEnsayo object identified by the id
     * @throws DataAccException on error
     */
    public OfferEnsayo getById(int id) throws DataAccException {
        return super.getByPk(OfferEnsayo.class, id);
    }

    /**
     * Get all OfferEnsayo objects from database sorted by the given criteria
     *
     * @param crit the sorting criteria
     * @return a list with all existing OfferEnsayo objects
     * @throws DataAccException on error
     */
    public List<OfferEnsayo> search(SortCriteria crit) throws DataAccException {
        return super.list(OfferEnsayo.class, crit);
    }

    /**
     * Get specified OfferEnsayo objects from database sorted by the given criteria
     *
     * @param search search criteria
     * @param sort   the sorting criteria
     * @return a list with OfferEnsayo objects matching the search criteria
     * @throws DataAccException on error
     */
    public List<OfferEnsayo> search(SearchCriteria search, SortCriteria sort) throws DataAccException {
        return super.search(OfferEnsayo.class, search, sort);
    }

    /**
     * Insert a new OfferEnsayo object in database
     *
     * @param dao the OfferEnsayo object to insert
     * @throws DataAccException on error
     */
    public void insert(OfferEnsayo dao) throws DataAccException {
        super.insert(dao);
    }

    /**
     * Update an existing OfferEnsayo object in database
     *
     * @param dao the OfferEnsayo object to update
     * @throws DataAccException on error
     */
    public void update(OfferEnsayo dao) throws DataAccException {
        super.update(dao, dao.getId());
    }

    /**
     * Delete an existing OfferEnsayo object in database
     *
     * @param dao the OfferEnsayo object to update
     * @throws DataAccException on error
     */
    public void delete(OfferEnsayo dao) throws DataAccException {
        super.delete(dao, dao.getId());
    }
/* OfferEnsayo - generated by stajanov (do not edit/delete) */


}
