/* 
 *  TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 */

package com.autentia.intra.dao.hibernate;

import com.autentia.intra.businessobject.PautaEnsayo;
import com.autentia.intra.dao.DataAccException;
import com.autentia.intra.dao.IDataAccessObject;
import com.autentia.intra.dao.SearchCriteria;
import com.autentia.intra.dao.SortCriteria;
import com.autentia.intra.util.SpringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.util.List;


/**
 * DAO for Parametrostring objects.
 *
 * @author stajanov code generator
 */
public class PautaEnsayoDAO extends HibernateManagerBase implements IDataAccessObject<PautaEnsayo> {
/* PautaEnsayo - generated by stajanov (do not edit/delete) */


    /**
     * Logger
     */
    private static final Log log = LogFactory.getLog(PautaEnsayoDAO.class);

    /**
     * Get default PautaEnsayoDAO as defined in Spring's configuration file.
     *
     * @return the default singleton PautaEnsayoDAO
     */
    public static PautaEnsayoDAO getDefault() {
        return (PautaEnsayoDAO) SpringUtils.getSpringBean("daoPautaEnsayo");
    }

    /**
     * Constructor
     *
     * @deprecated do not construct DAOs alone: use Spring's declared beans
     */
    public PautaEnsayoDAO() {
        super(false);
    }

    /**
     * Retrieve a PautaEnsayo object from database given its id
     *
     * @param id primary key of PautaEnsayo object
     * @return the PautaEnsayo object identified by the id
     * @throws com.autentia.intra.dao.DataAccException
     *          on error
     */
    public PautaEnsayo getById(int id) throws DataAccException {
        return super.getByPk(PautaEnsayo.class, id);
    }

    /**
     * Get all PautaEnsayo objects from database sorted by the given criteria
     *
     * @param crit the sorting criteria
     * @return a list with all existing PautaEnsayo objects
     * @throws com.autentia.intra.dao.DataAccException
     *          on error
     */
    public List<PautaEnsayo> search(SortCriteria crit) throws DataAccException {
        return super.list(PautaEnsayo.class, crit);
    }

    /**
     * Get specified PautaEnsayo objects from database sorted by the given criteria
     *
     * @param search search criteria
     * @param sort   the sorting criteria
     * @return a list with PautaEnsayo objects matching the search criteria
     * @throws com.autentia.intra.dao.DataAccException
     *          on error
     */
    public List<PautaEnsayo> search(SearchCriteria search, SortCriteria sort) throws DataAccException {
        return super.search(PautaEnsayo.class, search, sort);
    }

    /**
     * Insert a new PautaEnsayo object in database
     *
     * @param dao the PautaEnsayo object to insert
     * @throws com.autentia.intra.dao.DataAccException
     *          on error
     */
    public void insert(PautaEnsayo dao) throws DataAccException {
        super.insert(dao);
        PautaDAO pautaDAO = PautaDAO.getDefault();
        pautaDAO.update(dao.getPauta());
    }

    /**
     * Update an existing PautaEnsayo object in database
     *
     * @param dao the PautaEnsayo object to update
     * @throws com.autentia.intra.dao.DataAccException
     *          on error
     */
    public void update(PautaEnsayo dao) throws DataAccException {
        super.update(dao, dao.getId());
        PautaDAO pautaDAO = PautaDAO.getDefault();
        pautaDAO.update(dao.getPauta());
    }

    /**
     * Delete an existing PautaEnsayo object in database
     *
     * @param dao the PautaEnsayo object to update
     * @throws com.autentia.intra.dao.DataAccException
     *          on error
     */
    public void delete(PautaEnsayo dao) throws DataAccException {
        super.delete(dao, dao.getId());
    }

/* PautaEnsayo - generated by stajanov (do not edit/delete) */

}