/* 
 *  TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 */

package com.autentia.intra.dao.hibernate;

import com.autentia.intra.businessobject.Province;
import com.autentia.intra.dao.DataAccException;
import com.autentia.intra.dao.IDataAccessObject;
import com.autentia.intra.dao.SearchCriteria;
import com.autentia.intra.dao.SortCriteria;
import com.autentia.intra.util.SpringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.util.List;

/**
 * DAO for Province objects.
 *
 * @author stajanov code generator
 */
public class ProvinceDAO extends HibernateManagerBase implements IDataAccessObject<Province> {
    /* province - generated by stajanov (do not edit/delete) */
    /**
     * Logger
     */
    private static final Log log = LogFactory.getLog(ProvinceDAO.class);

    /**
     * Get default ProvinceDAO as defined in Spring's configuration file.
     *
     * @return the default singleton ProvinceDAO
     */
    public static ProvinceDAO getDefault() {
        return (ProvinceDAO) SpringUtils.getSpringBean("daoProvince");
    }

    /**
     * Constructor
     *
     * @deprecated do not construct DAOs alone: use Spring's declared beans
     */
    public ProvinceDAO() {
        super(false);
    }

    /**
     * Retrieve a Province object from database given its id
     *
     * @param id primary key of Province object
     * @return the Province object identified by the id
     * @throws DataAccException on error
     */
    public Province getById(int id) throws DataAccException {
        return super.getByPk(Province.class, id);
    }

    /**
     * Get all Province objects from database sorted by the given criteria
     *
     * @param crit the sorting criteria
     * @return a list with all existing Province objects
     * @throws DataAccException on error
     */
    public List<Province> search(SortCriteria crit) throws DataAccException {
        return super.list(Province.class, crit);
    }

    /**
     * Get specified Province objects from database sorted by the given criteria
     *
     * @param search search criteria
     * @param sort   the sorting criteria
     * @return a list with Province objects matching the search criteria
     * @throws DataAccException on error
     */
    public List<Province> search(SearchCriteria search, SortCriteria sort) throws DataAccException {
        return super.search(Province.class, search, sort);
    }

    /**
     * Insert a new Province object in database
     *
     * @param dao the Province object to insert
     * @throws DataAccException on error
     */
    public void insert(Province dao) throws DataAccException {
        super.insert(dao);
    }

    /**
     * Update an existing Province object in database
     *
     * @param dao the Province object to update
     * @throws DataAccException on error
     */
    public void update(Province dao) throws DataAccException {
        super.update(dao, dao.getId());
    }

    /**
     * Delete an existing Province object in database
     *
     * @param dao the Province object to update
     * @throws DataAccException on error
     */
    public void delete(Province dao) throws DataAccException {
        super.delete(dao, dao.getId());
    }
/* province - generated by stajanov (do not edit/delete) */
}
