/* 
 *  TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 */

package com.autentia.intra.manager.admin;

import com.autentia.intra.businessobject.ContractType;
import com.autentia.intra.dao.SortCriteria;
import com.autentia.intra.dao.hibernate.ContractTypeDAO;
import com.autentia.intra.dao.search.ContractTypeSearch;
import com.autentia.intra.util.SpringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.util.List;


public class ContractTypeManager {

/* Department - generated by stajanov (do not edit/delete) */


    /**
     * Logger
     */
    private static final Log log = LogFactory.getLog(ContractTypeManager.class);

    /**
     * ContractType DAO *
     */
    private ContractTypeDAO contractTypeDAO;

    /**
     * Get default ContractTypeManager as defined in Spring's configuration file.
     *
     * @return the default singleton ContractTypeManager
     */
    public static ContractTypeManager getDefault() {
        return (ContractTypeManager) SpringUtils.getSpringBean("managerContractType");
    }

    /**
     * Empty constructor needed by CGLIB (Spring AOP)
     */
    protected ContractTypeManager() {
    }

    /**
     * Default constructor
     *
     * @deprecated do not construct managers alone: use Spring's declared beans
     */
    public ContractTypeManager(ContractTypeDAO contractTypeDAO) {
        this.contractTypeDAO = contractTypeDAO;
    }

    /**
     * List contractTypes.
     *
     * @param search search filter to apply
     * @param sort   sorting criteria
     * @return the list of all contractTypes sorted by requested criterion
     */
    public List<ContractType> getAllEntities(ContractTypeSearch search, SortCriteria sort) {
        return contractTypeDAO.search(search, sort);
    }

    /**
     * Get contractType by primary key.
     *
     * @return contractType selected by id.
     */
    public ContractType getEntityById(int id) {
        return contractTypeDAO.getById(id);
    }

    /**
     * Insert contractType.
     */
    public void insertEntity(ContractType contractType) {
        contractTypeDAO.insert(contractType);
    }

    /**
     * Update contractType.
     */
    public void updateEntity(ContractType contractType) {
        contractTypeDAO.update(contractType);
    }

    /**
     * Delete contractType.
     */
    public void deleteEntity(ContractType contractType) {
        contractTypeDAO.delete(contractType);
    }

/* Department - generated by stajanov (do not edit/delete) */


}
