/* 
 *  TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 */


package com.autentia.intra.manager.admin;


import com.autentia.intra.businessobject.Department;
import com.autentia.intra.dao.SortCriteria;
import com.autentia.intra.dao.hibernate.DepartmentDAO;
import com.autentia.intra.dao.search.DepartmentSearch;
import com.autentia.intra.util.SpringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.util.List;


public class DepartmentManager {

/* Department - generated by stajanov (do not edit/delete) */


    /**
     * Logger
     */
    private static final Log log = LogFactory.getLog(DepartmentManager.class);

    /**
     * Department DAO *
     */
    private DepartmentDAO departmentDAO;

    /**
     * Get default DepartmentManager as defined in Spring's configuration file.
     *
     * @return the default singleton DepartmentManager
     */
    public static DepartmentManager getDefault() {
        return (DepartmentManager) SpringUtils.getSpringBean("managerDepartment");
    }

    /**
     * Empty constructor needed by CGLIB (Spring AOP)
     */
    protected DepartmentManager() {
    }

    /**
     * Default constructor
     *
     * @deprecated do not construct managers alone: use Spring's declared beans
     */
    public DepartmentManager(DepartmentDAO departmentDAO) {
        this.departmentDAO = departmentDAO;
    }

    /**
     * List departments.
     *
     * @param search search filter to apply
     * @param sort   sorting criteria
     * @return the list of all departments sorted by requested criterion
     */
    public List<Department> getAllEntities(DepartmentSearch search, SortCriteria sort) {
        return departmentDAO.search(search, sort);
    }

    /**
     * Get department by primary key.
     *
     * @return department selected by id.
     */
    public Department getEntityById(int id) {
        return departmentDAO.getById(id);
    }

    /**
     * Insert department.
     */
    public void insertEntity(Department department) {
        departmentDAO.insert(department);
    }

    /**
     * Update department.
     */
    public void updateEntity(Department department) {
        departmentDAO.update(department);
    }

    /**
     * Delete department.
     */
    public void deleteEntity(Department department) {
        departmentDAO.delete(department);
    }

/* Department - generated by stajanov (do not edit/delete) */


}
