/* 
 *  TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 */


package com.autentia.intra.manager.admin;

import com.autentia.intra.businessobject.ProjectCost;
import com.autentia.intra.dao.SortCriteria;
import com.autentia.intra.dao.hibernate.ProjectCostDAO;
import com.autentia.intra.dao.search.ProjectCostSearch;
import com.autentia.intra.util.SpringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.util.List;


public class ProjectCostManager {
/* generated by stajanov (do not edit/delete) */


    /**
     * Logger
     */
    private static final Log log = LogFactory.getLog(ProjectCostManager.class);

    /**
     * ProjectCost DAO *
     */
    private ProjectCostDAO projectCostDAO;

    /**
     * Get default ProjectCostManager as defined in Spring's configuration file.
     *
     * @return the default singleton ProjectCostManager
     */
    public static ProjectCostManager getDefault() {
        return (ProjectCostManager) SpringUtils.getSpringBean("managerProjectCost");
    }

    /**
     * Empty constructor needed by CGLIB (Spring AOP)
     */
    protected ProjectCostManager() {
    }

    /**
     * Default constructor
     *
     * @deprecated do not construct managers alone: use Spring's declared beans
     */
    public ProjectCostManager(ProjectCostDAO projectCostDAO) {
        this.projectCostDAO = projectCostDAO;
    }

    /**
     * List projectCosts.
     *
     * @param search search filter to apply
     * @param sort   sorting criteria
     * @return the list of all projectCosts sorted by requested criterion
     */
    public List<ProjectCost> getAllEntities(ProjectCostSearch search, SortCriteria sort) {
        return projectCostDAO.search(search, sort);
    }

    /**
     * Get projectCost by primary key.
     *
     * @return projectCost selected by id.
     */
    public ProjectCost getEntityById(int id) {
        return projectCostDAO.getById(id);
    }

    /**
     * Insert projectCost.
     */
    public void insertEntity(ProjectCost projectCost) {
        projectCostDAO.insert(projectCost);
    }

    /**
     * Update projectCost.
     */
    public void updateEntity(ProjectCost projectCost) {
        projectCostDAO.update(projectCost);
    }

    /**
     * Delete projectCost.
     */
    public void deleteEntity(ProjectCost projectCost) {
        projectCostDAO.delete(projectCost);
    }
/* generated by stajanov (do not edit/delete) */
}
