/* 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 */


package com.autentia.intra.manager.admin;

import com.autentia.intra.businessobject.ProjectEnsayoRequerimiento;
import com.autentia.intra.dao.SortCriteria;
import com.autentia.intra.dao.hibernate.ProjectEnsayoRequerimientoDAO;
import com.autentia.intra.dao.search.ProjectEnsayoRequerimientoSearch;
import com.autentia.intra.manager.contacts.ParametroStringManager;
import com.autentia.intra.util.SpringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.util.List;


public class ProjectEnsayoRequerimientoManager {


    /**
     * Logger
     */
    private static final Log log = LogFactory.getLog(ProjectEnsayoRequerimientoManager.class);

    /**
     * ParametroString DAO *
     */
    private ProjectEnsayoRequerimientoDAO projectEnsayoRequerimientoDAO;

    /**
     * Get default ParametroStringManager as defined in Spring's configuration file.
     *
     * @return the default singleton ParametroStringManager
     */
    public static ParametroStringManager getDefault() {
        return (ParametroStringManager) SpringUtils.getSpringBean("managerProjectEnsayoRequerimiento");
    }

    /**
     * Empty constructor needed by CGLIB (Spring AOP)
     */
    protected ProjectEnsayoRequerimientoManager() {
    }

    /**
     * Default constructor
     *
     * @deprecated do not construct managers alone: use Spring's declared beans
     */
    public ProjectEnsayoRequerimientoManager(ProjectEnsayoRequerimientoDAO projectEnsayoRequerimientoDAO) {
        this.projectEnsayoRequerimientoDAO = projectEnsayoRequerimientoDAO;
    }

    /**
     * List pautas.
     *
     * @param search search filter to apply
     * @param sort   sorting criteria
     * @return the list of all pautas sorted by requested criterion
     */
    public List<ProjectEnsayoRequerimiento> getAllEntities(ProjectEnsayoRequerimientoSearch search, SortCriteria sort) {
        return projectEnsayoRequerimientoDAO.search(search, sort);
    }

    /**
     * Get pauta by primary key.
     *
     * @return pauta selected by id.
     */
    public ProjectEnsayoRequerimiento getEntityById(int id) {
        return projectEnsayoRequerimientoDAO.getById(id);
    }

    /**
     * Insert pauta.
     */
    public void insertEntity(ProjectEnsayoRequerimiento pauta) {
        projectEnsayoRequerimientoDAO.insert(pauta);
    }

    /**
     * Update pauta.
     */
    public void updateEntity(ProjectEnsayoRequerimiento pauta) {
        projectEnsayoRequerimientoDAO.update(pauta);
    }

    /**
     * Delete pauta.
     */
    public void deleteEntity(ProjectEnsayoRequerimiento pauta) {
        projectEnsayoRequerimientoDAO.delete(pauta);
    }

/* ProjectEnsayoRequerimiento - generated by stajanov (do not edit/delete) */


}