/* 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 */


package com.autentia.intra.manager.admin;

import com.autentia.intra.businessobject.ProjectEnsayo;
import com.autentia.intra.dao.SortCriteria;
import com.autentia.intra.dao.hibernate.ProjectEnsayoDAO;
import com.autentia.intra.dao.search.ProjectEnsayoSearch;
import com.autentia.intra.util.SpringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.util.List;


public class ProjectEnsayoManager {

/* generated by stajanov (do not edit/delete) */


    /**
     * Logger
     */
    private static final Log log = LogFactory.getLog(ProjectEnsayoManager.class);

    /**
     * ProjectEnsayo DAO *
     */
    private ProjectEnsayoDAO projectEnsayoDAO;

    /**
     * Get default ProjectEnsayoManager as defined in Spring's configuration file.
     *
     * @return the default singleton ProjectEnsayoManager
     */
    public static ProjectEnsayoManager getDefault() {
        return (ProjectEnsayoManager) SpringUtils.getSpringBean("managerProjectEnsayo");
    }

    /**
     * Empty constructor needed by CGLIB (Spring AOP)
     */
    protected ProjectEnsayoManager() {
    }

    /**
     * Default constructor
     *
     * @deprecated do not construct managers alone: use Spring's declared beans
     */
    public ProjectEnsayoManager(ProjectEnsayoDAO projectEnsayoDAO) {
        this.projectEnsayoDAO = projectEnsayoDAO;
    }

    /**
     * List projectEnsayos.
     *
     * @param search search filter to apply
     * @param sort   sorting criteria
     * @return the list of all projectEnsayos sorted by requested criterion
     */
    public List<ProjectEnsayo> getAllEntities(ProjectEnsayoSearch search, SortCriteria sort) {
        return projectEnsayoDAO.search(search, sort);
    }

    /**
     * Get projectEnsayo by primary key.
     *
     * @return projectEnsayo selected by id.
     */
    public ProjectEnsayo getEntityById(int id) {
        return projectEnsayoDAO.getById(id);
    }

    /**
     * Insert projectEnsayo.
     */
    public void insertEntity(ProjectEnsayo projectEnsayo) {
        projectEnsayoDAO.insert(projectEnsayo);
    }

    /**
     * Update projectEnsayo.
     */
    public void updateEntity(ProjectEnsayo projectEnsayo) {
        projectEnsayoDAO.update(projectEnsayo);
    }

    /**
     * Delete projectEnsayo.
     */
    public void deleteEntity(ProjectEnsayo projectEnsayo) {
        projectEnsayoDAO.delete(projectEnsayo);
    }
/* generated by stajanov (do not edit/delete) */
}
