/* 
 *  TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 */


package com.autentia.intra.manager.admin;

import com.autentia.intra.businessobject.Offer;
import com.autentia.intra.businessobject.Organization;
import com.autentia.intra.businessobject.Project;
import com.autentia.intra.dao.SortCriteria;
import com.autentia.intra.dao.hibernate.OfferDAO;
import com.autentia.intra.dao.hibernate.ProjectDAO;
import com.autentia.intra.dao.search.ProjectSearch;
import com.autentia.intra.util.SpringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.util.List;


public class ProjectManager {

/* Project - generated by stajanov (do not edit/delete) */


    /**
     * Logger
     */
    private static final Log log = LogFactory.getLog(ProjectManager.class);

    /**
     * Project DAO *
     */
    private ProjectDAO projectDAO;

    /**
     * Get default ProjectManager as defined in Spring's configuration file.
     *
     * @return the default singleton ProjectManager
     */
    public static ProjectManager getDefault() {
        return (ProjectManager) SpringUtils.getSpringBean("managerProject");
    }

    /**
     * Empty constructor needed by CGLIB (Spring AOP)
     */
    protected ProjectManager() {
    }

    /**
     * Default constructor
     *
     * @deprecated do not construct managers alone: use Spring's declared beans
     */
    public ProjectManager(ProjectDAO projectDAO) {
        this.projectDAO = projectDAO;
    }

    /**
     * List projects.
     *
     * @param search search filter to apply
     * @param sort   sorting criteria
     * @return the list of all projects sorted by requested criterion
     */
    public List<Project> getAllEntities(ProjectSearch search, SortCriteria sort) {
        return projectDAO.search(search, sort);
    }

    /**
     * Get project by primary key.
     *
     * @return project selected by id.
     */
    public Project getEntityById(int id) {
        return projectDAO.getById(id);
    }

    /**
     * Insert project.
     */
    public void insertEntity(Project project) {
        projectDAO.insert(project);
    }

    /**
     * Update project.
     */
    public void updateEntity(Project project) {
        projectDAO.update(project);
    }

    /**
     * Delete project.
     */
    public void deleteEntity(Project project) {
        projectDAO.delete(project);
    }

/* Project - generated by stajanov (do not edit/delete) */

    public List<Project> getOpenProjects(SortCriteria sort) {
        ProjectSearch s = new ProjectSearch();
        s.setOpen(true);
        return getAllEntities(s, sort);
    }


    public List<Project> getOpenProjectsByOrganization(Organization org) {
        return projectDAO.searchOpenByOrganization(new SortCriteria("referenciaLaboratorio"), org);
    }

    public List<Project> getProjectsByOrganization(Organization org) {
        return projectDAO.searchByOrganization(new SortCriteria("referenciaLaboratorio"), org);
    }

    public Offer copyFromOffer(Integer id) {
        Offer oferta = OfferDAO.getDefault().getById(id);
        return oferta;
    }


}
