/* 
 *  TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 */


package com.autentia.intra.manager.admin;

import com.autentia.intra.businessobject.ProjectRole;
import com.autentia.intra.dao.SortCriteria;
import com.autentia.intra.dao.hibernate.ProjectRoleDAO;
import com.autentia.intra.dao.search.ProjectRoleSearch;
import com.autentia.intra.util.SpringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.util.List;


public class ProjectRoleManager {
/* generated by stajanov (do not edit/delete) */


    /**
     * Logger
     */
    private static final Log log = LogFactory.getLog(ProjectRoleManager.class);

    /**
     * ProjectRole DAO *
     */
    private ProjectRoleDAO projectRoleDAO;

    /**
     * Get default ProjectRoleManager as defined in Spring's configuration file.
     *
     * @return the default singleton ProjectRoleManager
     */
    public static ProjectRoleManager getDefault() {
        return (ProjectRoleManager) SpringUtils.getSpringBean("managerProjectRole");
    }

    /**
     * Empty constructor needed by CGLIB (Spring AOP)
     */
    protected ProjectRoleManager() {
    }

    /**
     * Default constructor
     *
     * @deprecated do not construct managers alone: use Spring's declared beans
     */
    public ProjectRoleManager(ProjectRoleDAO projectRoleDAO) {
        this.projectRoleDAO = projectRoleDAO;
    }

    /**
     * List projectRoles.
     *
     * @param search search filter to apply
     * @param sort   sorting criteria
     * @return the list of all projectRoles sorted by requested criterion
     */
    public List<ProjectRole> getAllEntities(ProjectRoleSearch search, SortCriteria sort) {
        return projectRoleDAO.search(search, sort);
    }

    /**
     * Get projectRole by primary key.
     *
     * @return projectRole selected by id.
     */
    public ProjectRole getEntityById(int id) {
        return projectRoleDAO.getById(id);
    }

    /**
     * Insert projectRole.
     */
    public void insertEntity(ProjectRole projectRole) {
        projectRoleDAO.insert(projectRole);
    }

    /**
     * Update projectRole.
     */
    public void updateEntity(ProjectRole projectRole) {
        projectRoleDAO.update(projectRole);
    }

    /**
     * Delete projectRole.
     */
    public void deleteEntity(ProjectRole projectRole) {
        projectRoleDAO.delete(projectRole);
    }
/* generated by stajanov (do not edit/delete) */
}
