<%-- project - generated by stajanov (do not edit/delete) --%>


<%--
* TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
*	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.
*
* 	This program is free software; you can redistribute it and/or
* 	modify it under the terms of the GNU General Public License
* 	as published by the Free Software Foundation; either version 2
* 	of the License, or (at your option) any later version.
*
* 	This program is distributed in the hope that it will be useful,
* 	but WITHOUT ANY WARRANTY; without even the implied warranty of
* 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* 	GNU General Public License for more details.
*
* 	You should have received a copy of the GNU General Public License
* 	along with this program; if not, write to the Free Software
* 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*
* 	Autentia Real Bussiness Solution S.L.
* 	Tlf: +34 91 675 33 06, +34 655 99 11 72
* 	Fax: +34 91 656 65 04
* 	info@autentia.com
*
--%>

<%@page language="java" contentType="text/html; charset=UTF-8" %>

<%@include file="/inc/tlibs.jsp" %>

<html>
<head>
    <%@include file="/inc/uiCore.jsp" %>
</head>
<body>

<!-- editProject.jsp: generated by stajanov code generator -->
<f:loadBundle basename="com.autentia.intra.resources.messages" var="msg"/>
<i:location place="detailProject" msg="${msg}"/>

<f:view>
<%@include file="/inc/header.jsp" %>
<h:form id="project" enctype="multipart/form-data">

<%-- Header --%>
<i:titleBar name="${projectBean.name}" msg="${msg}">
    <t:commandLink action="#{projectBean.edit}" immediate="true" rendered="#{projectBean.editAvailable}">
        <f:param name="id" value="#{projectBean.id}"/>
        <h:graphicImage title="#{msg.entityActions_edit}" value="/img/edit.gif" styleClass="cmdImg"/>
    </t:commandLink>
    <h:commandLink action="#{projectBean.delete}" rendered="#{projectBean.deleteAvailable}"
                   onclick="if( !confirm('#{msg['question.confirmDelete']}') ) return false;">
        <h:graphicImage title="#{msg.entityActions_delete}" value="/img/delete.gif" styleClass="titleImg"/>
    </h:commandLink>
    <h:commandLink action="#{projectBean.list}" immediate="true">
        <h:graphicImage title="#{msg.entityActions_back}" value="/img/back.gif" styleClass="titleImg"/>
    </h:commandLink>
    <h:commandLink action="#" title="Generar informe Empresa PDF"
                   onclick="openReportParameters('document/#{projectBean.project.plantilla}.pdf','?projectId='+#{projectBean.id},'');"
                   immediate="true" rendered="#{projectBean.id != null}">
        <h:graphicImage value="/img/document.png" styleClass="titleImg"/>
    </h:commandLink>

    <h:commandLink action="#" title="Generar informe Laboratorio PDF"
                   onclick="openReportParameters('document/#{projectBean.project.plantillaLab}.pdf','?projectId='+#{projectBean.id},'');"
                   immediate="true" rendered="#{projectBean.id != null}">
        <h:graphicImage value="/img/document.png" styleClass="titleImg"/>
    </h:commandLink>
</i:titleBar>


<%-- Detail form --%>
<table class="detailTable" cellpadding="0" cellspacing="0">


    <%-- Ignored field: id --%>


    <%-- Field: startDate --%>
<tr>
    <td class="detailLabelRW">${msg['project.startDate']}:</td>
    <td class="detailFieldCell">
        <h:outputText value="#{projectBean.startDate}" converter="autentia.dateConverter"/>
    </td>
</tr>

    <%-- Field: referenciaCliente --%>
<tr>
    <td class="detailLabelRW">${msg['project.referenciaCliente']}:</td>
    <td class="detailFieldCell">
        <h:outputText value="#{projectBean.project.referenciaCliente}"/>
    </td>
</tr>

    <%-- Field: referenciasCliente --%>
<tr>
    <td class="detailLabelRW">${msg['project.referenciasCliente']}:</td>
    <td class="detailFieldCell">
        <%@include file="inlineDetailProjectIdentification.jsp" %>
    </td>
</tr>

    <%-- Field: referenciaLaboratorio --%>
<tr>
    <td class="detailLabelRW">${msg['project.referenciaLaboratorio']}:</td>
    <td class="detailFieldCell">
        <h:outputText value="#{projectBean.project.referenciaLaboratorio}"/>
    </td>
</tr>

    <%-- Field: especificacion --%>
<tr>
    <td class="detailLabelRW">${msg['project.especificacion']}:</td>
    <td class="detailFieldCell">
        <h:outputText value="#{projectBean.project.especificacion}"/>
    </td>
</tr>

    <%-- Field: descripcion --%>
<tr>
    <td class="detailLabelRW">${msg['project.descripcion']}:</td>
    <td class="detailFieldCell">
        <h:outputText value="#{projectBean.project.descripcion}"/>
    </td>
</tr>


    <%-- Field: open --%>
<tr>
    <td class="detailLabelRW">${msg['project.closed']}:</td>
    <td class="detailFieldCell">
        <h:outputText value="#{projectBean.project.finished}"/>
    </td>
</tr>

    <%-- Field: billable --%>
<tr>
    <td class="detailLabelRW">${msg['project.billable']}:</td>
    <td class="detailFieldCell">
        <h:outputText value="#{projectBean.billable}"/>
    </td>
</tr>

    <%-- Field: orderNumber --%>
<tr>
    <td class="detailLabelRW">${msg['bill.orderNumber']}:</td>
    <td class="detailFieldCell">
        <h:outputText value="#{projectBean.project.orderNumber}"/>
    </td>
</tr>


    <%-- Field: name --%>
<tr>
    <td class="detailLabelRW">${msg['project.name']}:</td>
    <td class="detailFieldCell">
        <h:outputText value="#{projectBean.name}"/>
    </td>
</tr>

    <%-- Field: titulo --%>
<tr>
    <td class="detailLabelRW">${msg['project.titulo']}:</td>
    <td class="detailFieldCell">
        <h:outputText value="#{projectBean.project.titulo}"/>
    </td>
</tr>


    <%-- Field: description --%>
<tr>
    <td class="detailLabelRW">${msg['project.description']}:</td>
    <td class="detailFieldCell">
        <h:outputText value="#{projectBean.description}"/>
    </td>
</tr>


    <%-- Ignored field: ownerId --%>


    <%-- Ignored field: departmentId --%>


    <%-- Ignored field: insertDate --%>


    <%-- Ignored field: updateDate --%>


    <%-- Field: client --%>
<tr>
    <td class="detailLabelRW">${msg['project.client']}:</td>
    <td class="detailFieldCell">
        <h:outputText value="#{projectBean.client.name}"/>
    </td>
</tr>


    <%-- Field: ensayosSolicitados --%>
<tr>
    <td class="detailLabelRW">${msg['project.ensayosSolicitados']}:</td>
    <td class="detailFieldCell">
        <h:outputText value="#{projectBean.project.ensayosSolicitados}"/>
    </td>
</tr>

    <%-- Field: estadoDeRecepcion --%>
<tr>
    <td class="detailLabelRW">${msg['project.estadoDeRecepcion']}:</td>
    <td class="detailFieldCell">
        <h:outputText value="#{projectBean.project.estadoDeRecepcion}"/>
    </td>
</tr>

    <%-- Field: roles --%>
<tr>
    <td class="detailLabelRW">${msg['project.roles']}:</td>
    <td class="detailFieldCell">
        <%@include file="inlineDetailProjectRole.jsp" %>
    </td>
</tr>


    <%-- Field: ensayos --%>
<tr>
    <td class="detailLabelRW">${msg['project.ensayos']}:</td>
    <td class="detailFieldCell">
        <%@include file="inlineDetailProjectEnsayo.jsp" %>
    </td>
</tr>


    <%-- Field: costs --%>
<tr>
    <td class="detailLabelRW">${msg['project.costs']}:</td>
    <td class="detailFieldCell">
        <%@include file="inlineDetailProjectCost.jsp" %>
    </td>
</tr>

    <%-- Field: costeAFacturar --%>
<tr>
    <td class="detailLabelRW">${msg['project.costeAFacturar']}:</td>
    <td class="detailFieldCell">
        <h:outputText value="#{projectBean.project.costeAFacturar}">
            <f:convertNumber pattern="#,##0.00"/>

        </h:outputText>
    </td>
</tr>


    <%-- Field: recibidoPor --%>
<tr>
    <td class="detailLabelRW">${msg['project.recibidoPor']}:</td>
    <td class="detailFieldCell">
        <h:outputText value="#{projectBean.project.recibidoPor.name}"/>
    </td>
</tr>

    <%-- Field: supervisadoPor --%>
<tr>
    <td class="detailLabelRW">${msg['project.supervisadoPor']}:</td>
    <td class="detailFieldCell">
        <h:outputText value="#{projectBean.project.supervisadoPor.name}"/>
    </td>
</tr>

    <%-- Field: realizadoPor --%>
<tr>
    <td class="detailLabelRW">${msg['project.realizadoPor']}:</td>
    <td class="detailFieldCell">
        <h:outputText value="#{projectBean.project.realizadoPor.name}"/>
    </td>
</tr>

    <%-- Field: recibidoFecha --%>
<tr>
    <td class="detailLabelRW">${msg['project.recibidoFecha']}:</td>
    <td class="detailFieldCell">
        <h:outputText value="#{projectBean.project.recibidoFecha}" converter="autentia.dateConverter"/>
    </td>
</tr>

    <%-- Field: endDate --%>
<tr>
    <td class="detailLabelRW">${msg['project.endDate']}:</td>
    <td class="detailFieldCell">
        <h:outputText value="#{projectBean.endDate}" converter="autentia.dateConverter"/>
    </td>
</tr>

    <%-- Field: observaciones --%>
<tr>
    <td class="detailLabelRW">${msg['project.observaciones']}:</td>
    <td class="detailFieldCell">
        <h:outputText value="#{projectBean.project.observaciones}"/>
    </td>
</tr>

    <%-- Field: motivoDevolucion --%>
<tr>
    <td class="detailLabelRW">${msg['project.motivoDevolucion']}:</td>
    <td class="detailFieldCell">
        <h:outputText value="#{projectBean.project.motivoDevolucion}"/>
    </td>
</tr>

    <%-- Field: numMuestras --%>
<tr>
    <td class="detailLabelRW">${msg['project.numMuestras']}:</td>
    <td class="detailFieldCell">
        <h:outputText value="#{projectBean.project.numMuestras}"/>
    </td>
</tr>

    <%-- Field: plantilla --%>
<tr>
    <td class="detailLabelRW">${msg['project.plantilla']}:</td>
    <td class="detailFieldCell">
        <h:outputText value="#{projectBean.project.plantilla}"/>
    </td>
</tr>

    <%-- Field: plantillaLab --%>
<tr>
    <td class="detailLabelRW">${msg['project.plantillaLab']}:</td>
    <td class="detailFieldCell">
        <h:outputText value="#{projectBean.project.plantillaLab}"/>
    </td>
</tr>


</table>

</h:form>
</f:view>

</body>
</html>

<%-- project - generated by stajanov (do not edit/delete) --%>
