<%-- 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 *
 --%>

<%@page language="java" contentType="text/html; charset=UTF-8" %>

<%@include file="/inc/tlibs.jsp" %>

<html>
<head>
    <%@include file="/inc/uiCore.jsp" %>
</head>
<body>

<!-- editProject.jsp: generated by stajanov code generator -->
<f:loadBundle basename="com.autentia.intra.resources.messages" var="msg"/>
<i:location place="editProjectEnsayo" msg="${msg}"/>

<f:view>
<%@include file="/inc/header.jsp" %>
<h:form id="projectEnsayo" enctype="multipart/form-data">

<%-- Header --%>
<i:titleBar name="${projectEnsayoBean.name}" msg="${msg}">
    <h:commandLink action="#{projectEnsayoBean.save}"
                   onclick="if(!askSave('#{projectEnsayoBean.id}','#{msg['question.confirmSave']}')) return false;">
        <h:graphicImage value="/img/save.gif" styleClass="titleImg"/>
    </h:commandLink>

    <h:commandLink action="#{projectBean.detail}" immediate="true">
        <f:param name="id" value="#{projectEnsayoBean.projectEnsayo.project.id}"/>
        <h:graphicImage value="/img/back.gif" styleClass="titleImg"/>
    </h:commandLink>

    <h:commandLink action="#" title="Generar informe Laboratorio PDF"
                   onclick="openReportParameters('document/#{projectEnsayoBean.projectEnsayo.plantilla}.pdf','?projectEnsayoId='+#{projectEnsayoBean.id},'');"
                   immediate="true">
        <h:graphicImage value="/img/document.png" styleClass="titleImg"/>
    </h:commandLink>


</i:titleBar>

<%-- Edition form --%>
<table class="editTable" cellpadding="0" cellspacing="0">

    <%-- Ignored field: id --%>


<tr>
    <td class="editLabelRW">${msg['projectEnsayo.identificacionCliente']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="identificacionCliente"/>
            <h:inputText id="identificacionCliente" value="#{projectEnsayoBean.projectEnsayo.identificacionCliente}"
                         size="70"/>
        </h:panelGroup>
    </td>
</tr>


<tr>
    <td class="editLabelRW">${msg['project.referenciasCliente']}:</td>
    <td class="editFieldCell">
        <%@include file="inlineEditProjectEnsayoIdentification.jsp" %>
    </td>
</tr>


<tr>
    <td class="editLabelRW">${msg['projectEnsayo.identificacionLab']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="identificacionLab"/>
            <h:inputText id="identificacionLab" value="#{projectEnsayoBean.projectEnsayo.identificacionLab}" size="70"/>
        </h:panelGroup>
    </td>
</tr>


<tr>
    <td class="editLabelRW">${msg['projectEnsayo.idTitMatEns']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="idTitMatEns"/>
            <h:inputText id="idTitMatEns" value="#{projectEnsayoBean.projectEnsayo.idTitMatEns}" size="70"/>
        </h:panelGroup>
    </td>
</tr>


<tr>
    <td class="editLabelRW">${msg['projectEnsayo.fechaRecepcionMuestra']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="fechaRecepcionMuestra"/>
            <t:inputCalendar id="fechaRecepcionMuestra" value="#{projectEnsayoBean.projectEnsayo.fechaRecepcionMuestra}"
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true"
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                    />
        </h:panelGroup>
    </td>
</tr>


<tr>
    <td class="editLabelRW">${msg['projectEnsayo.procedimiento']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="procedimiento"/>
            <h:inputText id="procedimiento" value="#{projectEnsayoBean.procedimiento}" size="70"/>
        </h:panelGroup>
    </td>
</tr>

<tr>
    <td class="editLabelRW">${msg['projectEnsayo.requerimiento']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="requerimiento"/>
            <h:inputText id="requerimiento" value="#{projectEnsayoBean.requerimiento}" size="70"/>
        </h:panelGroup>
    </td>
</tr>


<tr>
    <td class="editLabelRW">${msg['projectEnsayo.valor']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="valor"/>
            <h:inputText id="valor" value="#{projectEnsayoBean.valor}" size="70"/>
        </h:panelGroup>
    </td>
</tr>


<tr>
    <td class="editLabelRW">${msg['projectEnsayo.conformidad']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="conformidad"/>
            <h:inputText id="conformidad" value="#{projectEnsayoBean.conformidad}" size="70"/>
        </h:panelGroup>
    </td>
</tr>


<tr>
    <td class="editLabelRW">${msg['projectEnsayo.dimensiones']}:</td>
    <td class="editFieldCell">
        <%@include file="inlineEditProjectEnsayoDimension.jsp" %>
    </td>
</tr>


<tr>
    <td class="editLabelRW">${msg['projectEnsayo.requerimientos']}:</td>

    <td class="editFieldCell">

        <%@include file="inlineEditProjectEnsayoRequerimiento.jsp" %>

    </td>
</tr>


<tr>
    <td class="editLabelRW">${msg['projectEnsayo.observaciones']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="observaciones"/>
            <h:inputTextarea id="observaciones" value="#{projectEnsayoBean.projectEnsayo.observaciones}" rows="5"
                             cols="68"/>
        </h:panelGroup>
    </td>
</tr>

    <%-- Field: photo --%>
<tr>
    <td class="editLabelRW">${msg['projectEnsayo.photo']}:</td>

    <td class="editFieldCell">
        <h:commandLink action="#{projectEnsayoBean.deleteFile}" immediate="true"
                       rendered="#{projectEnsayoBean.projectEnsayo.photo != null}">
            <h:graphicImage title="#{msg.entityActions_delete}" value="/img/delete.gif"
                            styleClass="titleImg"/>
        </h:commandLink>
        <i:fileLink type="projectEnsayo" objectId="${projectEnsayoBean.id}"
                    file="${projectEnsayoBean.projectEnsayo.photo}"/>
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="photo"/>
            <t:inputFileUpload id="photo" size="58" value="#{projectEnsayoBean.uploadPhoto}" storage="file"/>
        </h:panelGroup>

    </td>
</tr>

<tr>
    <td class="editLabelRW">${msg['projectEnsayo.realizadoPor']}:</td>

    <td class="editFieldCell">

        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="realizadoPor"/>
            <h:selectOneMenu id="realizadoPor" value="#{projectEnsayoBean.projectEnsayo.realizadoPor}">
                <f:selectItems value="#{projectEnsayoBean.users}"/>
                <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
        </h:panelGroup>

    </td>
</tr>


<tr>
    <td class="editLabelRW">${msg['projectEnsayo.realizadoFecha']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="realizadoFecha"/>
            <t:inputCalendar id="realizadoFecha" value="#{projectEnsayoBean.projectEnsayo.realizadoFecha}"
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true"
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                    />
        </h:panelGroup>
    </td>
</tr>


<tr>
    <td class="editLabelRW">${msg['projectEnsayo.revisadoPor']}:</td>

    <td class="editFieldCell">

        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="revisadoPor"/>
            <h:selectOneMenu id="revisadoPor" value="#{projectEnsayoBean.projectEnsayo.revisadoPor}">
                <f:selectItems value="#{projectEnsayoBean.users}"/>
                <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
        </h:panelGroup>

    </td>
</tr>


<tr>
    <td class="editLabelRW">${msg['projectEnsayo.revisadoFecha']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="revisadoFecha"/>
            <t:inputCalendar id="revisadoFecha" value="#{projectEnsayoBean.projectEnsayo.revisadoFecha}"
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true"
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                    />
        </h:panelGroup>
    </td>
</tr>


<tr>
    <td class="editLabelRW">${msg['projectEnsayo.aprobadoPor']}:</td>

    <td class="editFieldCell">

        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="aprobadoPor"/>
            <h:selectOneMenu id="aprobadoPor" value="#{projectEnsayoBean.projectEnsayo.aprobadoPor}">
                <f:selectItems value="#{projectEnsayoBean.users}"/>
                <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
        </h:panelGroup>

    </td>
</tr>


<tr>
    <td class="editLabelRW">${msg['projectEnsayo.aprobadoFecha']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="aprobadoFecha"/>
            <t:inputCalendar id="aprobadoFecha" value="#{projectEnsayoBean.projectEnsayo.aprobadoFecha}"
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true"
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                    />
        </h:panelGroup>
    </td>
</tr>


<tr>
    <td class="editLabelRW">${msg['projectEnsayo.plantilla']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="plantilla"/>
            <h:inputText id="plantilla" value="#{projectEnsayoBean.projectEnsayo.plantilla}" maxlength="128"/>
        </h:panelGroup>
    </td>
</tr>

<tr>
    <td class="editLabelRW">${msg['projectEnsayo.plantillaTit']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="plantillaTit"/>
            <h:inputText id="plantillaTit" value="#{projectEnsayoBean.projectEnsayo.plantillaTit}" maxlength="128"/>
        </h:panelGroup>
    </td>
</tr>

<tr>
    <td class="editLabelRW">${msg['projectEnsayo.plantillaLab']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="plantillaLab"/>
            <h:inputText id="plantillaLab" value="#{projectEnsayoBean.projectEnsayo.plantillaLab}" maxlength="128"/>
        </h:panelGroup>
    </td>
</tr>

<tr>
    <td class="editLabelRW">${msg['projectEnsayo.plantillaReq']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="plantillaReq"/>
            <h:inputText id="plantillaReq" value="#{projectEnsayoBean.projectEnsayo.plantillaReq}" maxlength="128"/>
        </h:panelGroup>
    </td>
</tr>

<tr>
    <td class="editLabelRW">${msg['projectEnsayo.plantillaDim']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="plantillaDim"/>
            <h:inputText id="plantillaDim" value="#{projectEnsayoBean.projectEnsayo.plantillaDim}" maxlength="128"/>
        </h:panelGroup>
    </td>
</tr>


</table>

<h:commandLink action="#{historicoBean.ver_historico}" immediate="true" target="_blank"
               rendered="#{projectEnsayoBean.id != null}">
    <f:param name="idObjeto" value="#{projectEnsayoBean.id}"/>
    <f:param name="klazz" value="#{projectEnsayoBean.projectEnsayo.class.name}"/>
    <h:graphicImage value="/img/historico.png" styleClass="titleImg"/>
</h:commandLink>

</h:form>
</f:view>

</body>
</html>  		

