<%-- 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 *
 --%>

<%@page language="java" contentType="text/html; charset=UTF-8" %>

<%@include file="/inc/tlibs.jsp" %>

<html>
<head>
    <%@include file="/inc/uiCore.jsp" %>
</head>
<body>

<!-- editProject.jsp: generated by stajanov code generator -->
<f:loadBundle basename="com.autentia.intra.resources.messages" var="msg"/>
<i:location place="editProject" msg="${msg}"/>

<f:view>
<%@include file="/inc/header.jsp" %>
<h:form id="project" enctype="multipart/form-data">

<%-- Header --%>
<i:titleBar name="${projectBean.name}" msg="${msg}">
    <h:commandLink action="#{projectBean.save}"
                   onclick="if(!askSave('#{projectBean.id}','#{msg['question.confirmSave']}')) return false;">
        <h:graphicImage value="/img/save.gif" styleClass="titleImg"/>
    </h:commandLink>
    <h:commandLink action="#{projectBean.delete}"
                   onclick="if( !confirm('#{msg['question.confirmDelete']}') ) return false;">
        <h:graphicImage value="/img/delete.gif" styleClass="titleImg"/>
    </h:commandLink>
    <h:commandLink action="#{projectBean.list}" immediate="true">
        <h:graphicImage value="/img/back.gif" styleClass="titleImg"/>
    </h:commandLink>
    <h:commandLink action="#" title="Generar informe Empresa PDF"
                   onclick="openReportParameters('document/#{projectBean.project.plantilla}.pdf','?projectId='+#{projectBean.id},'');"
                   immediate="true" rendered="#{projectBean.id != null}">
        <h:graphicImage value="/img/document.png" styleClass="titleImg"/>
    </h:commandLink>

    <h:commandLink action="#" title="Generar informe Laboratorio PDF"
                   onclick="openReportParameters('document/#{projectBean.project.plantillaLab}.pdf','?projectId='+#{projectBean.id},'');"
                   immediate="true" rendered="#{projectBean.id != null}">
        <h:graphicImage value="/img/document.png" styleClass="titleImg"/>
    </h:commandLink>

</i:titleBar>

<%-- Edition form --%>
<table class="editTable" cellpadding="0" cellspacing="0">

    <%-- Ignored field: id --%>

    <%-- Field: startDate --%>
<tr>
    <td class="editLabelRW">*${msg['project.startDate']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="startDate"/>
            <t:inputCalendar id="startDate" value="#{projectBean.startDate}"
                             required="true" styleClass="requiredFieldClass"
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true"
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                    />
        </h:panelGroup>
    </td>
</tr>


<tr>
    <td class="editLabelRW">*${msg['project.referenciaCliente']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="referenciaCliente"/>
            <h:inputText id="referenciaCliente" value="#{projectBean.project.referenciaCliente}" maxlength="64"
                         size="64" required="true" styleClass="requiredFieldClass"/>
        </h:panelGroup>
    </td>
</tr>

    <%-- Field: roles --%>
<tr>
    <td class="editLabelRW">${msg['project.referenciasCliente']}:</td>
    <td class="editFieldCell">
        <%@include file="inlineEditProjectIdentification.jsp" %>
    </td>
</tr>

<tr>
    <td class="editLabelRW">${msg['project.referenciaLaboratorio']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="referenciaLaboratorio"/>
            <h:inputText id="referenciaLaboratorio" value="#{projectBean.siguienteRefLab}" maxlength="64" size="64"
                         validator="#{projectBean.referenciaLaboratorioValidate}"/>
        </h:panelGroup>
    </td>
</tr>

<tr>
    <td class="editLabelRW">${msg['project.estado']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:outputText value="#{projectBean.estadoFormatted}"/>
            <h:outputText value=": "
                          rendered="#{projectBean.project.albaran != null or projectBean.project.albaran.bill != null}"/>
            <t:commandLink action="#{albaranBean.detail_desde_fuera}" immediate="true" styleClass="enlaceAzul"
                           rendered="#{projectBean.project.albaran != null}">
                <f:param name="id" value="#{projectBean.project.albaran.id}"/>
                <h:outputText value="#{projectBean.project.albaran.name}"/>
            </t:commandLink>
            <h:outputText value=", "
                          rendered="#{projectBean.project.albaran != null and projectBean.project.albaran.bill != null}"/>
            <t:commandLink action="#{billBean.detail_desde_fuera}" immediate="true" styleClass="enlaceAzul"
                           rendered="#{projectBean.project.albaran.bill != null}">
                <f:param name="id" value="#{projectBean.project.albaran.bill.id}"/>
                <h:outputText value="#{projectBean.project.albaran.bill.number}"/>
            </t:commandLink>
        </h:panelGroup>
    </td>
</tr>

<tr>
    <td class="editLabelRW">${msg['project.especificacion']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="especificacion"/>
            <h:inputText id="especificacion" value="#{projectBean.project.especificacion}" maxlength="64" size="64"/>
        </h:panelGroup>
    </td>
</tr>


<tr>
    <td class="editLabelRW">${msg['project.descripcion']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="descripcion"/>
            <h:inputText id="descripcion" value="#{projectBean.project.descripcion}" maxlength="64" size="64"/>
        </h:panelGroup>
    </td>
</tr>


    <%-- Field: open --%>
<tr>
    <td class="editLabelRW">${msg['project.closed']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="open"/>
            <h:selectBooleanCheckbox id="open" value="#{projectBean.closed}"/>
        </h:panelGroup>
    </td>
</tr>

    <%-- Field: billable --%>
<tr>
    <td class="editLabelRW">${msg['project.billable']}:</td>

    <td class="editFieldCell">

        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="billable"/>
            <h:selectBooleanCheckbox id="billable" value="#{projectBean.billable}"/>
        </h:panelGroup>

    </td>
</tr>

    <%-- Field: orderNumber --%>
<tr>
    <td class="editLabelRW">${msg['bill.orderNumber']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="orderNumber"/>
            <h:inputText id="orderNumber" value="#{projectBean.orderNumber}" maxlength="64"/>
        </h:panelGroup>
    </td>
</tr>

    <%-- Field: name --%>
<tr>
    <td class="editLabelRW">*${msg['project.name']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="name"/>
            <h:inputText id="name" value="#{projectBean.name}" size="70" maxlength="128" required="true"
                         styleClass="requiredFieldClass"/>
        </h:panelGroup>
    </td>
</tr>

<tr>
    <td class="editLabelRW">${msg['project.titulo']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="titulo"/>
            <h:inputText id="titulo" value="#{projectBean.project.titulo}" size="70" maxlength="255"/>
        </h:panelGroup>
    </td>
</tr>

    <%-- Field: description --%>
<tr>
    <td class="editLabelRW">${msg['project.description']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="description"/>
            <h:inputTextarea id="description" value="#{projectBean.description}" rows="5" cols="68"/>
        </h:panelGroup>
    </td>
</tr>

    <%-- Field: client --%>
<tr>
    <td class="editLabelRW">*${msg['project.client']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="client"/>
            <h:selectOneMenu id="client" value="#{projectBean.client}" required="true" styleClass="requiredFieldClass">
                <f:selectItems value="#{projectBean.clients}"/>
                <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
        </h:panelGroup>
    </td>
</tr>

    <%-- Field: ensayosSolicitados --%>
<tr>
    <td class="editLabelRW">${msg['project.ensayosSolicitados']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="ensayosSolicitados"/>
            <h:inputTextarea id="ensayosSolicitados" value="#{projectBean.ensayosSolicitados}" rows="5" cols="68"/>
        </h:panelGroup>
    </td>
</tr>

    <%-- Field: estadoDeRecepcion --%>
<tr>
    <td class="editLabelRW">${msg['project.estadoDeRecepcion']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="estadoDeRecepcion"/>
            <h:inputTextarea id="estadoDeRecepcion" value="#{projectBean.project.estadoDeRecepcion}" rows="5"
                             cols="68"/>
        </h:panelGroup>
    </td>
</tr>

    <%-- Field: roles --%>
<tr>
    <td class="editLabelRW">${msg['project.roles']}:</td>
    <td class="editFieldCell">
        <%@include file="inlineEditProjectRole.jsp" %>
    </td>
</tr>

    <%-- Field: ensayos --%>
<tr>
    <td class="editLabelRW">${msg['project.ensayos']}:</td>

    <td class="editFieldCell">

        <%@include file="inlineEditProjectEnsayo.jsp" %>

    </td>
</tr>

    <%-- Field: costs --%>
<tr>
    <td class="editLabelRW">${msg['project.costs']}:</td>
    <td class="editFieldCell">
        <%@include file="inlineEditProjectCost.jsp" %>
    </td>
</tr>

<tr>
    <td class="editLabelRW">${msg['project.costeAFacturar']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="costeAFacturar"/>
            <h:inputText id="costeAFacturar" value="#{projectBean.project.costeAFacturar}" maxlength="64"/>
        </h:panelGroup>
        La suma de tareas, ensayos y costes es:
        <h:outputText value="#{projectBean.project.totalCost}">
            <f:convertNumber pattern="#,##0.00"/>
        </h:outputText> €
    </td>
</tr>


<tr>
    <td class="editLabelRW">${msg['project.recibidoPor']}:</td>

    <td class="editFieldCell">

        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="recibidoPor"/>
            <h:selectOneMenu id="recibidoPor" value="#{projectBean.project.recibidoPor}">
                <f:selectItems value="#{projectBean.users}"/>
                <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
        </h:panelGroup>

    </td>
</tr>


<tr>
    <td class="editLabelRW">${msg['project.supervisadoPor']}:</td>

    <td class="editFieldCell">

        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="supervisadoPor"/>
            <h:selectOneMenu id="supervisadoPor" value="#{projectBean.project.supervisadoPor}">
                <f:selectItems value="#{projectBean.users}"/>
                <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
        </h:panelGroup>

    </td>
</tr>


<tr>
    <td class="editLabelRW">${msg['project.realizadoPor']}:</td>

    <td class="editFieldCell">

        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="realizadoPor"/>
            <h:selectOneMenu id="realizadoPor" value="#{projectBean.project.realizadoPor}">
                <f:selectItems value="#{projectBean.users}"/>
                <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
        </h:panelGroup>

    </td>
</tr>

<tr>
    <td class="editLabelRW">${msg['project.realizadoFecha']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="realizadoFecha"/>
            <t:inputCalendar id="realizadoFecha" value="#{projectBean.project.realizadoFecha}"
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true"
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                    />
        </h:panelGroup>
    </td>
</tr>

    <%-- Field: endDate --%>
<tr>
    <td class="editLabelRW">${msg['project.endDate']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="endDate"/>
            <t:inputCalendar id="endDate" value="#{projectBean.endDate}"
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true"
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                    />
        </h:panelGroup>
    </td>
</tr>


<tr>
    <td class="editLabelRW">${msg['project.observaciones']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="observaciones"/>
            <h:inputTextarea id="observaciones" value="#{projectBean.project.observaciones}" rows="5" cols="68"/>
        </h:panelGroup>
    </td>
</tr>


<tr>
    <td class="editLabelRW">${msg['project.motivoDevolucion']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="motivoDevolucion"/>
            <h:inputText id="motivoDevolucion" value="#{projectBean.project.motivoDevolucion}" size="128"
                         maxlength="256"/>
        </h:panelGroup>
    </td>
</tr>


<tr>
    <td class="editLabelRW">${msg['project.numMuestras']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="numMuestras"/>
            <h:inputText id="numMuestras" value="#{projectBean.project.numMuestras}" maxlength="64"/>
        </h:panelGroup>
    </td>
</tr>


<tr>
    <td class="editLabelRW">${msg['project.plantilla']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="plantilla"/>
            <h:inputText id="plantilla" value="#{projectBean.project.plantilla}" maxlength="128"/>
        </h:panelGroup>
    </td>
</tr>

<tr>
    <td class="editLabelRW">${msg['project.plantillaLab']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="plantillaLab"/>
            <h:inputText id="plantillaLab" value="#{projectBean.project.plantillaLab}" maxlength="128"/>
        </h:panelGroup>
    </td>
</tr>

<tr>
    <td class="editLabelRW">${msg['project.tiempoRespuesta']}:</td>
    <td class="editFieldCell">
        <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="tiempoRespuesta"/>
            <h:inputText id="tiempoRespuesta" value="#{projectBean.project.tiempoRespuesta}" maxlength="64"/>
        </h:panelGroup>
        días
    </td>
</tr>

</table>

<h:commandLink action="#{historicoBean.ver_historico}" immediate="true" target="_blank"
               rendered="#{projectBean.id != null}">
    <f:param name="idObjeto" value="#{projectBean.id}"/>
    <f:param name="klazz" value="#{projectBean.project.class.name}"/>
    <h:graphicImage value="/img/historico.png" styleClass="titleImg"/>
</h:commandLink>

</h:form>
</f:view>

</body>
</html>  		

