/* 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 */


package com.autentia.intra.manager.contacts;

import com.autentia.intra.businessobject.Albaran;
import com.autentia.intra.dao.SortCriteria;
import com.autentia.intra.dao.hibernate.AlbaranDAO;
import com.autentia.intra.dao.search.AlbaranSearch;
import com.autentia.intra.util.SpringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.util.List;


public class AlbaranManager {

/* Albaran - generated by stajanov (do not edit/delete) */


    /**
     * Logger
     */
    private static final Log log = LogFactory.getLog(AlbaranManager.class);

    /**
     * Albaran DAO *
     */
    private AlbaranDAO albaranDAO;

    /**
     * Get default AlbaranManager as defined in Spring's configuration file.
     *
     * @return the default singleton AlbaranManager
     */
    public static AlbaranManager getDefault() {
        return (AlbaranManager) SpringUtils.getSpringBean("managerAlbaran");
    }

    /**
     * Empty constructor needed by CGLIB (Spring AOP)
     */
    protected AlbaranManager() {
    }

    /**
     * Default constructor
     *
     * @deprecated do not construct managers alone: use Spring's declared beans
     */
    public AlbaranManager(AlbaranDAO albaranDAO) {
        this.albaranDAO = albaranDAO;
    }

    /**
     * List albarans.
     *
     * @param search search filter to apply
     * @param sort   sorting criteria
     * @return the list of all albarans sorted by requested criterion
     */
    public List<Albaran> getAllEntities(AlbaranSearch search, SortCriteria sort) {
        return albaranDAO.search(search, sort);
    }

    /**
     * Get albaran by primary key.
     *
     * @return albaran selected by id.
     */
    public Albaran getEntityById(int id) {
        return albaranDAO.getById(id);
    }

    /**
     * Insert albaran.
     */
    public void insertEntity(Albaran albaran) {
        albaranDAO.insert(albaran);
    }

    /**
     * Update albaran.
     */
    public void updateEntity(Albaran albaran) {
        albaranDAO.update(albaran);
    }

    /**
     * Delete albaran.
     */
    public void deleteEntity(Albaran albaran) {
        albaranDAO.delete(albaran);
    }

/* Albaran - generated by stajanov (do not edit/delete) */


}
