/* 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 */


package com.autentia.intra.manager.contacts;

import com.autentia.intra.businessobject.Contact;
import com.autentia.intra.dao.SortCriteria;
import com.autentia.intra.dao.hibernate.ContactDAO;
import com.autentia.intra.dao.search.ContactSearch;
import com.autentia.intra.util.SpringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.util.List;


public class ContactManager {

/* contact - generated by stajanov (do not edit/delete) */


    /**
     * Logger
     */
    private static final Log log = LogFactory.getLog(ContactManager.class);

    /**
     * Contact DAO *
     */
    private ContactDAO contactDAO;

    /**
     * Get default ContactManager as defined in Spring's configuration file.
     *
     * @return the default singleton ContactManager
     */
    public static ContactManager getDefault() {
        return (ContactManager) SpringUtils.getSpringBean("managerContact");
    }

    /**
     * Empty constructor needed by CGLIB (Spring AOP)
     */
    protected ContactManager() {
    }

    /**
     * Default constructor
     *
     * @deprecated do not construct managers alone: use Spring's declared beans
     */
    public ContactManager(ContactDAO contactDAO) {
        this.contactDAO = contactDAO;
    }

    /**
     * List contacts.
     *
     * @param search search filter to apply
     * @param sort   sorting criteria
     * @return the list of all contacts sorted by requested criterion
     */
    public List<Contact> getAllEntities(ContactSearch search, SortCriteria sort) {
        return contactDAO.search(search, sort);
    }

    /**
     * Get contact by primary key.
     *
     * @return contact selected by id.
     */
    public Contact getEntityById(int id) {
        return contactDAO.getById(id);
    }

    /**
     * Insert contact.
     */
    public void insertEntity(Contact contact) {
        contactDAO.insert(contact);
    }

    /**
     * Update contact.
     */
    public void updateEntity(Contact contact) {
        contactDAO.update(contact);
    }

    /**
     * Delete contact.
     */
    public void deleteEntity(Contact contact) {
        contactDAO.delete(contact);
    }

/* contact - generated by stajanov (do not edit/delete) */

}
