/* 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 */


package com.autentia.intra.manager.contacts;

import com.autentia.intra.businessobject.EnsayoPrecio;
import com.autentia.intra.dao.SortCriteria;
import com.autentia.intra.dao.hibernate.EnsayoPrecioDAO;
import com.autentia.intra.dao.search.EnsayoPrecioSearch;
import com.autentia.intra.util.SpringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.util.List;


public class EnsayoPrecioManager {

/* generated by stajanov (do not edit/delete) */


    /**
     * Logger
     */
    private static final Log log = LogFactory.getLog(EnsayoPrecioManager.class);

    /**
     * EnsayoPrecio DAO *
     */
    private EnsayoPrecioDAO ensayoPrecioDAO;

    /**
     * Get default EnsayoPrecioManager as defined in Spring's configuration file.
     *
     * @return the default singleton EnsayoPrecioManager
     */
    public static EnsayoPrecioManager getDefault() {
        return (EnsayoPrecioManager) SpringUtils.getSpringBean("managerEnsayoPrecio");
    }

    /**
     * Empty constructor needed by CGLIB (Spring AOP)
     */
    protected EnsayoPrecioManager() {
    }

    /**
     * Default constructor
     *
     * @deprecated do not construct managers alone: use Spring's declared beans
     */
    public EnsayoPrecioManager(EnsayoPrecioDAO ensayoPrecioDAO) {
        this.ensayoPrecioDAO = ensayoPrecioDAO;
    }

    /**
     * List ensayoPrecios.
     *
     * @param search search filter to apply
     * @param sort   sorting criteria
     * @return the list of all ensayoPrecios sorted by requested criterion
     */
    public List<EnsayoPrecio> getAllEntities(EnsayoPrecioSearch search, SortCriteria sort) {
        return ensayoPrecioDAO.search(search, sort);
    }

    /**
     * Get ensayoPrecio by primary key.
     *
     * @return ensayoPrecio selected by id.
     */
    public EnsayoPrecio getEntityById(int id) {
        return ensayoPrecioDAO.getById(id);
    }

    /**
     * Insert ensayoPrecio.
     */
    public void insertEntity(EnsayoPrecio ensayoPrecio) {
        ensayoPrecioDAO.insert(ensayoPrecio);
    }

    /**
     * Update ensayoPrecio.
     */
    public void updateEntity(EnsayoPrecio ensayoPrecio) {
        ensayoPrecioDAO.update(ensayoPrecio);
    }

    /**
     * Delete ensayoPrecio.
     */
    public void deleteEntity(EnsayoPrecio ensayoPrecio) {
        ensayoPrecioDAO.delete(ensayoPrecio);
    }
/* generated by stajanov (do not edit/delete) */
}
