/* 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 */


package com.autentia.intra.manager.contacts;

import com.autentia.intra.businessobject.OfferPauta;
import com.autentia.intra.dao.SortCriteria;
import com.autentia.intra.dao.hibernate.OfferPautaDAO;
import com.autentia.intra.dao.search.OfferPautaSearch;
import com.autentia.intra.util.SpringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.util.List;


public class OfferPautaManager {

/* generated by stajanov (do not edit/delete) */


    /**
     * Logger
     */
    private static final Log log = LogFactory.getLog(OfferPautaManager.class);

    /**
     * OfferPauta DAO *
     */
    private OfferPautaDAO offerPautaDAO;

    /**
     * Get default OfferPautaManager as defined in Spring's configuration file.
     *
     * @return the default singleton OfferPautaManager
     */
    public static OfferPautaManager getDefault() {
        return (OfferPautaManager) SpringUtils.getSpringBean("managerOfferPauta");
    }

    /**
     * Empty constructor needed by CGLIB (Spring AOP)
     */
    protected OfferPautaManager() {
    }

    /**
     * Default constructor
     *
     * @deprecated do not construct managers alone: use Spring's declared beans
     */
    public OfferPautaManager(OfferPautaDAO offerPautaDAO) {
        this.offerPautaDAO = offerPautaDAO;
    }

    /**
     * List offerPautas.
     *
     * @param search search filter to apply
     * @param sort   sorting criteria
     * @return the list of all offerPautas sorted by requested criterion
     */
    public List<OfferPauta> getAllEntities(OfferPautaSearch search, SortCriteria sort) {
        return offerPautaDAO.search(search, sort);
    }

    /**
     * Get offerPauta by primary key.
     *
     * @return offerPauta selected by id.
     */
    public OfferPauta getEntityById(int id) {
        return offerPautaDAO.getById(id);
    }

    /**
     * Insert offerPauta.
     */
    public void insertEntity(OfferPauta offerPauta) {
        offerPautaDAO.insert(offerPauta);
    }

    /**
     * Update offerPauta.
     */
    public void updateEntity(OfferPauta offerPauta) {
        offerPautaDAO.update(offerPauta);
    }

    /**
     * Delete offerPauta.
     */
    public void deleteEntity(OfferPauta offerPauta) {
        offerPautaDAO.delete(offerPauta);
    }
/* generated by stajanov (do not edit/delete) */
}
