/* 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 */


package com.autentia.intra.manager.contacts;

import com.autentia.intra.businessobject.OfferCost;
import com.autentia.intra.dao.SortCriteria;
import com.autentia.intra.dao.hibernate.OfferCostDAO;
import com.autentia.intra.dao.search.OfferCostSearch;
import com.autentia.intra.util.SpringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.util.List;


public class OfferCostManager {

/* generated by stajanov (do not edit/delete) */


    /**
     * Logger
     */
    private static final Log log = LogFactory.getLog(OfferCostManager.class);

    /**
     * OfferCost DAO *
     */
    private OfferCostDAO offerCostDAO;

    /**
     * Get default OfferCostManager as defined in Spring's configuration file.
     *
     * @return the default singleton OfferCostManager
     */
    public static OfferCostManager getDefault() {
        return (OfferCostManager) SpringUtils.getSpringBean("managerOfferCost");
    }

    /**
     * Empty constructor needed by CGLIB (Spring AOP)
     */
    protected OfferCostManager() {
    }

    /**
     * Default constructor
     *
     * @deprecated do not construct managers alone: use Spring's declared beans
     */
    public OfferCostManager(OfferCostDAO offerCostDAO) {
        this.offerCostDAO = offerCostDAO;
    }

    /**
     * List offerCosts.
     *
     * @param search search filter to apply
     * @param sort   sorting criteria
     * @return the list of all offerCosts sorted by requested criterion
     */
    public List<OfferCost> getAllEntities(OfferCostSearch search, SortCriteria sort) {
        return offerCostDAO.search(search, sort);
    }

    /**
     * Get offerCost by primary key.
     *
     * @return offerCost selected by id.
     */
    public OfferCost getEntityById(int id) {
        return offerCostDAO.getById(id);
    }

    /**
     * Insert offerCost.
     */
    public void insertEntity(OfferCost offerCost) {
        offerCostDAO.insert(offerCost);
    }

    /**
     * Update offerCost.
     */
    public void updateEntity(OfferCost offerCost) {
        offerCostDAO.update(offerCost);
    }

    /**
     * Delete offerCost.
     */
    public void deleteEntity(OfferCost offerCost) {
        offerCostDAO.delete(offerCost);
    }
/* generated by stajanov (do not edit/delete) */
}
