/* 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 */


package com.autentia.intra.manager.contacts;

import com.autentia.intra.businessobject.OfferEnsayo;
import com.autentia.intra.dao.SortCriteria;
import com.autentia.intra.dao.hibernate.OfferEnsayoDAO;
import com.autentia.intra.dao.search.OfferEnsayoSearch;
import com.autentia.intra.util.SpringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.util.List;


public class OfferEnsayoManager {

/* generated by stajanov (do not edit/delete) */


    /**
     * Logger
     */
    private static final Log log = LogFactory.getLog(OfferEnsayoManager.class);

    /**
     * OfferEnsayo DAO *
     */
    private OfferEnsayoDAO offerEnsayoDAO;

    /**
     * Get default OfferEnsayoManager as defined in Spring's configuration file.
     *
     * @return the default singleton OfferEnsayoManager
     */
    public static OfferEnsayoManager getDefault() {
        return (OfferEnsayoManager) SpringUtils.getSpringBean("managerOfferEnsayo");
    }

    /**
     * Empty constructor needed by CGLIB (Spring AOP)
     */
    protected OfferEnsayoManager() {
    }

    /**
     * Default constructor
     *
     * @deprecated do not construct managers alone: use Spring's declared beans
     */
    public OfferEnsayoManager(OfferEnsayoDAO offerEnsayoDAO) {
        this.offerEnsayoDAO = offerEnsayoDAO;
    }

    /**
     * List offerEnsayos.
     *
     * @param search search filter to apply
     * @param sort   sorting criteria
     * @return the list of all offerEnsayos sorted by requested criterion
     */
    public List<OfferEnsayo> getAllEntities(OfferEnsayoSearch search, SortCriteria sort) {
        return offerEnsayoDAO.search(search, sort);
    }

    /**
     * Get offerEnsayo by primary key.
     *
     * @return offerEnsayo selected by id.
     */
    public OfferEnsayo getEntityById(int id) {
        return offerEnsayoDAO.getById(id);
    }

    /**
     * Insert offerEnsayo.
     */
    public void insertEntity(OfferEnsayo offerEnsayo) {
        offerEnsayoDAO.insert(offerEnsayo);
    }

    /**
     * Update offerEnsayo.
     */
    public void updateEntity(OfferEnsayo offerEnsayo) {
        offerEnsayoDAO.update(offerEnsayo);
    }

    /**
     * Delete offerEnsayo.
     */
    public void deleteEntity(OfferEnsayo offerEnsayo) {
        offerEnsayoDAO.delete(offerEnsayo);
    }
/* generated by stajanov (do not edit/delete) */
}
