/* 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 */


package com.autentia.intra.manager.contacts;

import com.autentia.intra.businessobject.OrganizationISOCategory;
import com.autentia.intra.dao.SortCriteria;
import com.autentia.intra.dao.hibernate.OrganizationISOCategoryDAO;
import com.autentia.intra.dao.search.OrganizationISOCategorySearch;
import com.autentia.intra.util.SpringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.util.List;


public class OrganizationISOCategoryManager {

/* OrganizationISOCategory - generated by stajanov (do not edit/delete) */


    /**
     * Logger
     */
    private static final Log log = LogFactory.getLog(OrganizationISOCategoryManager.class);

    /**
     * OrganizationISOCategory DAO *
     */
    private OrganizationISOCategoryDAO organizationISOCategoryDAO;

    /**
     * Get default OrganizationISOCategoryManager as defined in Spring's configuration file.
     *
     * @return the default singleton OrganizationISOCategoryManager
     */
    public static OrganizationISOCategoryManager getDefault() {
        return (OrganizationISOCategoryManager) SpringUtils.getSpringBean("managerOrganizationISOCategory");
    }

    /**
     * Empty constructor needed by CGLIB (Spring AOP)
     */
    protected OrganizationISOCategoryManager() {
    }

    /**
     * Default constructor
     *
     * @deprecated do not construct managers alone: use Spring's declared beans
     */
    public OrganizationISOCategoryManager(OrganizationISOCategoryDAO organizationISOCategoryDAO) {
        this.organizationISOCategoryDAO = organizationISOCategoryDAO;
    }

    /**
     * List organizationISOCategorys.
     *
     * @param search search filter to apply
     * @param sort   sorting criteria
     * @return the list of all organizationISOCategorys sorted by requested criterion
     */
    public List<OrganizationISOCategory> getAllEntities(OrganizationISOCategorySearch search, SortCriteria sort) {
        return organizationISOCategoryDAO.search(search, sort);
    }

    /**
     * Get organizationISOCategory by primary key.
     *
     * @return organizationISOCategory selected by id.
     */
    public OrganizationISOCategory getEntityById(int id) {
        return organizationISOCategoryDAO.getById(id);
    }

    /**
     * Insert organizationISOCategory.
     */
    public void insertEntity(OrganizationISOCategory organizationISOCategory) {
        organizationISOCategoryDAO.insert(organizationISOCategory);
    }

    /**
     * Update organizationISOCategory.
     */
    public void updateEntity(OrganizationISOCategory organizationISOCategory) {
        organizationISOCategoryDAO.update(organizationISOCategory);
    }

    /**
     * Delete organizationISOCategory.
     */
    public void deleteEntity(OrganizationISOCategory organizationISOCategory) {
        organizationISOCategoryDAO.delete(organizationISOCategory);
    }

/* OrganizationISOCategory - generated by stajanov (do not edit/delete) */

}
