/* 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 */


package com.autentia.intra.manager.contacts;

import com.autentia.intra.businessobject.PautaEnsayo;
import com.autentia.intra.dao.SortCriteria;
import com.autentia.intra.dao.hibernate.PautaEnsayoDAO;
import com.autentia.intra.dao.search.PautaEnsayoSearch;
import com.autentia.intra.util.SpringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.util.List;


public class PautaEnsayoManager {


    /**
     * Logger
     */
    private static final Log log = LogFactory.getLog(PautaEnsayoManager.class);

    /**
     * PautaEnsayo DAO *
     */
    private PautaEnsayoDAO pautaDAO;

    /**
     * Get default PautaEnsayoManager as defined in Spring's configuration file.
     *
     * @return the default singleton PautaEnsayoManager
     */
    public static PautaEnsayoManager getDefault() {
        return (PautaEnsayoManager) SpringUtils.getSpringBean("managerPautaEnsayo");
    }

    /**
     * Empty constructor needed by CGLIB (Spring AOP)
     */
    protected PautaEnsayoManager() {
    }

    /**
     * Default constructor
     *
     * @deprecated do not construct managers alone: use Spring's declared beans
     */
    public PautaEnsayoManager(PautaEnsayoDAO pautaDAO) {
        this.pautaDAO = pautaDAO;
    }

    /**
     * List pautas.
     *
     * @param search search filter to apply
     * @param sort   sorting criteria
     * @return the list of all pautas sorted by requested criterion
     */
    public List<PautaEnsayo> getAllEntities(PautaEnsayoSearch search, SortCriteria sort) {
        return pautaDAO.search(search, sort);
    }

    /**
     * Get pauta by primary key.
     *
     * @return pauta selected by id.
     */
    public PautaEnsayo getEntityById(int id) {
        return pautaDAO.getById(id);
    }

    /**
     * Insert pauta.
     */
    public void insertEntity(PautaEnsayo pauta) {
        pautaDAO.insert(pauta);
    }

    /**
     * Update pauta.
     */
    public void updateEntity(PautaEnsayo pauta) {
        pautaDAO.update(pauta);
    }

    /**
     * Delete pauta.
     */
    public void deleteEntity(PautaEnsayo pauta) {
        pautaDAO.delete(pauta);
    }

/* PautaEnsayo - generated by stajanov (do not edit/delete) */


}