/* 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 */


package com.autentia.intra.manager.contacts;

import com.autentia.intra.businessobject.ProductoPrecio;
import com.autentia.intra.dao.SortCriteria;
import com.autentia.intra.dao.hibernate.ProductoPrecioDAO;
import com.autentia.intra.dao.search.ProductoPrecioSearch;
import com.autentia.intra.util.SpringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.util.List;


public class ProductoPrecioManager {

/* generated by stajanov (do not edit/delete) */


    /**
     * Logger
     */
    private static final Log log = LogFactory.getLog(ProductoPrecioManager.class);

    /**
     * ProductoPrecio DAO *
     */
    private ProductoPrecioDAO productoPrecioDAO;

    /**
     * Get default ProductoPrecioManager as defined in Spring's configuration file.
     *
     * @return the default singleton ProductoPrecioManager
     */
    public static ProductoPrecioManager getDefault() {
        return (ProductoPrecioManager) SpringUtils.getSpringBean("managerProductoPrecio");
    }

    /**
     * Empty constructor needed by CGLIB (Spring AOP)
     */
    protected ProductoPrecioManager() {
    }

    /**
     * Default constructor
     *
     * @deprecated do not construct managers alone: use Spring's declared beans
     */
    public ProductoPrecioManager(ProductoPrecioDAO productoPrecioDAO) {
        this.productoPrecioDAO = productoPrecioDAO;
    }

    /**
     * List productoPrecios.
     *
     * @param search search filter to apply
     * @param sort   sorting criteria
     * @return the list of all productoPrecios sorted by requested criterion
     */
    public List<ProductoPrecio> getAllEntities(ProductoPrecioSearch search, SortCriteria sort) {
        return productoPrecioDAO.search(search, sort);
    }

    /**
     * Get productoPrecio by primary key.
     *
     * @return productoPrecio selected by id.
     */
    public ProductoPrecio getEntityById(int id) {
        return productoPrecioDAO.getById(id);
    }

    /**
     * Insert productoPrecio.
     */
    public void insertEntity(ProductoPrecio productoPrecio) {
        productoPrecioDAO.insert(productoPrecio);
    }

    /**
     * Update productoPrecio.
     */
    public void updateEntity(ProductoPrecio productoPrecio) {
        productoPrecioDAO.update(productoPrecio);
    }

    /**
     * Delete productoPrecio.
     */
    public void deleteEntity(ProductoPrecio productoPrecio) {
        productoPrecioDAO.delete(productoPrecio);
    }
/* generated by stajanov (do not edit/delete) */
}