/* 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 */


package com.autentia.intra.manager.bulletin;

import com.autentia.intra.businessobject.BulletinBoardCategory;
import com.autentia.intra.dao.SortCriteria;
import com.autentia.intra.dao.hibernate.BulletinBoardCategoryDAO;
import com.autentia.intra.dao.search.BulletinBoardCategorySearch;
import com.autentia.intra.util.SpringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.util.List;


public class BulletinBoardCategoryManager {

/* BulletinBoardCategory - generated by stajanov (do not edit/delete) */


    /**
     * Logger
     */
    private static final Log log = LogFactory.getLog(BulletinBoardCategoryManager.class);

    /**
     * BulletinBoardCategory DAO *
     */
    private BulletinBoardCategoryDAO bulletinBoardCategoryDAO;

    /**
     * Get default BulletinBoardCategoryManager as defined in Spring's configuration file.
     *
     * @return the default singleton BulletinBoardCategoryManager
     */
    public static BulletinBoardCategoryManager getDefault() {
        return (BulletinBoardCategoryManager) SpringUtils.getSpringBean("managerBulletinBoardCategory");
    }

    /**
     * Empty constructor needed by CGLIB (Spring AOP)
     */
    protected BulletinBoardCategoryManager() {
    }

    /**
     * Default constructor
     *
     * @deprecated do not construct managers alone: use Spring's declared beans
     */
    public BulletinBoardCategoryManager(BulletinBoardCategoryDAO bulletinBoardCategoryDAO) {
        this.bulletinBoardCategoryDAO = bulletinBoardCategoryDAO;
    }

    /**
     * List bulletinBoardCategorys.
     *
     * @param search search filter to apply
     * @param sort   sorting criteria
     * @return the list of all bulletinBoardCategorys sorted by requested criterion
     */
    public List<BulletinBoardCategory> getAllEntities(BulletinBoardCategorySearch search, SortCriteria sort) {
        return bulletinBoardCategoryDAO.search(search, sort);
    }

    /**
     * Get bulletinBoardCategory by primary key.
     *
     * @return bulletinBoardCategory selected by id.
     */
    public BulletinBoardCategory getEntityById(int id) {
        return bulletinBoardCategoryDAO.getById(id);
    }

    /**
     * Insert bulletinBoardCategory.
     */
    public void insertEntity(BulletinBoardCategory bulletinBoardCategory) {
        bulletinBoardCategoryDAO.insert(bulletinBoardCategory);
    }

    /**
     * Update bulletinBoardCategory.
     */
    public void updateEntity(BulletinBoardCategory bulletinBoardCategory) {
        bulletinBoardCategoryDAO.update(bulletinBoardCategory);
    }

    /**
     * Delete bulletinBoardCategory.
     */
    public void deleteEntity(BulletinBoardCategory bulletinBoardCategory) {
        bulletinBoardCategoryDAO.delete(bulletinBoardCategory);
    }

/* BulletinBoardCategory - generated by stajanov (do not edit/delete) */

    /**
     * Get configured public category
     *
     * @return public category object
     */
    public BulletinBoardCategory getPublicCategory() {
        return bulletinBoardCategoryDAO.getPublicCategory();
    }

}
