/* 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 */


package com.autentia.intra.manager.bulletin;

import com.autentia.intra.businessobject.CompanyState;
import com.autentia.intra.dao.SortCriteria;
import com.autentia.intra.dao.hibernate.CompanyStateDAO;
import com.autentia.intra.dao.search.CompanyStateSearch;
import com.autentia.intra.util.SpringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.util.List;


public class CompanyStateManager {

/* CompanyState - generated by stajanov (do not edit/delete) */


    /**
     * Logger
     */
    private static final Log log = LogFactory.getLog(CompanyStateManager.class);

    /**
     * CompanyState DAO *
     */
    private CompanyStateDAO companyStateDAO;

    /**
     * Get default CompanyStateManager as defined in Spring's configuration file.
     *
     * @return the default singleton CompanyStateManager
     */
    public static CompanyStateManager getDefault() {
        return (CompanyStateManager) SpringUtils.getSpringBean("managerCompanyState");
    }

    /**
     * Empty constructor needed by CGLIB (Spring AOP)
     */
    protected CompanyStateManager() {
    }

    /**
     * Default constructor
     *
     * @deprecated do not construct managers alone: use Spring's declared beans
     */
    public CompanyStateManager(CompanyStateDAO companyStateDAO) {
        this.companyStateDAO = companyStateDAO;
    }

    /**
     * List companyStates.
     *
     * @param search search filter to apply
     * @param sort   sorting criteria
     * @return the list of all companyStates sorted by requested criterion
     */
    public List<CompanyState> getAllEntities(CompanyStateSearch search, SortCriteria sort) {
        return companyStateDAO.search(search, sort);
    }

    /**
     * Get companyState by primary key.
     *
     * @return companyState selected by id.
     */
    public CompanyState getEntityById(int id) {
        return companyStateDAO.getById(id);
    }

    /**
     * Insert companyState.
     */
    public void insertEntity(CompanyState companyState) {
        companyStateDAO.insert(companyState);
    }

    /**
     * Update companyState.
     */
    public void updateEntity(CompanyState companyState) {
        companyStateDAO.update(companyState);
    }

    /**
     * Delete companyState.
     */
    public void deleteEntity(CompanyState companyState) {
        companyStateDAO.delete(companyState);
    }

/* CompanyState - generated by stajanov (do not edit/delete) */

}
