/* 
 *  TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 */

package com.autentia.intra.manager.activity;

import com.autentia.intra.businessobject.Objective;
import com.autentia.intra.dao.SortCriteria;
import com.autentia.intra.dao.hibernate.ObjectiveDAO;
import com.autentia.intra.dao.search.ObjectiveSearch;
import com.autentia.intra.util.SpringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.util.List;


public class ObjectiveManager {

/* objective - generated by stajanov (do not edit/delete) */


    /**
     * Logger
     */
    private static final Log log = LogFactory.getLog(ObjectiveManager.class);

    /**
     * Objective DAO *
     */
    private ObjectiveDAO objectiveDAO;

    /**
     * Get default ObjectiveManager as defined in Spring's configuration file.
     *
     * @return the default singleton ObjectiveManager
     */
    public static ObjectiveManager getDefault() {
        return (ObjectiveManager) SpringUtils.getSpringBean("managerObjective");
    }

    /**
     * Empty constructor needed by CGLIB (Spring AOP)
     */
    protected ObjectiveManager() {
    }

    /**
     * Default constructor
     *
     * @deprecated do not construct managers alone: use Spring's declared beans
     */
    public ObjectiveManager(ObjectiveDAO objectiveDAO) {
        this.objectiveDAO = objectiveDAO;
    }

    /**
     * List objectives.
     *
     * @param search search filter to apply
     * @param sort   sorting criteria
     * @return the list of all objectives sorted by requested criterion
     */
    public List<Objective> getAllEntities(ObjectiveSearch search, SortCriteria sort) {
        return objectiveDAO.search(search, sort);
    }

    /**
     * Get objective by primary key.
     *
     * @return objective selected by id.
     */
    public Objective getEntityById(int id) {
        return objectiveDAO.getById(id);
    }

    /**
     * Insert objective.
     */
    public void insertEntity(Objective objective) {
        objectiveDAO.insert(objective);
    }

    /**
     * Update objective.
     */
    public void updateEntity(Objective objective) {
        objectiveDAO.update(objective);
    }

    /**
     * Delete objective.
     */
    public void deleteEntity(Objective objective) {
        objectiveDAO.delete(objective);
    }
/* objective - generated by stajanov (do not edit/delete) */
}
