<%-- 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 *
 --%>


<%@page language="java" contentType="text/html; charset=UTF-8" %>

<%@include file="/inc/tlibs.jsp" %>

<html>
<head>
    <%@include file="/inc/uiCore.jsp" %>
</head>
<body>

<!-- editBulletinBoard.jsp: generated by stajanov code generator -->
<f:loadBundle basename="com.autentia.intra.resources.messages" var="msg"/>
<i:location place="editBulletinBoard" msg="${msg}"/>

<f:view>
    <%@include file="/inc/header.jsp" %>
    <h:form id="bulletinBoard" enctype="multipart/form-data">

        <%-- Header --%>
        <i:titleBar name="${bulletinBoardBean.title}" msg="${msg}">
            <h:commandLink action="#{bulletinBoardBean.save}">
                <h:graphicImage value="/img/save.gif" styleClass="titleImg"/>
            </h:commandLink>
            <h:commandLink action="#{bulletinBoardBean.delete}"
                           onclick="if( !confirm('#{msg['question.confirmDelete']}') ) return false;">
                <h:graphicImage value="/img/delete.gif" styleClass="titleImg"/>
            </h:commandLink>
            <h:commandLink action="#{bulletinBoardBean.list}" immediate="true">
                <h:graphicImage value="/img/back.gif" styleClass="titleImg"/>
            </h:commandLink>
        </i:titleBar>

        <%-- Edition form --%>
        <table class="editTable" cellpadding="0" cellspacing="0">

                <%-- bulletinBoard - generated by stajanov (do not edit/delete) --%>


                <%-- Ignored field: id --%>


                <%-- Field: creationDate --%>
            <tr>
                <td class="editLabelRW">*${msg['bulletinBoard.creationDate']}:</td>
                <td class="editFieldCell">

                    <h:panelGroup>
                        <h:message styleClass="error" showSummary="true" showDetail="false" for="creationDate"/>
                        <t:inputCalendar id="creationDate" value="#{bulletinBoardBean.creationDate}"
                                         required="true" styleClass="requiredFieldClass"
                                         renderAsPopup="true" popupDateFormat="d/MM/yyyy"
                                         renderPopupButtonAsImage="true"
                                         popupTodayString="#{msg['calendar.today']}"
                                         popupWeekString="#{msg['calendar.week']}"
                                />
                    </h:panelGroup>

                </td>
            </tr>

                <%-- Field: title --%>
            <tr>
                <td class="editLabelRW">*${msg['bulletinBoard.title']}:</td>
                <td class="editFieldCell">

                    <h:panelGroup>
                        <h:message styleClass="error" showSummary="true" showDetail="false" for="title"/>
                        <h:inputText id="title" value="#{bulletinBoardBean.title}" size="70" maxlength="128"
                                     required="true"
                                     styleClass="requiredFieldClass"/>
                    </h:panelGroup>

                </td>
            </tr>

                <%-- Field: message --%>
            <tr>
                <td class="editLabelRW">*${msg['bulletinBoard.message']}:</td>
                <td class="editFieldCell">

                    <h:panelGroup>
                        <h:message styleClass="error" showSummary="true" showDetail="false" for="message"/>
                        <h:inputTextarea id="message" value="#{bulletinBoardBean.message}" rows="5" cols="68"
                                         required="true"
                                         styleClass="requiredFieldClass"/>
                    </h:panelGroup>

                </td>
            </tr>

                <%-- Field: documentPath --%>
            <tr>
                <td class="editLabelRW">${msg['bulletinBoard.documentPath']}:</td>
                <td class="editFieldCell">
                    <h:commandLink action="#{bulletinBoardBean.deleteFile}" immediate="true"
                                   rendered="#{bulletinBoardBean.documentPath != null}">
                        <h:graphicImage title="#{msg.entityActions_delete}" value="/img/delete.gif"
                                        styleClass="titleImg"/>
                    </h:commandLink>
                    <i:fileLink type="bulletinBoard" objectId="${bulletinBoardBean.id}"
                                file="${bulletinBoardBean.documentPath}"
                                mime="${bulletinBoardBean.documentContentType}"/>
                    <h:panelGroup>
                        <h:message styleClass="error" showSummary="true" showDetail="false" for="documentPath"/>
                        <t:inputFileUpload id="documentPath" size="58" maxlength="128"
                                           value="#{bulletinBoardBean.uploadDocumentPath}" storage="file"/>
                    </h:panelGroup>

                </td>
            </tr>

                <%-- Ignored field: documentContentType --%>


                <%-- Field: category --%>
            <tr>
                <td class="editLabelRW">*${msg['bulletinBoard.category']}:</td>
                <td class="editFieldCell">

                    <h:panelGroup>
                        <h:message styleClass="error" showSummary="true" showDetail="false" for="category"/>
                        <h:selectOneMenu id="category" value="#{bulletinBoardBean.category}" required="true"
                                         styleClass="requiredFieldClass">
                            <f:selectItems value="#{bulletinBoardBean.categorys}"/>
                            <f:converter converterId="autentia.EntityConverter"/>
                        </h:selectOneMenu>
                    </h:panelGroup>

                </td>
            </tr>

                <%-- Ignored field: user --%>


                <%-- bulletinBoard - generated by stajanov (do not edit/delete) --%>

        </table>

    </h:form>
</f:view>

</body>
</html>  		

